### ISSUE TITLE
Make tickless kernel the default mode

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#10149]
Move to tickless kernel by default.

Should address the issues below as well as set the default to tickless kernel

- [ ] #3651: add tickless idle and kernel support to RISCV32 pulpino
- [ ] #7048: Tickless Kernel Timekeeping Problem
- [ ] #7193: tickless and timeslicing don't play well together
- [ ] #8257: Unify KERNEL_TICKLESS and KERNEL_IDLE
- [ ] #9627: Clean up timeout handling
- [ ] #9904: nRF system timer handling

**Comment by carlescufi** [comment]
CC @pizi-nordic @cvinayak

**Comment by andyross** [comment]
Refactoring in preparation up at #10160 -- that shrinks the driver interface (a lot) and cleans up the intent of the behavior.  It doesn't actually change the way the kernel or drivers work, but it enables a simpler rewrite of both.

**Comment by galak** [comment]
@andyross @nashif is this resolved, can we close this?

**Comment by andyross** [comment]
Oh, yeah.  Long since merged, sorry.
