### ISSUE TITLE
Migrate drivers to Devicetree

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#10516]
Note: Sensors are covered in #9962

* **adc**
	- [x] dw
	- [x] intel_quark_d2000 
	- [x] mcux_adc16
	- [x] mcux_adc
	- [x] nrfx_adc
	- [x] nrfx_saadc
	- [x] sam_afec

* **audio**
	- [x] N/A tlv320dac310x

* **bluetooth**
	- [x] ~nrf51~
	- [x] h4
	- [x] h5
	- [x] spi
	- [x] userchan
	
* **can**
	- [x] stm32

* **clock_control**
	- [x] beetle
	- [x] ? mcux_ccm
	- [x] ? mcux_sim
	- [x] nrf5
	- [ ] ~stm32~

* **console**
	- [ ] N/A ipm
	- [ ] N/A native_posix
	- [ ] ram
	- [ ] rtt
	- [ ] N/A telnet
	- [x] uart_console
	- [x] uart_mcumgr
	- [x] uart_pipe
	- [ ] N/A websocket
	- [ ] N/A xtensa_sim

* **counter**
	- [ ] counter_dtmr_cmsdk_apb
	- [ ] counter_tmr_cmsdk_apb
	- [x] timer_dtmr_cmsdk_apb
	- [ ] timer_tmr_cmsdk_apb

* **crypto**
	- [ ] ataes132a
	- [ ] N/A mtls_shim
	- [ ] N/A tc_shim

* **display**
	- [ ] ili9340
	- [ ] ili9340_adafruit_1480
	- [ ] N/A mb_font
	
* **dma**
	- [ ] cavs
	- [ ] nios2_msgdma
	- [ ] sam_xdmac
	- [ ] stm32f4x

* **entropy**
	- [x] esp32
	- [x] mcux
	- [x] native_posix
	- [x] nrf5
	- [x] stm32 

* **ethernet**
	- [ ] dw
	- [x] e1000
	- [ ] enc28j60
	- [x] mcux
	- [ ] native_posix
	- [ ] sam_gmac
	- [ ] stm32_hal

* **flash**
	- [x] mcux
	- [ ] nios2_qspi
	- [x] nrf
	- [x] sam0
	- [x] stm32
	- [ ] w25qxxdv

* **gpio**
	- [ ] altera_nios2
	- [ ] (missing irq prio) atmel_sam3
	- [x] cc2650
	- [ ] cc32xxx
	- [ ] (missing irq prio) cmsdk_ahb
	- [x] dw
	- [ ] esp32
	- [x] gecko
	- [x] imx
	- [ ] intel_apl
	- [ ] mcux
	- [x] mcux_igpio
	- [ ] mcux_lpc
	- [ ] mmio32
	- [x] nrfx
	- [ ] pcal9535a
	- [ ] pulpino
	- [x] sam
	- [x] sam0
	- [ ] sch
	- [x] sifive
	- [ ] stm32
	- [x] sx1509b

* **grove**
	- [ ] lcd_rgb
	- [ ] light_sensor
	- [ ] temperature_sensor
	
* **i2c** 
	- [ ] i2c (generic Kconfig is instantiating there)
	- [x] sam3
	- [ ] bitbang
	- [x] cc32xx
	- [x] dw
	- [x] esp32
	- [ ] gpio
	- [x] imx
	- [x] ll_stm32
	- [x] mcux 
	- [x] nios2
	- [x] nrfx_twi
	- [x] nrfx_twim
	- [x] ? qmsi
	- [x] ? qmsi_ss
	- [x] sam_twi
	- [x] sam_twihs
	- [x] sbcon
	
* **i2s**
	- [ ] cavs
	- [ ] sam_ssc

* **ieee802154**
	- [ ] cc1200 
	- [x] cc2520
	- [ ] kw41z
	- [x] mcr20a
	- [ ] nrf5 
	- [ ] uart_pipe

* **interrupt_controller**
	- [ ] arcv2_irq_unit
	- [x] cavs_ictl
	- [x] (Partial?) dw_ictl
	- [ ] stm32 
	- [ ] i8259
	- [x] ioapic_intr
	- [ ] loapic_intr
	- [ ] mvic
	- [ ] plic
	- [ ] shared_irq
	- [ ] system_apic

* **ipm**
	- [x] mcux

* **led**
	- [x] lp3943
	- [x] lp5562
	- [x] pca9633
	
* **led_strip**
	- [ ] apa102
	- [ ] lpd880x
	- [ ] ws2812b_sw
	- [ ] ws2812
 
* **modem**
	- [x] wncm14a2a

* **net**
	- [ ] loopback
	- [ ] slip
	
* **pci**
	- [ ] pci

* **pinmux**
	- [ ] cc2650 
	- [ ] esp32 
	- [ ] mcux 
	- [ ] mcux_lpc 
	- [x] sam0 
	- [ ] sifive

* **pwm**
	- [ ] pwm_dw 
	- [ ] imx 
	- [ ] led_esp32 
	- [x] mcux_ftm 
	- [ ] nrf5_sw 
	- [ ] nrfx 
	- [ ] pca9685 
	- [x] stm32

* **rtc**
	- [x] ll_stm32
	- [x] mcux

* **serial**
	- [ ] altera_jtag_hal 
	- [x] cc32xx 
	- [x] cmsdk_apb 
	- [ ] esp32 
	- [x] gecko 
	- [ ] handlers 
	- [x] imx 
	- [x] mcux 
	- [x] mcux_lpsci 
	- [x] mcux_lpuart 
	- [ ] miv 
	- [x] msp432p4xx 
	- [ ] native_posix 
	- [x] nrfx_uart 
	- [x] nrfx_uarte 
	- [x] ns16550 
	- [ ] nsim 
	- [x] psoc6 
	- [x] qmsi 
	- [x] riscv_qemu 
	- [x] sam0 
	- [x] sam 
	- [x] sifive 
	- [x] stellaris 
	- [x] stm32 
	- [x] mcux_lpc 
	- [x] sam

* **spi**
	- [x] dw
	- [x] ll_stm32
	- [x] mcux 
	- [x] mcux_lpspi
	- [x] nrfx_spi
	- [x] nrfx_spim
	- [x] nrfx_spis 
	- [x] sam0
	- [x] sam

Missing:
* **timer**
* **usb**
* **watchdog**
* **wifi**

**Comment by carlescufi** [comment]
@galak should we close this issue now?

**Comment by galak** [comment]
@carlescufi should we close it now :).  I think so.

**Comment by henrikbrixandersen** [comment]
> @carlescufi should we close it now :). I think so.

I agree. This issue does not provide value anymore.
