### ISSUE TITLE
BLE Split Link Layer

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#12681]
The "split link layer" is a version of the BLE controller which is split into:
* An upper, HW independent, LL (ULL)
* A lower, thin, LL (LLL), which depends on the particular HW being used

Currently this split LL is part of the master branch code, but is disabled ([`CONFIG_BT_LL_SW_SPLIT`](https://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_BT_LL_SW_SPLIT.html?highlight=config_bt_ll_sw_split#cmdoption-arg-config-bt-ll-sw-split))

----------------------
This is the list of the missing features to reach parity with the old LL.

- [x] Build the split Link Layer in Zephyr CI (#12689)
- [x] Add support for Data Length Extensions (#13235): @cvinayak 
- [x] Add support for privacy (in platforms with HW address acceleration) (#14675)
- [x] Merge the new Link Layer into master (#12404)
- [x] Encapsulate the `req/ack` code blocks into helper functions ([link](https://github.com/zephyrproject-rtos/zephyr/pull/12404#pullrequestreview-194987023))
- [x] Update/improve controller documentation

-----------------------
Once parity is reached, this new link layer will be the default. The current target is for [release 1.15](https://github.com/zephyrproject-rtos/zephyr/projects/9)
Additional improvements are listed in #13519.

**Comment by carlescufi** [comment]
CC @jhedberg @Vudentz

**Comment by aescolar** [comment]
CC @mtpr-ot @thoh-ot  @wopu-ot

**Comment by aescolar** [comment]
@pskhansen

**Comment by jhedberg** [comment]
Does the new controller support Advertising Extensions "out of the box"? If not, that should be added to the list as well, I suppose.

**Comment by pskhansen** [comment]
@carlescufi A few more tasks for the list:
- Change the role dependent event-done handling from type switch-case to callback concept.
- Move the LLL event prepare/resume queue/handling into LLL.
- Move the LLL-to-ULL Tx ack queue API to ULL domain.

**Comment by jhedberg** [comment]
> @jhedberg it doesn't, but this list is really about reaching feature parity with the existing Link Layer. We already have a GitHub issue for AE.

@carlescufi ok, thanks for clarifying. I think "Add support for Mesh Extensions" confused me, since that's not really (at least fully) supported in the old LL either.

**Comment by aescolar** [comment]
> Out of curiosity, is "remove old link layer" in the road map, or is the intention to support both?

@SebastianBoe : Eventually yes, but the 1st step is to get the split LL to match its functionality

**Comment by koffes** [comment]
@carlescufi @cvinayak if possible, please break down some more of the issues defined here in smaller tasks. Encapsulate the `req/ack` in PR #12681 was a nice bite size for getting started.

**Comment by koffes** [comment]
FYI: I am currently implementing atomic_cas as discussed above.
