### ISSUE TITLE
1.10 Release Checklist

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#1460]
Add items as required
--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-1.10.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-1.10.rst details sections (relative to 1.9.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checkin resulting file scripts/sanity_chk/sanity_last_release.csv
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues/Jira items
  - [x] Review doc/release-notes-1.10.rst overview summary and details sections (see Sign-off below)
  - [x] Update doc/release-notes.rst (add reference to 1.10 notes)
  - [x] Update doc/index.rst (add reference to doc/1.10.0)
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v1.10.0 (with release notes)
  - [x] Update https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update https://www.zephyrproject.org/developers/#downloads
  - [x] Update doc generation (in future should be automatic based on tag)
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] Xtensa, RISCV32, NIOS-II - @nashif, @andrewboie 
--------
- [ ] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [ ] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create checklist for next release
  - [x] Create branch for 1.10.x releases, update github protections for branch

**Comment by dbkinder** [comment]
Concurrent editing loses your changes :(

**Comment by galak** [comment]
@ruuddw, @nashif, @jhedberg, @jukkar, @carlescufi, @MaureenHelm, @andrewboie - Can you guys please take a look at the release notes for your section of ownership

**Comment by carlescufi** [comment]
+1 on Bluetooth release notes (already ticked)

**Comment by MaureenHelm** [comment]
+1

**Comment by ruuddw** [comment]
+1 on release notes

**Comment by galak** [comment]
@dbkinder I've tagged the release, can you handle the following tasks on the website:

 Update https://www.zephyrproject.org/developers/#releases-overview
 Update https://www.zephyrproject.org/developers/#downloads

**Comment by galak** [comment]
@nashif can you update the doc generation for 1.10.0

**Comment by nashif** [comment]
documentation updated

**Comment by dbkinder** [comment]
Release done.
