### ISSUE TITLE
ARM: Core Stack Improvements/Bug fixes for 2.0 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#14744]
This is an umbrella issue for the ARM stack enhancements, including improvements/enhancements made for ARM SoCs and Boards, beyond 1.14 LTS and towards the 2.0 release.

Several of the items below are  related to issues, which have been spotted during the 1.14 feature freeze and tree stabilization, and have, eventually, been moved to the 2.0 Zephyr release.

Items are constantly been added in the list, as issues are been reported and fixed. This will give a quick overview of the implemented fixes/improvements and help with the ARM release notes.

Areas:
- ARM stack 
- ARM SoCs, Boards, Drivers
- Kernel interface to arch
- Memory protection related tests

Scope
- Optimizations
- Coverage
- Feature enhancements
- Bug fixes / Workarounds (or workaround removals, if applicable)
- Clean-up, refactoring

Below is a list of tasks:

- [x] [Enh. ARM Boards] Add memory protection features' support in Arduino Due Board (#14526, #13564)
- [x] [Enh. ARM SoC/Boards] Rework system-timer source selection in ARM SoCs/Boards (#15212)
- [x] [Enh. ARM ] Reduce the IRQ locking time in thread context-switch (#15735)
- [x] [Bug ARM} PrepC does not switch the SP when building with `CONFIG_NO_OPTIMIZATIONS` (#16099, #15794)
- [x] [Bug ARM] System call init code is using the un-provileged stack (#17177 )
- [x] [Bug ARM] z_do_kernel_oops too permissive in user mode (#17591  )
- [x] [Bug ARM] Support for HW stack protection features together with CONFIG_FP_SHARING (currently broken) (#14828)
- [x] ~~[Enh. ARM] Move thread privileged stack area right above the user stack (#14688)~~
- [x] [Enh. ARM] Re-organize arch/include folders into a single one. Move code into c sources. Move internal APIs in /arch, re-organize common arch-calls, remove workarounds (#16136, #16169, #16199, #16355, #16382, #16388  ... )
- [x] [Enh. ARM] Print thread names in `fatal.c` also for ARM (#16253 )
- [x] [Enh, ARM, Tests] Implement a sample/test for `RAMFUNC `feature (#17091)
- [x] [Enh, ARM, Tests] Implement a test for ZERO_LATENCY_IRQS (#16901, #17045)
- [x] [Enh, ARM, Tests] Implement a test for ARM swap ( #17423)
- [x] [Enh, ARM, Tests] Test privilege stack overflow in tests/fatal and test, also for no-usermode (#16859, #16854  )
- [x] [Enh. ARM] Force FP stacking only if FP_SHARING is enabled (#15074)
- [x] [Enh. ARM] Force lazy-stacking preservation feature if FP_SHARING is enabled(#15074 , #2049)
- [x] [Enh. ARM] Implement FLOAT/FP_SHARING properly, i.e without stacking FP context by default (#15074)
- [x] [Enh. ARM] Move core ARM configuration in DTS (#12173, ...)
- [x] ~~[Enh. ARM, Kernel] Privilege stack size could be per-thread configurable, depending on what system-calls are executed. We should investigate.~~
- [x] [Bug. ARM, Tests] Memory Protection -related fixes (#15546 #15728 ,#16757, #16858, #16828, #16780, #16923, #16894, #17146  ...)
- [x] [Enh. ARM] Update CMSIS_5 to latest version (#15827, #16525  )
- [x] [Bug ARM] Assembly compilation for ARMv8-M Baseline (https://github.com/zephyrproject-rtos/sdk-ng/pull/77)
- [x] [Enh. ARMv8-M] QEMU for ARMv8-M (#15305)
- [x] [Enh. ARMv8-M] Non-Secure Callable improvements (#16055 )
- [x] [Bug ARM NXP MPU] Fix configuration of default regions (#17834 , #17603 )
- [x] [Clean-up ARM] Remove unused functions in cpu idle (#18099)

**Comment by ioannisg** [comment]
FYI @agross-korg

**Comment by ioannisg** [comment]
Moving uncompleted issues to 2.1 release and closing this down.
