### ISSUE TITLE
ARM: Fix/Enhance Floating Point for ARM Cortex-M architecture

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#15074]
This is an umbrella issue for fixing the floating point implementation for the ARM stack in Zephyr.

In high-level description, we will focus on the following issues

- [x]  When only `CONFIG_FLOAT `is defined, FP co-processor is not shared between threads. Therefore, we won't be in need of stacking/un-stacking the FP context. The ESF structure can, additionally, skip reserving space for the FP context. FInally, we should not need to initialize the FP context in system boot. Changes will improve interrupt latency and memory consumption. (#15115)
 Un-shared FP Service mode is vulnerable to accidental use of FP context by multiple entities. We could provide a test-mode for Ushared FP that detects multi-usage. See #15292

- [x]  When `CONFIG_FLOAT `and `CONFIG_FP_SHARING `are both defined, FP co-processor is shared between threads. The changes, here, will focus on increasing implementation robustness and performance (see #15964):
   - Activate FP context only on the threads that actually use the FP registers
   - Enable lazy stacking for FPU capable threads (#2049)
   - Implement FP context saving only for FP-active threads
   - [x] Implement stack protection for FPU capable supervisor threads properly (#14828, #16360)
   - [x] Allow threads to disable FP activation (after their work with FP is completed) (#15981 )

- [x]  Finally, we need to fix documentation of FP Services for ARM, to comply with the new, improved design (#15981).
