### ISSUE TITLE
Link Layer Control Procedure overhaul

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#15256]
There are three types of issues that can occur today when handling Control Procedures in the Link layer (both legacy and split):

* Type 1: Peer initiated procedure first and then local initiated procedure will lead to `HCI_CMD_DISALLOWED` 
* Type 2: Local initiated procedure first and then peer initiated procedure will lead to disconnect
* Type 3: Multiple local initiated procedures processed simultaneously, can cause the peer side to disconnect.

We need 2 tables, one per Type, listing the combinations of Control Procedures that can lead to the undesired outcome (`HCI_CMD_DISALLOWED` or disconnection).

## Type 1

| Peer (row) Local (col) | chan_map_update    | conn_update        | phy_req        | phy_ind        | min_used_chan  | ll_ping        |
|------------------------|--------------------|--------------------|----------------|----------------|----------------|----------------|
| phy_req                | HCI_CMD_DISALLOWED | HCI_CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED |
| feature_exchange       | HCI_CMD_DISALLOWED | HCI_CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED |
| versiond_ind           | HCI_CMD_DISALLOWED | HCI_CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED |
| chan_map_update        |                    |                    | CMD_DISALLOWED |                |                | CMD_DISALLOWED |
| length_update          | HCI_CMD_DISALLOWED | HCI_CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED | CMD_DISALLOWED |

## Type 2

| Peer (row) Local (col) | conn_update | chan_map   | phy_upd    | phy_req | encryption
|------------------------|-------------|------------|------------|---------|---------|
| version_ind            | disconnect  | disconnect | disconnect | reject  |            |
| feature_exchange       | disconnect  | disconnect | disconnect | reject  |      |
| length_request         |             |            |            | reject  |                 |
| slave_feature_exch |              |             |            |            | MIC failure |

## Type 3
| Peer (row) Local (col) | conn_param_req |
|------------------------|--------------------|
| feature_exchange | disconnect |

--------------

Following tasks to do have been defined July 2020

Phase 1:
- [x] Combine old and new LLCP implementation, using KConfig for selecting either one
- [x] Integrate new LLCP into LLL controller
- [x] Integrate new LLCP into HCI
- [x] Implement procedure payload for PHY update
- [x] Implement procedure payload for ENCryption start
- [x] Implement procedure payload for Connectup parameter request
- [x] Implement procedure payload for Minimum Number of Used Channels
- [x] Hook procedures into controller logic so that the payload is used
- [x] Implement ACL termination
- [x] Implement Data Length Update
- [x] Implement ENCryption pause
- [x] Implement Channel Map update
- [x] Handle termination of connections, both planned and unplanned

Phase 2:
- [x] Use KConfig for enabling/disabling features
- [x] Add rejection logic for non-supported features
- [x] Handle procedure timeouts
- [x] Handle limited resources: tx-buffers and procedure contexts
- [x] Validate input parameters for the control procedures

Phase 3:
- [x] Add failure handling/invalid PDUs
- [x] Handle Unknown response for local procedures
- [ ] Handle delays in the notification of completed procedures, see issue #45323

Phase 4:
- [x] Fix all TODO's
- [x] Evaluate ASSERTs: either add proper error handling, or leave them

Phase 5: (added march 2021):
- [x] Update topic branch with changes made to control procedures in upstream branch
- [ ] add (design) documentation, see issue #45688
- [x] Create PR for move to upstream
- [x] Succesfully run EBQ, see issue #43435
- [x] Make the new LLCP the default #46462

Following only if code-size is an issue:
- [ ] Optimise code: remove duplicate functionality
- [ ] Optimise code: improve state machines
- [ ] Optimise code: memory management, reuse the RX node in the PDU it is in instead of copying to new memory

Design improvements (added august 2022):
- [ ] Dropping of remote requests, issue #41823
- [ ] Support for advanced scheduling, issue #44339 
- [ ] Race condition in communication between ISR and thread, issue #45427 
- [ ] Possible access to released contexts, issue #48850

See #39435 for the preparations that were done for the upmerge from topic-ble-llcp to main

Timeline in `main`:

- 3.0.0 contains the feature, disabled by default
- 3.2.0 contains the feature, enabled by default
- 3.3.0 remove the old LLCP code

**Comment by joerchan** [comment]
Attached sniffer log of type 3
[type3.zip](https://github.com/zephyrproject-rtos/zephyr/files/3371892/type3.zip)

**Comment by maz3max** [comment]
A sniffer log where both peers try to set the security level to FIPS.
[both_check.zip](https://github.com/zephyrproject-rtos/zephyr/files/3422739/both_check.zip)

**Comment by maz3max** [comment]
A sniffer log where only the central tries to set the security level to FIPS (and fails).
[only-central-checks.zip](https://github.com/zephyrproject-rtos/zephyr/files/3422752/only-central-checks.zip)

**Comment by maz3max** [comment]
@joerchan After the merge of #17836, the peripheral still cannot set the security level right after connecting. I suspect the problem to be on the central side this time.
Logs are here: https://pastebin.com/55kritYE
Sniffer Capture is here (it loops a few times):
[only-periph-req-sec.zip](https://github.com/zephyrproject-rtos/zephyr/files/3538111/only-periph-req-sec.zip)

**Comment by carlescufi** [comment]
> @joerchan After the merge of #17836, the peripheral still cannot set the security level right after connecting. I suspect the problem to be on the central side this time.
> Logs are here: https://pastebin.com/55kritYE
> Sniffer Capture is here (it loops a few times):
> [only-periph-req-sec.zip](https://github.com/zephyrproject-rtos/zephyr/files/3538111/only-periph-req-sec.zip)

Thanks for the report @maz3max. @joerchan can you decide whether this requires a new GH issue to be open, or will it be fixed by an existing PR?

**Comment by joerchan** [comment]
@carlescufi @maz3max :
Reproduced the issue and reported here: https://github.com/zephyrproject-rtos/zephyr/issues/18645

**Comment by carlescufi** [comment]
@pskhansen @cvinayak please discuss the resolution of this issue, there are two options:

- Merge #15320, port it to the split link layer
- Come up with a new approach for control procedures for the split LL, merge #15320 for the legacy link layer

**Comment by carlescufi** [comment]
@kruithofa @erbr-ot @thoh-ot this is the issue tracking the LLCP rework.

**Comment by kruithofa** [comment]
We should also have a look at issue #13519

**Comment by fabiobaltieri** [comment]
@carlescufi can you update this one? Looks like all issues/PRs linked here have been merged/closed, is this done?

**Comment by carlescufi** [comment]
> @carlescufi can you update this one? Looks like all issues/PRs linked here have been merged/closed, is this done?

This can be considered as done for 3.2.0 @fabiobaltieri
