### ISSUE TITLE
2.0 Release Checklist

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#15494]
Add items as required
--------
- [x] Major enhancements:
   - [x]  BLE Split Link Layer: #12681
   - [x]  Support for PPP protocol: #14034 
   - [x]  Initial support for ARM Cortex-R: #9316
   - [x]  Initial support for TEE for ARC: #9341 
   - [x]  A new DTS/binding parser: #17660 
   - [x]  External modules into standalone repositories: #16454
   - [x]  ~~Make newlib libc the default c library: #3102 (Pushed to 2.1.0)~~ 

- [x] Pre RC1 Steps
   - [x] Verify that all external components and external dependencies are up to date, for example 
      - mbedTLS
      - tinycrypt
      - FatFS
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable.

See https://github.com/zephyrproject-rtos/zephyr/wiki/Release-procedure for tagging details

--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-2.0.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-2.0.rst detailed sections (relative to 1.14.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checking resulting file scripts/sanity_chk/sanity_last_release.csv
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues (spell check issue list and fix in GitHub as needed)
  - [x] Review doc/release-notes/release-notes-2.0.rst overview summary and details sections (see Sign-off below)
  - [x] Update doc/release-notes/index.rst (add reference to 2.0 notes)
  - [x] Update doc/index.rst (add reference to doc/2.0.0)
  - [x] Update doc/conf.py (add version to pick list)
  - [x] Update doc/LICENSING.rst for new components that do not have a license
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v2.0.0 (with release notes)
  - [x] Update https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update https://www.zephyrproject.org/developers/#downloads (and git checkout version example)
  - [x] Update doc generation (in future should be automatic based on tag) ping @nashif
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] Xtensa, RISCV32, NIOS-II - @nashif, @andrewboie 
  - [x] Security - @d3zd3z 
--------
- [x] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create branch for 2.0.x releases, update github protections for branch
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Update https://www.zephyrproject.org with latest stats from Github [@dbkinder]
  - [x] Move all PRs/Issues in the 2.0 milestone to the next milestone
  - [x] Close v2.0.0 milestone
  - [x] Create v2.0.1 milestone

**Comment by ioannisg** [comment]
@MaureenHelm @nashif @galak @carlescufi I am trying to resolve this pre-RC1 task:
>  Verify that all external components and external dependencies are up to date, for example mbedtls.

However, now such external components are outside the main repository, so I am wondering, if we can skip this checking now. That would make sense, since these components can be updated independently of the main repo (that is, regardless of feature freeze).

Or: does this, now, mean that we need to tag all repositories together with the main zephyr repo?

**Comment by aescolar** [comment]
@ioannisg, 2 comments fro me:
* There is still a few ext/ in tree (e.g. tinycrypt, which is up to date)
* I would say that them being in a separate repo does not change things here. As you said, you are tagging zephyr with a west manifest which lists the "known to work with" version of those other repos. So those should be up to date

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg, 2 comments from me:
> 
>     * There is still a few ext/ in tree (e.g. tinycrypt, which is up to date)
> 

@aescolar thanks, for your help here :)
Sure, I am aware of the components in the tree; tinucrypt is indeed up-to-date

>     * I would say that them being in a separate repo does not change things here. As you said, you are tagging zephyr with a west manifest which lists the "known to work with" version of those other repos. So those should be up to date

I agree they need to be up-to-date, in general; but does it mean "latest release" or we are ok with "latest major release"?

Second: updating external components (in the standalone repos) and west revisions (in zephyr) will require some testing, righti? if I should do this now, I can't tag -rc1 until this testing is completed. So what level of testing would we need? I suppose green CI should suffice, or?

**Comment by ioannisg** [comment]
@nashif @dbkinder there is one box left to tick in the Final Release Notes, could you check if this has been actually done?

**Comment by dbkinder** [comment]
V2.0.0 docs are published (thanks @nashif ) completing the last item in the “Finalize release notes” section, so I checked that off.

**Comment by ioannisg** [comment]
2.1 Release checklist: https://github.com/zephyrproject-rtos/zephyr/issues/19053
