### ISSUE TITLE
ARM: Core Stack Improvements/Bug fixes for 2.1 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#18173]
This is an umbrella issue for the ARM stack enhancements, including improvements/enhancements made for ARM SoCs and Boards, beyond 2.0 and towards the 2.1 release.

Several of the items below are  related to issues, which have been spotted before and during the 2.0 feature freeze and tree stabilization, and have, eventually, been moved to the 2.1 Zephyr release.

Items are constantly been added in the list, as issues are been reported and fixed. This will give a quick overview of the implemented fixes/improvements and help with the ARM release notes.

Areas:
- ARM stack 
- ARM SoCs, Boards, Drivers
- Kernel interface to arch
- Memory protection related tests

Scope
- Optimizations
- Coverage
- Feature enhancements
- Bug fixes / Workarounds (or workaround removals, if applicable)
- Clean-up, refactoring

Below is a list of tasks:

- [x] [Bug ARM] Support for memory protection features in baseline cores (M0+ and M23) (#12961, #19689, #19794, #20074 )
- [x] [Enh. Bug ARM] Misc bug-fixes and improvements (#17189, #19310, #19318, #19709, #19822, #19825, #20215, #20446 , #20119, #20468 )
- [x] [Enh. ARM] Update CMSIS headers to version 5.6 (#19286)
- [x] [Enh. ARM] Non-overlapping MPU gap-filling needs to be optional (#19067)
- [x] [Enh. ARM] QEMU for ARMv6-M (#2686)
- [x] [Enh. ARM] ARM code naming cleanup (#19491)
- [x] [Enh. ARM] Make ARM Thread Swap test run for Cortex-M0 (#19572)
- [x] [Ehn. ARM]  Make ARM IRQ Vector Table test run for ARMv6-M (#19856)
- [x] [Enh. ARM] Re-work z_arm_is_in_isr and API for nested exception (#19688)
- [x] [Bug ARM] Clobber list in z_arch_switch_to_main_thread() (#16900, #20094)
- [x] [Enh. ARM] Cortex-R enhancements for 2.1 (#19696, #19698 )

**Comment by andrewboie** [comment]
@ioannisg please consider adding https://github.com/zephyrproject-rtos/zephyr/issues/19067 to the list.
I can take a look at implementing it if you don't have the bandwidth.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg please consider adding #19067 to the list.
> I can take a look at implementing it if you don't have the bandwidth.

You're right  @andrewboie that one should be in for 2.1. I 'll include it.

**Comment by ioannisg** [comment]
Unfinished issues moved to  #21201
