### ISSUE TITLE
Tracking Issue for C++ Support as of release 2.1

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#18554]
Issues that impact C++ support as of Zephyr release 2.1

## PR pending
- [ ] #21519 providing thread safety for newlib ; pr #21518

## Resolved
- [x] #1205 involves need for explicit cast from `void *` to `type *` in C++ builds
- [x] #4028 requests new/delete, vectors, RTTI, exceptions, static global dtor.
- [x] #5695 mostly done, but blocked by #18551 ; pr #21397
- [x] #15603 cannot include_next stdhdr.h ; pr #18552 
- [x] #16239 trivial? need to excluded `-Wold-style-definition` from C++ builds ; pr #21398
- [x] #18551 address-of-temporary idiom illegal in C++ ; pr #21397
- [x] #18990, relates to heap alloc with real libc++ ; pr #18464, #20678

**Comment by pabigot** [comment]
@galak @vanwinkeljan FYI.

**Comment by aescolar** [comment]
@pabigot Thanks for collecting this list. If you will be working on this towards 2.1 it would be nice if you could comment it in one of the coming TSC meetings so others are made aware of it.

**Comment by brooksprumo** [comment]
Hi all, I found a C++ issue with mcuboot.h, which was missing `extern "C"` guards.  I've created a PR for it here:

https://github.com/zephyrproject-rtos/zephyr/pull/21916

I'm not sure if this is the right place to track this PR, so please let me know if I should comment elsewhere.

**Comment by cfriedt** [comment]
A while ago I started looking at taking the conventional route to support std::thread, std::mutex, and std::condition_variable (basically wrapping all of it around pthread using gthr.h). Would involve minor modifications to the toolchain. Wrapping pthread requires pthread_create to accept a NULL attr, which requires dynamically allocated thread stacks, ..., dynamic kobject, heap allocator modifications. I'm hopefully at the bottom of that rabbit hole now 😅

A lot of it will be necessary without even using pthread, but wrapping pthread would be a useful shortcut even though it might add to the footprint. Definitely interested in helping out with this effort.

**Comment by nashif** [comment]
2.1 is long gone.
