### ISSUE TITLE
2.1 Release Checklist

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#19053]
Add items as required
--------
- [x] Major enhancements:
   - [ ]  Make newlib libc the default c library: #3102 (Pushed to 2.1.0) 

- [x] Pre RC1 Steps
   - [x] Verify that all external components and external dependencies are up to date, for example 
      - mbedTLS
      - tinycrypt
      - FatFS
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable.

See https://github.com/zephyrproject-rtos/zephyr/wiki/Release-procedure for tagging details

--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-2.1.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-2.1.rst detailed sections (relative to 2.0.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checking resulting file scripts/sanity_chk/sanity_last_release.csv
--------
- [ ] Finalize Release Notes
  - [x] Add list of GitHub issues (spell check issue list and fix in GitHub as needed)
  - [x] Review doc/release-notes/release-notes-2.1.rst overview summary and details sections (see Sign-off below)
  - [x] Update doc/release-notes/index.rst (add reference to 2.1 notes)
  - [x] Update doc/index.rst (add reference to doc/2.1.0)
  - [x] Update doc/conf.py (add version to pick list)
  - [x] Update doc/LICENSING.rst for new components that do not have a license
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v2.1.0 (with release notes)
  - [ ] Update https://www.zephyrproject.org/developers/#releases-overview
  - [ ] Update https://www.zephyrproject.org/developers/#downloads (and git checkout version example)
  - [x] Update doc generation (in future should be automatic based on tag) ping @nashif
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] RISCV - @pgielda @nategraff-sifive
    - [x] Xtensa, NIOS-II - @nashif, @andrewboie 
  - [x] Security - @d3zd3z 
--------
- [ ] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [ ] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create branch for 2.1.x releases, update github protections for branch
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [ ] Update https://www.zephyrproject.org with latest stats from Github [@dbkinder]
  - [x] Move all PRs/Issues in the 2.1 milestone to the next milestone
  - [ ] Close v2.1.0 milestone
  - [x] Create v2.1.1 milestone

**Comment by dleach02** [comment]
Release 2.2 checklist: https://github.com/zephyrproject-rtos/zephyr/issues/21253
