### ISSUE TITLE
ARM: Core Stack Improvements/Bug fixes for 2.2 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#21201]
### ARM Architecture related issues scheduled for v2.2 release

**New features**
- [x] Cortex-A53 (ARMv8, AArch64) support (#20263)
- [x] [ARM Cortex-M] Support for Direct Dynamic Interrupts in ARM-only API (#21516 )

**Feature Enhancements**
- [x] [Enh ARM] Document the ZL IRQ feature (#21765)
- [x] [Enh. ARM] Document the incompatibilities between ARMv7-M and ARMv8-M Mainline
- [x] [Enh. ARM Cortex-M] Document ARM Cortex-M Exception priority model (#22691 )
- [x] [Enh. ARM Cortex-M] Add ARM System Call test (#22691)
- [x] [Enh. ARM Cortex-M] Add Test for irq_lock(), unlock() function usage from user mode
- [x] [Enh. ARM Cortex-M] Cleanup definitions of fixed MPU regions defined at SoC level (#21227)
- [x] [Enh. ARM Cortex-M] Skip redundant MPU runtime clean-up in swap() (#22357)
- [x] [Enh. ARM Cortex-R] Added documentation for Qemu Cortex-R5 platform (#23146)

**Bug Fixes**

- [x] Fix Cortex-M stack limit checking in user mode (#22691)
- [x] Fix Cortex-M MPU races in arch_buffer_validate (#22691)
- [x] Fix Cortex-R power management interrupt handling (#21758)
- [x] Fix Cortex-M linker text section name and clean-up (#21874)
- [x] Fix Cortex-R linker text section name and clean-up (#22672)
- [x] Fix Cortex-M Floating Point initialization in multi-image chain loading (#22977)
- [x] Fix ARMv7-M MPU is_in_region() calculation overflow (#23239 )
- [x] Fix Cortex-M system call dispatch branch instruction (#23323 )

**Comment by jhedberg** [comment]
@ioannisg removed this from the release plan since it doesn't look like it'll make it. It didn't feel right to move it to 2.3 either since some items have been completed.

**Comment by ioannisg** [comment]
> @ioannisg removed this from the release plan since it doesn't look like it'll make it. It didn't feel right to move it to 2.3 either since some items have been completed.

@jhedberg that's fine, so, what I will do is to re-scope it and close this before the release, and move the undone tasks to next release.

**Comment by ioannisg** [comment]
Closing this meta-issue; unfinished tasks moved to #23366
