### ISSUE TITLE
2.2 Release Checklist

### ISSUE THREAD

**Issue by dleach02** [zephyrproject-rtos/zephyr#21253]
Add items as required
--------
- [x] Major enhancements merged

- [x] Pre RC1 Steps
   - [x] Verify that all external components and external dependencies are up to date, for example 
      - mbedTLS
      - tinycrypt
      - FatFS
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable (Security working group).

See https://docs.zephyrproject.org/latest/development_process/release_process.html#tagging for tagging details

--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-2.2.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-2.2.rst detailed sections (relative to 2.1.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checking resulting file scripts/sanity_chk/sanity_last_release.csv @nashif 
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues (spell check issue list and fix in GitHub as needed) using `scripts/release/list_issues.py`
  - [x] Review doc/releases/release-notes-2.2.rst overview summary and details sections (see Sign-off below)
    - [x] Request summary details from code owners
  - [x] Update doc/conf.py (add version to pick list)
  - [x] Update doc/LICENSING.rst for new components that do not have a license
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v2.2.0 (with release notes)
  - [x] Update https://www.zephyrproject.org/developer-resources/#current-release
  - [x] Update doc generation (in future should be automatic based on tag) ping @nashif
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] RISCV - @pgielda @nategraff-sifive
    - [x] Xtensa, NIOS-II - @nashif, @andrewboie 
  - [x] Security - @d3zd3z 
--------
- [x] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create branch for 2.2.x releases, update github protections for branch
  - [x] Create checklist issue for next release #22637
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Move all PRs/Issues in the 2.2 milestone to the next milestone
  - [x] Close v2.2.0 milestone
  - [x] Create v2.3.0 milestone
  - [x] Update current release dates in https://github.com/zephyrproject-rtos/zephyr/wiki/Program-Management and add next release timeline if missing

**Comment by dleach02** [comment]
The main website changed from (or during) the last release so I'm not sure https://www.zephyrproject.org/developers/#downloads has a new place to resolve to. Probably should remove it from the checklist unless someone knows where this should resolve to.

**Comment by jhedberg** [comment]
Next release's checklist is here: https://github.com/zephyrproject-rtos/zephyr/issues/22637

**Comment by jhedberg** [comment]
Closing since all items have been completed (blog post text was just sent to the marketing team)
