### ISSUE TITLE
Merge topic-gpio back to master

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#21789]
In order to merge topic-gpio back to master we need to finalize:

- [x] Complete #18530  
- [x] Complete #20017
- [x] [@pabigot]Clean up `typedef`s: `gpio_devicetree_flags_t` to `gpio_dt_flags_t` ; replace u32_t with role-specific typedefs in function declarations
- [x] [@pabigot] Deprecate functions and macros
- [x] [@pabigot] Remove the old API implementations
- [x] [@pabigot] As soon as master CI is green, freeze merges to master,  rebase the topic branch
- [x] [@nashif] run CI locally, merge topic-gpio to master, unfreeze 
- [x] Final testing on hardware (~10 boards before merge, @pabigot and @mnkp . Rest in master before release)
----
Post-merge:
- [x] [@carlescufi] Send an email to devel@ with a warning of potential master breakage if CI is not rerun on all PRs
- [x] [@mnkp] Add to release notes: summary of changes and impact, e.g. pin enable/disable callback operations deprecated, explain how to use the new API to achieve the same result
- [x] (optional) Make the [porting guide](https://github.com/zephyrproject-rtos/zephyr/issues/20017#issuecomment-549315497) available to users
- [ ] Document the revision range of the lifetime of the topic-gpio branch
----
Post effort:
- [ ] Never go through this again

**Comment by jfischer-phytec-iot** [comment]
Could we skip #20017 and convert GPIO users on master? That would avoid conflict and locks.

**Comment by carlescufi** [comment]
> Could we skip #20017 and convert GPIO users on master? That would avoid conflict and locks.

As discussed before, this would cause sanitycheck to fail because in-tree samples would be using deprecated functions. If you want to propose an alternative mechanism to merge topic-gpio I suggest you take a look first at  @pabigot's [initial roadmap proposal](https://github.com/zephyrproject-rtos/zephyr/issues/18530#issuecomment-527997161).

**Comment by pabigot** [comment]
This comment provides more detail on how I intend to address several of the main issue bullet points.  It may be adjusted based on discoveries and feedback.

Work will begin once #18530 is complete, and #20017 is nearly complete.  At that point the topic branch will again be rebased on master.

The exact order and breakdown of changes into into commits and PRs will be determined as I get into it.  Work-in-progress will probably be exposed in a draft PR.  My intent is to have all this submitted for review by 01 February so we can merge the topic branch to master the week of 03 February.  The deadline is 07 February, but there's no reason to wait until the last minute.

### Generic

* API documentation clarifications not covered by other updates.

### Role-based typedef cleanup

* Change public GPIO API to use `gpio_pin_t` for all parameters that are pin indexes.
* Replace `gpio_devicetree_flags_t` to `gpio_dt_flags_t`.
* Replace `u32_t` by `gpio_port_value_t` for all port API value parameters.

### Function and macro deprecation

* Re-implement `gpio_pin_write()` as `gpio_pin_set_raw()` and deprecate it. Replace all in-tree uses.
* Re-implement `gpio_pin_read()` as `gpio_pin_get_raw()` and deprecate it. Replace all in-tree uses.
* Macro deprecation details TBD.

### Implementation cleanup
* (all drivers) Remove the write and read API functions and references to `GPIO_ACCESS_BY_` macros.
* (all drivers) Remove access_op parameter from API functions.
* (all drivers) Update API function declarations to use role-specific typedefs
* Remove the write and read API functions and `GPIO_ACCESS_BY_` macros from the API function table and generic header.
* Fix return value for internal `get_pending_int` function declaration.

**Comment by carlescufi** [comment]
Closing this since it's not relevant anymore
