### ISSUE TITLE
AArch64 / Cortex-A port improvements / TODO

### ISSUE THREAD

**Issue by carlocaione** [zephyrproject-rtos/zephyr#22411]
https://github.com/zephyrproject-rtos/zephyr/pull/20263 introduced the basic support for AArch64 / Cortex-A.

This issue is used to track the TODO / WiP work.

**WiP**:
- [x] MMU support: https://github.com/zephyrproject-rtos/zephyr/pull/20263#issuecomment-568964341 and https://github.com/zephyrproject-rtos/zephyr/issues/22410 (@Abhishek-brcm) [#22446]
- [ ] Support for Xilinx ZynqMP APU (@carlocaione) [#22418]
- [ ] Rework interrupt handling (remove cascade IRQ controller) (@stephanosio) [#22718]
- [ ] Support SMP and switch to `arch_switch()` (@carlocaione [#22877]

**TODO**:

- [ ] Merge shared code between Cortex-R / Cortex-A
- [ ] Support GICv3  #24850 (@sandeepbrcm )
- [ ] Do not update sp with each STP instruction (https://github.com/zephyrproject-rtos/zephyr/pull/20263#issuecomment-577606572)
- [ ] User-mode Support with EL0

**Comment by carlocaione** [comment]
tagging interested / relevant people: @stephanosio @Abhishek-brcm @sandeepbrcm @timork @Mani-Sadhasivam @andrewboie @Jojjec1 

Feel free to add / modify the list.

**Comment by carlocaione** [comment]
This is outdated. Closing for now.

**Comment by JohnCarterGonzalez** [comment]
Am I correct in assuming that because this issue is closed it means that Zephyr has Cortex A family support?

**Comment by carlocaione** [comment]
> Am I correct in assuming that because this issue is closed it means that Zephyr has Cortex A family support?

yes
