### ISSUE TITLE
2.3 Release Checklist

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#22637]
- [x] Major enhancements:
   - See https://github.com/zephyrproject-rtos/zephyr/projects/9

- [x] Pre RC1 Steps
   - [x] Create v2.4.0 milestone so that features that don't make it to the release can be assigned a milestone
   - [x] Verify that all external components and external dependencies are up to date, for example 
      - mbedTLS
      - tinycrypt
      - FatFS
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable (Security working group).

See https://docs.zephyrproject.org/latest/development_process/release_process.html#tagging for tagging details

--------
- [x] Release Notes WIP
  - [x] Make sure to tell everybody to use the **past tense** (i.e. "X has been added" or "X is now Y")
  - [x] Create draft `doc/releases/release-notes-2.3.rst` with feature summary from https://www.zephyrproject.org/developers/#releases-overview #22923
  - [x] Update `doc/releases/release-notes-2.3.rst` detailed sections (relative to 2.2.0 release) as important issues are addressed (subsystem owners). See #25869
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues (spell check issue list and fix in GitHub as needed) using `scripts/release/list_issues.py`
  - [x] Review `doc/releases/release-notes-2.3.rst` overview summary and details sections (see Sign-off below)
    - [x] Request summary details from code owners
- [x] update `doc/reference/overview.rst`
- [x] Update doc/conf.py (add version to pick list)
- [x] Update doc/LICENSING.rst for new components that do not have a license
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Kernel - @andyross, @andrewboie
    - [x] Build and infrastructure - @tejlmand @nashif @galak  
    - [x] Devicetree - @galak, @mbolivar-nordic 
    - [x] Drivers and sensors - @MaureenHelm, @tbursztyka, @pabigot, @mnkp  
    - [x] Filesystems - @nvlsianpu, @pabigot  
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @joerchan, @carlescufi 
    - [x] USB - @jfischer-phytec-iot @emob-nordic 
    - [x] CAN - @alexanderwachter  
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @ioannisg , @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] RISCV - @pgielda @nategraff-sifive
    - [x] Xtensa, NIOS-II - @nashif, @andrewboie 
  - Board an Soc support - many
  - [x] Security - @d3zd3z 
--------
- [x] Update version in VERSION
- [x] Tag both v2.3.0 and zephyr-v2.3.0
- [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases. Make sure you use the `zephyr-v2.3.0` tag so that the `.zip` that GitHub offers has a reasonable name. Add the release notes to the GitHub release.
--------
- [x] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [x] Update doc generation (in future should be automatic based on tag) ping @nashif
  - [x] Update https://www.zephyrproject.org/developer-resources/#current-release (email Brett)
  - [x] Create `v2.3-branch` branch for 2.3.x releases (from v2.3.0 tag, don't include the switch to patchlevel 99)
  - [x] Merge all post-release PRs in https://github.com/zephyrproject-rtos/zephyr/projects/27
  - [x] Move all PRs/Issues in the 2.3 milestone to the next milestone
  - [x] Close v2.3.0 milestone 
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release and announce the opening of the merge window
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog) (email Kate)
  - [x] Update https://www.zephyrproject.org with latest stats from GitHub (email Brett)
  - [x] Update current release dates in https://github.com/zephyrproject-rtos/zephyr/wiki/Program-Management, move current release column to "past releases table", and add next release timeline if missing (v2.6.0)

**Comment by carlescufi** [comment]
Next release checklist: #26084
