### ISSUE TITLE
Convert SAM SoC drivers to DT_INST

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#23107]
**Is your enhancement proposal related to a problem? Please describe.**

This is to keep tracking of drivers to DT_INST related to Atmel SoCs. The worked started with #22806.

**Describe the solution you'd like**

Move/Create DT_INST for below driver list:
- [X] drivers/adc/adc_sam0.c #24683 #24687 #24789
- [X] drivers/adc/adc_sam_afec.c #24580 #24623
- [X] drivers/counter/counter_sam0_tc32.c #24683 #24687 #24698
- [X] drivers/dma/dma_sam0.c #23739 #24572 #24969
- [x] drivers/dma/dma_sam_xdmac.c #24948
- [X] drivers/entropy/entropy_sam.c #22806 #23740 #24127
- [X] drivers/ethernet/eth_sam_gmac.c #23001 #23031 #23045 #23300 #24057 #24870
- [X] drivers/flash/flash_sam0.c #23739 #24220
- [X] drivers/flash/flash_sam.c #22947 #23740 #24220
- [X] drivers/gpio/gpio_sam0.c #23739 #24679
- [X] drivers/gpio/gpio_sam.c #22634 #23740 #24578
- [X] drivers/hwinfo/hwinfo_sam0.c #23739 #24203
- [ ] drivers/hwinfo/hwinfo_sam.c #22947
- [X] drivers/i2c/i2c_sam0.c #23739 #24250 #24575 #24969
- [X] drivers/i2c/i2c_sam_twi.c #24250 #24506
- [X] drivers/i2c/i2c_sam_twihs.c #24250 #24506
- [x] drivers/i2s/i2s_sam_ssc.c #22630 #24948
- [x] drivers/interrupt_controller/intc_sam0_eic.c #23739
- [X] drivers/pinmux/pinmux_sam0.c #24656 
- [X] drivers/pwm/pwm_sam.c #23740
- [X] drivers/serial/uart_sam0.c #23234 #23289 #23739 #24110 #24572 #24969
- [X] drivers/serial/uart_sam.c #22630 #24110 #24319
- [X] drivers/serial/usart_sam.c #22630 #22634 #24110 #24319
- [X] drivers/spi/spi_sam0.c #24575 #24969
- [X] drivers/spi/spi_sam.c #24638
- [X] drivers/timer/sam0_rtc_timer.c #23739  #24401
- [x] drivers/usb/device/usb_dc_sam0.c #23739
- [X] drivers/usb/device/usb_dc_sam.c #24598
- [x] drivers/watchdog/wdt_sam0.c #23739
- [X] drivers/watchdog/wdt_sam.c #22806 #23740

SoC:
- [X] soc/arm/atmel_sam0/samd20/dts_fixup.h #23739 #24250
- [X] soc/arm/atmel_sam0/samd21/dts_fixup.h #23739 #24250
- [X] soc/arm/atmel_sam0/samd51/dts_fixup.h  #23739 #24250
- [X] soc/arm/atmel_sam0/same51/dts_fixup.h  #23739 #24250
- [X] soc/arm/atmel_sam0/same53/dts_fixup.h #23739 #24250
- [X] soc/arm/atmel_sam0/same54/dts_fixup.h #23739 #24250
- [X] soc/arm/atmel_sam0/samr21/dts_fixup.h #23739 #24250
- [X] soc/arm/atmel_sam/common/atmel_sam_dt.h #24319 #24487
- [X] soc/arm/atmel_sam/sam3x/soc.h #24297 #24319 #24250 #24487 #24578
- [X] soc/arm/atmel_sam/sam4e/soc.h #24319 #24250 #24487 #24578 #24948
- [X] soc/arm/atmel_sam/sam4s/soc.h #24319 #24250 #24487 #24578 #24948
- [X] soc/arm/atmel_sam/same70/soc.h #24319 #24250 #24487 #24578 #24948
- [X] soc/arm/atmel_sam/samv71/soc.h #24319 #24250 #24487 #24578 #24948
- [X] soc/arm/atmel_sam/sam3x/soc_pinmap.h #24319 #24506
- [X] soc/arm/atmel_sam/sam4e/soc_pinmap.h #24319 #24506 #24870 #24948
- [X] soc/arm/atmel_sam/sam4s/soc_pinmap.h #24319 #24506 #24948
- [X] soc/arm/atmel_sam/same70/soc_pinmap.h #24319 #24506 #24580 #24870 #24948
- [X] soc/arm/atmel_sam/samv71/soc_pinmap.h #24319 #24506 #24580 #24870 #24948
- [X] soc/arm/atmel_sam/sam3x/dts_fixup.h #24319 #24506
- [X] soc/arm/atmel_sam/sam4e/dts_fixup.h #24319 #24506
- [X] soc/arm/atmel_sam/sam4s/dts_fixup.h #24319 #24506
- [X] soc/arm/atmel_sam/same70/dts_fixup.h #24319 #24506 #24580 #24598
- [X] soc/arm/atmel_sam/samv71/dts_fixup.h #24319 #24506 #24580 #24598

Boards:
- [X] boards/arm/sam_e70_xplained/pinmux.c #23932
- [X] boards/arm/sam_v71_xult/pinmux.c #23932

Others:
- [X] drivers/ieee802154/ieee802154_rf2xx.c #23779 #24096
- [X] General #24161
- [X] sam0: tests/drivers/uart/uart_async_api #24610 #24588 #24586
- [X] sam0: Implement Linux style device tree clock control #15585
- [X] DTS API #25009
- [X] dts: ethernet: rework how we deal with mac-address setting #24651

Pinctrl:
Feature #24236 #24319

Issues:
#23281 fixed by #23289
#23415 fixed by #23427
#24399 fixed by #24401

**Comment by nandojve** [comment]
@galak

**Comment by nandojve** [comment]
@carlescufi @benpicco @stephanosio

**Comment by nandojve** [comment]
@jhedberg

**Comment by galak** [comment]
@nandojve are you able to get back to look at conversions for SAM now that we have the new DT macro's in place.  Here's what I have (the # is count of DT_ references that need modification, or a rough estimate).

```
     10 drivers/adc/adc_sam_afec.c
      2 drivers/flash/flash_sam.c
     35 drivers/gpio/gpio_sam.c
      2 drivers/hwinfo/hwinfo_sam.c
     12 drivers/i2c/i2c_sam_twi.c
     18 drivers/i2c/i2c_sam_twihs.c
     35 drivers/serial/uart_sam.c
     24 drivers/serial/usart_sam.c
      5 drivers/spi/spi_sam.c
     28 drivers/usb/device/usb_dc_sam.c

     13 drivers/adc/adc_sam0.c
      9 drivers/counter/counter_sam0_tc32.c
     12 drivers/gpio/gpio_sam0.c
     35 drivers/i2c/i2c_sam0.c
     12 drivers/pinmux/pinmux_sam0.c
     46 drivers/serial/uart_sam0.c
     43 drivers/spi/spi_sam0.c
```

**Comment by nandojve** [comment]
Hi @galak, I can take look at weekend and try update full list. I saw tons of DT_INST moving and probably lots of SAM related.

**Comment by galak** [comment]
> Hi @galak, I can take look at weekend and try update full list. I saw tons of DT_INST moving and probably lots of SAM related.

Thanks.  All the DT_INST conversions should be complete.  This work now would be moving away from something like `DT_ATMEL_SAM0_SPI_...` to `DT_INST` and `DT_NODELABEL` (nodelabel form used for cases like pinmux.c that you need to know the specific instance).  The idea being that the node label in dts will match the SoC docs naming.

**Comment by nandojve** [comment]
@galak I believe is almost done with Atmel SAM/SAM0.

Drivers converted however not define the global DT_DRV_COMPAT:
drivers/hwinfo/hwinfo_sam.c

Drivers without DT support:
drivers/dma/dma_sam_xdmac.c
drivers/i2s/i2s_sam_ssc.c

**Comment by galak** [comment]
> @galak I believe is almost done with Atmel SAM/SAM0.
> 
> Drivers converted however not define the global DT_DRV_COMPAT:
> drivers/hwinfo/hwinfo_sam.c

I'm not sure it makes sense in this case, but ok if you want to submit a PR for it.

> Drivers without DT support:
> drivers/dma/dma_sam_xdmac.c
> drivers/i2s/i2s_sam_ssc.c

Done.

**Comment by nandojve** [comment]
Atmel SoC DT_INST migration was concluded.
