### ISSUE TITLE
ARM: Core Stack Improvements/Bug fixes for 2.3 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#23366]
### ARM Architecture related issues tentatively scheduled for v2.3 release

**New features**
- [x] [ARM] Support CMSIS-DSP integration (#24307)
- [x] [ARM] Add semihosting console (#21073)

**Feature Enhancements**

- [x] [Enh. ARM Cortex-M] Move Core (Cortex-M) CMSIS in own repository
- [x] [Enh. Cortex-R] Refactor ARM interrupt system (Cortex-A & Cortex-R) (#22718)
- [x] [Enh. Cortex-R] CMSIS support (#22740)
- [x] [Enh. Cortex-R] Support nested interrupts (#23636, #23614)
- [x] [Enh. Cortex-A AArch64] Support nested interrupts (#23685)
- [x] [Enh. Cortex-M] Clean-up z_arm_reserved from vector exception entries (#24012)
- [x] [Enh. Cortex-R] Rework to establish base exception handling framework (#24192)
- [x] [Enh. Cortex-A] Add CMSIS Core-A (#24201)
- [x] [Enh. ARM] Update CMSIS version to 5.7.0 (#24257)

**Bug Fixes**
- [x] [ARM Cortex-M/R] Fix arch_cpu_idle() implementation (#23511, #23652)
- [x] [ARM Cortex-M] Fix and test Cortex-M spurious IRQ handler behavior (#23356)
- [x] [ARM Cortex-A] Missing ASM_FILE_PROLOGUE (#23379)
- [x] [ARM Cortex-M] Properly applying ARMv7-M workaround for stack adjustment (#25612, #25609 )
- [x] [ARM Cortex-M] Fix Stacking Error reporting (#25612)
- [x] [ARM Cortex-M] Fix workaround placements for ARMv7-M MPU stack size adjustment (#25654 )
