### ISSUE TITLE
Convert STM32 drivers to new DT macros

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#23529]
In https://github.com/zephyrproject-rtos/zephyr/pull/23285, some STM32 have been converted to DT_INST usage to help cleaning up fixup files.
For remaining drivers this was not possible to use DT_INST for various documented reasons.
Work should be completed by using new DT macros (such as DT_NODELABEL_FOO).
List of these drivers is:
- [x] drivers/can/can_stm32.c (cf below comment)
- [x] drivers/ethernet/eth_stm32_hal.c (Only impact `DT_DTCM_BASE_ADDRESS`. To be removed?)
- [x] drivers/flash/flash_stm32f3x.c (Only impact `DT_FLASH_SIZE`. To be removed ?) (#24247)
- [x] drivers/flash/flash_stm32l4x.c (Only impact `DT_FLASH_SIZE`. be removed ?) (#24247)
- [x] drivers/gpio/gpio_stm32.c (cf below comment) (#23988)
- [x] drivers/i2c/i2c_ll_stm32.c (cf below comment) (#24342)
- [x] drivers/i2s/i2s_ll_stm32.c (cf below comment) (#24204)
- [x] drivers/timer/stm32_lptim_timer.c (To be converted to DT first)

Reasons for not being able to convert to DT_INST are documented here: https://github.com/zephyrproject-rtos/zephyr/pull/22807#issuecomment-592481101

**Comment by erwango** [comment]
This has been completed
