### ISSUE TITLE
Fix devicetree documentation for new API

### ISSUE THREAD

**Issue by mbolivar-nordic** [zephyrproject-rtos/zephyr#25469]
The devicetree documentation contains errors and is missing descriptions due to late-breaking semantic changes which had to go in before code freeze. This issue tracks the necessary work I'm aware of. Release notes are tracked separately in #22637.

- [x] DTC_OVERLAY_FILE description says colon-separated, that's wrong (https://github.com/zephyrproject-rtos/zephyr/pull/25470)
- [x] centralize documentation of chosen zephyr nodes in a non-legacy file, provide a reference to them from the intro (https://github.com/zephyrproject-rtos/zephyr/pull/25470)
- [x] review doxygen docstrings and correct errors for generic APIs (https://github.com/zephyrproject-rtos/zephyr/pull/25470)
- [x] add introductory text to each section in the API reference (https://github.com/zephyrproject-rtos/zephyr/pull/25470)
- [x] review doxygen docstrings and correct errors for instance APIs (#25633)
- [x] review doxygen docstrings and correct errors for hw specific APIs (#25633)
- [x] address outstanding comments from #25009 (#25633)
- [x] review user guides and correct errors (#25633)
- [ ] write a migration guide for moving to the new API
- [ ] check if zephyr v2.2 restriction in https://docs.zephyrproject.org/latest/guides/dts/bindings.html#bindings-file-syntax is still an issue
