### ISSUE TITLE
ARM: Core Stack Improvements/Bug fixes for 2.4 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#25927]
### ARM Architecture related issues tentatively scheduled for v2.4 release

**New features**
- [X] [Cortex-M] Support for Cortex-M1 
- [X] [Cortex-M] timing functionality based on DWT

**Feature Enhancements**

- [x] [Enh. ARM Cortex-M] Add ARM Cortex-M test for IRQ target state management (#22133)
- [x] [Enh. ARMv8-m] Make built-in stack overflow a default feature (=y)
- [x] [Enh. ARCHitectures, Kernel] Support distinct ways for allocating stack areas for default and supervisor-only threads (#13637, #24714)
- [x] [ARM] Make threads use `K_THREAD_STACK_SIZEOF `and remove workaround for ARM 's `z_new_thread()` (#14269, #24714)
- [x] [Enh. Cortex-M] Clean-up and enhance SW vector relaying for Baseline Cortex-M (#26289)
- [x] [Enh. Cortex-M] Extend SW vector relaying for Mainline Cortex-M (#26276)
- [x] [Enh. Cortex-M] Include full register state in ARM Cortex M Exception Stack Frame  (#27495)
- [x] [Enh Cortex-M] Lock scheduler while doing secure calls.

**Bug Fixes**

- [x] [Bug ARM Cortex-M] Stack randomization for main thread (#23702)
- [x] [Bug ARM Cortex-M] Vector Tables are not aligned properly in the linker (#26800)
- [x] [Bug ARM Cortex-A,R,M] Vector Tables and Relay Vector table symbols are exported as GTEXT (#27039)
- [x] [Bug QEMU] Fix timer driver on QEMU Cortex-M0 and restore test coverage (#26189)
- [x] [Bug Cortex-M] Fix Cortex-M Boot with CONFIG_MULTITHREADING=n

**Comment by ioannisg** [comment]
Open items moved to #28729
