### ISSUE TITLE
[topic-usb] USB stack rework. ToDo list.

### ISSUE THREAD

**Issue by emob-nordic** [zephyrproject-rtos/zephyr#26935]
## Introduction

This issue is created to list all things that should be reworked in [topic-usb](https://github.com/zephyrproject-rtos/zephyr/tree/topic-usb) before its merged into master.

### Problem description

USB device stack requires rework to address feature requests that we currently have. Some of them:

- #20236 usb: api: Cleanup of current inclusion path for USB
- #19713 usb: investigate if Network Buffer can be used in USB device stack and USB drivers
- #24200 USB GET_INTERFACE response always 0, even when an alternate setting is used
- ~#25604 USB: enable/disable a class driver at runtime~
- #29135 usb: allow the instances of a USB class to be enabled and disabled at runtime 

### ToDo list:

- [x] Extend the possibility to have more than one alternate setting for interface. (follow up of #26733)
        This point requires updates to `struct usb_if_descriptor`. @emob-nordic 
- [x] Make all drivers use bitfields introduced in #26854. Remove direction, type and recipient [getter macros](https://github.com/zephyrproject-rtos/zephyr/blob/a2d4292a96e0e3f710374b6da6d3d5060bccc905/include/usb/usbstruct.h#L39-L41). @jfischer-phytec-iot 
- [x] USB Framework (Chapter 9) defines and structures rework/cleanup #27045
- [ ] Introduce USB device state tracing in USB device core so that classes would copy/paste same code in `status_callback` like #27119 (HID) and #27025 (CDC) do.
- [ ] Use net_bufs and common `usb_transfer` mechanism across the stack (Addressing issues: #19713 #26857)

**Comment by koffes** [comment]
Geetings! Has a timeline been set for this task?

**Comment by emob-nordic** [comment]
@koffes The work has started but We cannot say the exact timing.

**Comment by koffes** [comment]
What is the status of this issue?

**Comment by jfischer-no** [comment]
> What is the status of this issue?

Is almost ready.

**Comment by jfischer-no** [comment]
Close in favor of #42066
