### ISSUE TITLE
samples without README

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#27805]
Taking #27130 to the next step: The following samples do not have a README:

* [ ] samples/boards/esp32/ethernet
* [ ] samples/boards/nrf/nrf53_sync_rtc/net
* [ ] samples/drivers/lcd_cyclonev_socdk
* [ ] samples/drivers/led_apa102c_bitbang
* [ ] samples/drivers/spi_fujitsu_fram
* [ ] samples/sensor/bmg160
* [ ] samples/sensor/max44009 (has a README)
* [ ] samples/sensor/sx9500  (has a README.txt)
* [ ] samples/shields/npm6001_ek
* [ ] samples/subsys/ipc/ipc_service/static_vrings/remote
* [ ] samples/subsys/logging/multidomain
* [ ] samples/subsys/mgmt/osdp/control_panel
* [ ] samples/subsys/mgmt/osdp/peripheral_device
* [ ] samples/subsys/pm/device_pm
* [ ] samples/subsys/pm/latency
* [ ] samples/subsys/rtio/sensor_batch_processing
* [ ] samples/subsys/shell/devmem_load
* [x] samples/bluetooth/mtu_update/central
* [x] samples/bluetooth/mtu_update/peripheral
* [x] samples/drivers/ipm/ipm_mcux/remote
* [x] samples/drivers/lora/receive
* [x] samples/drivers/lora/send
* [x] samples/drivers/mbox/remote
* [x] samples/drivers/spi_flash (pr #27805)
* [x] samples/drivers/watchdog
* [x] samples/modules/thrift/hello/client (in hello/)
* [x] samples/modules/thrift/hello/server (in hello/)
* [x] samples/net/mdns_responder (pr #27866)
* [x] samples/posix/eventfd
* [x] samples/sensor/fxos8700-hid
* [x] samples/sensor/grove_light
* [x] samples/sensor/grove_temperature
* [x] samples/sensor/thermometer (has a README.txt)
* [x] samples/subsys/console/echo
* [x] samples/subsys/fs/format
* [x] samples/subsys/shell/shell_module
* [x] samples/subsys/tracing (has a README.txt)

**Comment by pabigot** [comment]
```
find samples/ -name sample.yaml \
| sed -e 's@/[^/]*$@@' \
| while read dir ; do \
  if $(cd $dir && ls | grep -i '^readme' > /dev/null) ; then \
    :  ; \
  else  \
    echo '* [ ]' $dir ; \
   fi \
done \
| sort
```

**Comment by Nukersson** [comment]
I think `Good First Issue` would be good for the beginners.

**Comment by kartben** [comment]
I've updated the checklist in the initial comment with the current status. I've also made sure samples with a README that's not a README.rst are also listed

**Comment by Spice-Weasel** [comment]
I will document the lora samples

**Comment by kartben** [comment]
> I will document the lora samples

Very nice, thanks!

**Comment by kartben** [comment]
@Spice-Weasel let me know if I can help with anything as you go through this. Thanks again!

**Comment by Spice-Weasel** [comment]
@kartben will do. I thought this was lorawan and not lora. 😅 I can document it anyway will try to find some time this weekend

**Comment by kartben** [comment]
Note to self (or to anyone else reading this and looking for inspiration of what samples might be of higher priority than others): adding the README to ` samples/subsys/shell/shell_module` would be really nice as it's quite a "key" sample for people interesting in developing shell commands, and having some clarity on what the purpose of the sample is would be really useful (some people have started to incorrectly use it as a place to dump overlays and config files that can be used to try all kinds of shell commands on a board, and that's not what this sample is for).

**Comment by Spice-Weasel** [comment]
@kartben thanks. I'll have a look at it!

**Comment by isaacjerish** [comment]
I'd like to work on the README for samples/sensor/max44009.

**Comment by qbx11** [comment]
## Updated list and improved search script

The script in the issue body doesn't account for samples that share a README in a parent directory
(e.g. `samples/bluetooth/channel_sounding/README.rst` covers all sub-samples under it).

### Improved script:
```bash
find samples/ -name sample.yaml \
  | sed -e 's@/[^/]*$@@' \
  | while read dir ; do \
      found=0 ; \
      d="$dir" ; \
      while [ "$d" != "." ] && [ "$d" != "samples" ] ; do \
        if ls "$d" | grep -qi '^readme' ; then \
          found=1 ; \
          break ; \
        fi ; \
        d=$(dirname "$d") ; \
      done ; \
      if [ $found -eq 0 ] ; then \
        echo '* [ ]' $dir ; \
      fi \
    done \
  | sort
```

### Updated list: (as of 20 April 2026)
* [ ] samples/boards/microchip/mec172xevb_assy6906/qmspi_ldma
* [ ] samples/boards/microchip/mec172xevb_assy6906/rom_api
* [x] samples/drivers/lcd_cyclonev_socdk [Pending review: #106593]
* [x] samples/drivers/soc_flash_nand [Pending review: #106632]
* [x] samples/drivers/spi_fujitsu_fram [Pending review: #106709]
* [ ] samples/shields/npm13xx_ek
* [ ] samples/shields/npm2100_ek
* [ ] samples/shields/npm6001_ek
* [x] samples/subsys/logging/multidomain [Pending review: #106319]
* [x] samples/subsys/pm/latency [Pending review: #105109]
* [x] samples/tfm_integration/config_build [Pending review: #106708]

**Comment by LuaBerry** [comment]
Hi, I’d like to work on adding the README for `samples/subsys/pm/latency`! If no one is working on it already.

**Comment by kartben** [comment]
> Hi, I’d like to work on adding the README for `samples/subsys/pm/latency`! If no one is working on it already.

see https://github.com/zephyrproject-rtos/zephyr/pull/105109 :)

**Comment by LuaBerry** [comment]
> > Hi, I’d like to work on adding the README for `samples/subsys/pm/latency`! If no one is working on it already.
> 
> see [#105109](https://github.com/zephyrproject-rtos/zephyr/pull/105109) :)

Thanks for the notice! I didn't see the updated list above.

I just found out that `samples/shields/npm13xx_ek`, `samples/shields/npm2100_ek`, and `samples/shields/npm6001_ek` already have documentation files in their directories, but they are named `index.rst` instead of `README.rst`.

Their contents look very similar to the `README.rst` files used in other samples.
Since this seems like a simple consistency issue, would you still prefer a PR for it, or is it better handled directly?

**Comment by LuaBerry** [comment]
I noticed that some existing `README.rst` files may not follow the current `doc/templates/sample.tmpl` style. For example, they do not start with `.. zephyr:code-sample::`.

I generated a candidate list with a quick search script.
`find samples -name README.rst -type f | xargs grep -L '^\.\. zephyr:code-sample::'`

Would updating these README files also be in scope for this issue, or should it be handled in a separate issue?
