### ISSUE TITLE
ARM: Core Stack Improvements/Bug fixes for 2.6 release

### ISSUE THREAD

**Issue by ioannisg** [zephyrproject-rtos/zephyr#28729]
### ARM Architecture related issues tentatively scheduled for v2.6 release

**New features**
- [x] [Cortex-M] QEMU support for ARM Cortex-M4F (#23185)
- [x] [Cortex-M] Null Pointer Exception detection in ARM Cortex-m (#3634 )

**Feature Enhancements**

- [x] [ARM Cortex-M, ARC, Kernel] Consider moving the arm_core_mpu API above the arch- level, so as not to duplicate for ARM, ARC

**Comment by bbolen** [comment]
I'm not sure if you saw #28231 , but it may be worth considering for 2.5

**Comment by ioannisg** [comment]
> I'm not sure if you saw #28231 , but it may be worth considering for 2.5

Sure, pls, just add this to the above list. (This ticket is only a meta issue for our convenience, to have the overview of what's done in each release)

**Comment by ioannisg** [comment]
Moving all these to 2.6 release

**Comment by galak** [comment]
@ioannisg can you clear this out / migrate to a 2.7 version.

**Comment by ioannisg** [comment]
> @ioannisg can you clear this out / migrate to a 2.7 version.

Yeap, already started doing that.

**Comment by ioannisg** [comment]
@galak moving remaining tasks in the ticket for 2.7 release.
