### ISSUE TITLE
Support for H3ULCB Renesas board

### ISSUE THREAD

**Issue by julien-massot** [zephyrproject-rtos/zephyr#33274]
**Is this request related to a missing driver support for a particular hardware platform, SoC or board? Please describe.**
The H3ULCB contains cortex A57/A53 that is often use to run Linux based OS, but also have a Cortex-R7.
The plan is to add support for this Cortex-r7 and some I/O.
The H3ULCB has an H3 SoC (r8a77951) from the R-Car Gen3 SoC series

Here is the checklist to get basic support:

- [x] Cortex-R7 support #31250 
- [x] R-Car Gen3 SoC series #31307 
- [x] H3ULCB basic dts and SoC definition (Ram console, GPIO, clock control) #31307
- [x] Enable CPU cache and branch prediction #36126
- [x] Renesas R-Car Pinmux  #40550
- [x] Renesas R-Car UART driver for console (polling) #34933
- [x] Renesas R-Car Classic CAN driver #34892
- [x] Renesas R-Car I2C driver #35387
- [ ] Renesas R-Car IPM driver to allow OpenAMP communication
- [x] Renesas R-Car UART driver for console (interrupt driven) #36283
- [x] West debug/flash support #37078

**Comment by julien-massot** [comment]
Let's consider that all the basic support has land into Zephyr.
The only missing point is IPM driver that needs synchronization with possible
other RTOS for Gen3.
Thanks to all reviewers and maintainers !
