### ISSUE TITLE
Bluetooth: controller: Review and back port fixes to Zephyr v1.14-branch

### ISSUE THREAD

**Issue by cvinayak** [zephyrproject-rtos/zephyr#33271]
**Describe the bug**
Review and back port upstream functional bug fixes to Zephyr v1.14-branch

Some of them:

- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/25634
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/27507 --> https://github.com/zephyrproject-rtos/zephyr/pull/33760
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/31571
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/33272 --> https://github.com/zephyrproject-rtos/zephyr/pull/33759
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/33278 --> https://github.com/zephyrproject-rtos/zephyr/pull/33760
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/33310 --> https://github.com/zephyrproject-rtos/zephyr/pull/34122
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/33340
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/34237

**To Reproduce**
NA

**Expected behavior**
Fixes equally fixed in Zephyr 1.14.x LTS release candidates

**Impact**
annoyance, showstopper

**Logs and console output**
As present in upstream fixes post v1.14 releases

**Environment (please complete the following information):**
As present in upstream fixes post v1.14 releases

**Additional context**
NA

**Comment by carlescufi** [comment]
Closing this since no more 1.14 dot releases are going to be released.
