### ISSUE TITLE
Bluetooth: Switch to inclusive terminology from the 5.3 specification

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#38348]
The inclusive naming mappings can be found here:
https://btprodspecificationrefs.blob.core.windows.net/language-mapping/Appropriate_Language_Mapping_Table.pdf

The item will be discussed in the API meeting so seek acceptance for inclusion in 2.7.0.

Areas to be covered:

- [x] include/bluetooth (excluding hci.h): #38522
- [x] include/bluetooth/hci.h #38605
- [x] subsys/bluetooth/host: #38640
- [x] subsys/bluetooth/controller: #38687
- [x] subsys/bluetooth/mesh #38356
- [x] subsys/bluetooth/other #38640 
- [x] drivers/bluetooth/
- [x] samples/bluetooth
- [x] tests/bluetooth #38640

**Comment by carlescufi** [comment]
CC @jhedberg @joerchan @alwa-nordic @asmk-ot @wopu-ot @kruithofa @Thalley @Vudentz @asbjornsabo @sjanc @andrzej-kaczmarek @KKopyscinski @trond-snekvik @LingaoM @michal-narajowski @ppryga

**Comment by Thalley** [comment]
@carlescufi Is there anything in `subsys/bluetooth/audio` that would require a change?

**Comment by carlescufi** [comment]
API meeting:

- The version of the specification that replaces the terms with inclusive ones is 5.3
- All Bluetooth subsystems will claim compliance with the 5.3 version of the spec in Zephyr 2.7.0
- General consensus is to allow for the change, as long as it only involves replacing the terms and is well documented in the release notes for 2.7.0
- Requires TSC approval

**Comment by carlescufi** [comment]
> @carlescufi Is there anything in `subsys/bluetooth/audio` that would require a change?

I am not sure about that @Thalley. Can you check?

**Comment by Thalley** [comment]
> > @carlescufi Is there anything in `subsys/bluetooth/audio` that would require a change?
> 
> I am not sure about that @Thalley. Can you check?

A quick course search reveals nothing. Do we have a list of words that has/should be changed? Should be able to write a fairly quick script to validate.

**Comment by carlescufi** [comment]
All done!
