### ISSUE TITLE
Collection of various issues related to I2C API

### ISSUE THREAD

**Issue by zephyrbot** [zephyrproject-rtos/zephyr#4040]
**_Reported by Piotr Mienkowski:_**

I2C API should be updated to fix all linked issues.

- [x] #2956: I2C Slave Driver (PR #5224)
- [x] #4039: Update I2C API to support arbitrary bus speed values
- [x] #4009: I2C API is mixing two incompatible definitions of bit-fields
- [x] #3806: I2C: move "Use 10-bit addressing" option to i2c_msg (PR #9334)
- [x] #2001: Add support in I2C shim driver for DMA transfer mode
- [x] #8684: unable to perform more than one write transfer like i2c_burst_write
- [x] #9920: I2C slave DTS support (PR #9943)
- [x] #11612: i2c_burst_write on nrf51 is not a burst write 
- [ ] #12277: i2c should define fine-grained error responses
- [x] #26760: i2c: complete support for 10-bit addressing
- [ ] #27675: i2c: complete and stabilize support for "slave" I2C devices
- [ ] #27715: i2c: consistent support for bus timeouts and recovery

(Imported from Jira ZEP-2612)

**Comment by nashif** [comment]
@MaureenHelm  to submit a proposal for #4039 and get comments in a PR

**Comment by endian-benjamin** [comment]
What's the status on async I2C? Asking because of #1387 mainly

**Comment by mnkp** [comment]
There are a few more changes to the I2C API which might be considered
- Despite the fact that PR #9334 moved 10-bit addressing flag to `struct i2c_msg` - this allows to use 10-bit addressing on a per message basis - the only function that takes `struct i2c_msg` as a parameter is `i2c_transfer`. No other function e.g. `i2c_write`, `i2c_reg_read_byte` allows to use 10-bit addressing. As such 10-bit addressing is not really supported by the API.
- while most of the functions follow the pattern `int i2c_write_read(struct device *dev, uint16_t addr,` where the second parameter is the device address on the i2c bus the `i2c_write`, `i2c_read` functions take it as the last parameter. This is quite confusing when reading the application code.

**Comment by pabigot** [comment]
API 2020-07-07: Moved from triage to in-progress, as there has been recent activity.

**Comment by carlescufi** [comment]
@teburd assigned to you as per @nashif

**Comment by nashif** [comment]
closing, the remaining issues have their own entries, so no need to keep this open
