### ISSUE TITLE
LE Audio: CAP Commander Implementation

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41714]
**Is your feature request related to a problem? Please describe.**
Implement the CAP Commander role (https://www.bluetooth.com/specifications/specs/common-audio-profile/)

```[tasklist]
### Tasks
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/64358
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/64359
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/64361
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/47313
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/47314
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/64363
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/66183
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/66164
- [ ] https://github.com/zephyrproject-rtos/zephyr/issues/66165
```
