### ISSUE TITLE
Zephyr SDK 0.15.0 Checklist

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#46491]
### Milestone completion
https://github.com/zephyrproject-rtos/sdk-ng/milestone/12

### After RC1 (two weeks before release)

- [x] Release CI Docker image containing RC1
- [x] Announce RC1 open beta
- [x] Announce pending minimum required Zephyr SDK version change to 0.15.0
- [x] https://github.com/zephyrproject-rtos/sdk-ng/issues/527
- [x] https://github.com/zephyrproject-rtos/sdk-ng/issues/528
- [x] Fix any GCC 12.1 incompatibilities (warnings, ABI changes)
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49495
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46604
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46606
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46607
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46617
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46671
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48455
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48456
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48457
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48458
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48483
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48522
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48661
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48686
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48727
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48710
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48729
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48814
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48831
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48838
    - [x] https://github.com/zephyrproject-rtos/zephyr/issues/48829 (issue, to be fixed via PR 48889)
    - [x] https://github.com/zephyrproject-rtos/zephyr/issues/44466 (issue, to be fixed via PR 48889)
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48889
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49062
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49449
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49468

### After release

- [x] #49195
    - https://github.com/zephyrproject-rtos/zephyr/pull/49496
- [x] Set minimum required Zephyr SDK version to 0.15.0
- [x] Ensure that the `latest` [docker-image](https://github.com/zephyrproject-rtos/docker-image) tag contains Zephyr SDK 0.15.0
- [x] Update [Zephyr SDK Version Compatibility Matrix](https://github.com/zephyrproject-rtos/sdk-ng/wiki/Zephyr-SDK-Version-Compatibility-Matrix)
- [x] ~#46609~ (discarded)
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/46461
- [x] Fix any GCC 12.1 incompatibilities that require that cannot be fixed in a backward-compatible way
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46484
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48521
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/48526
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49058
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49459
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49704
    - [x] https://github.com/zephyrproject-rtos/zephyr/pull/49702
- [x] Redirect sdk-ng CI to track the Zephyr `main` branch instead of the `topic-sdk15` branch
- [x] https://github.com/zephyrproject-rtos/zephyr/issues/47329
- [x] Re-enable any tests that were broken with previous Zephyr SDK versions (grep `FIXME`)

### Known Issues with Zephyr SDK 0.15.0

* https://github.com/zephyrproject-rtos/zephyr/issues/49213
* https://github.com/zephyrproject-rtos/zephyr/issues/49036
* https://github.com/zephyrproject-rtos/zephyr/issues/48992
* https://github.com/zephyrproject-rtos/zephyr/issues/49491
* https://github.com/zephyrproject-rtos/zephyr/issues/49492
* https://github.com/zephyrproject-rtos/zephyr/issues/49494
