### ISSUE TITLE
Removal of logging v1

### ISSUE THREAD

**Issue by nordic-krch** [zephyrproject-rtos/zephyr#46500]
Logging v1 has been deprecated in v3.0 with notification that it will removed after v3.1.
The plan is to do it partially. This issue will track the progress.

- [x] Removal of support for v1 from in tree logging backends #46499
- [x] Removing v1 from tests #46503 
- [x] Removing v1 references from samples #46509
- [x] Removing v1 references from the documentation #46520
- [x] Removing v1 support from the core #46564
- [ ] Renaming any references to v2 (e.g. log_msg2) #46727
- [x] Rename files log_msg2 to log_msg. #46724
- [x] Removing all `log_strdup` calls #46680

**Comment by aasthagr** [comment]
@nordic-krch Seems like there are still references to Z_LOG_MSG2_CREATE* , LOG_MSG2_DEBUG, LOG_MSG2_GENERIC_HDR macros in the tree.

**Comment by nordic-krch** [comment]
@aasthagr thanks for that info, if i find something like that i will be posting small patches.
