### ISSUE TITLE
Migration and road map from the deprecated testing API to the new ZTEST API.

### ISSUE THREAD

**Issue by aaronemassey** [zephyrproject-rtos/zephyr#47002]
# Migration and road map from deprecated testing API to the current API.

## Some example API migrations

* [Bluetooth AT](https://github.com/zephyrproject-rtos/zephyr/pull/44761)
* [CMSIS DSP](https://github.com/zephyrproject-rtos/zephyr/pull/44855)
* [Condition Variables](https://github.com/zephyrproject-rtos/zephyr/pull/46662)
* [Posix](https://github.com/zephyrproject-rtos/zephyr/pull/46809)

## Migration status

The list below was initially generated by finding tests without a `ZTEST_SUITE`
macro usage and roughly categorizing them with respect to their directories and
tested features. For example, `tests/application_development` and
`tests/arch/arm` contain unmigrated tests.

- [x] application_development
   - [x] code_relocation [@hakehuang ] 
   - [x] gen_inc_file [@enjiamai ]
- [x] arch/arm [@shaoanxli ]    (12/12)
- [x] arch/arm64 [@carlocaione]  (3/3)
- [x] arch/x86 + others [@enjiamai, @edersondisouza ]   (3/3)
- [x] benchmarks (@enjiamai )
- [ ] bluetooth 
   - [ ] @kruithofa for `controller/ctrl_`
   - [x] @ppryga for `connection{less}_*`
   - [x] @carlescufi for the rest
- [x] boards (5/5)
   - [x] boards/altera_max10 (@enjiamai )
   - [x] boards/espressif_esp32 (@enjiamai )
   - [x] boards/intel_adsp (@enjiamai )
   - [x] boards/mec15xxevb_assy6853 (@enjiamai )
   - [x] boards/native_posix (@enjiamai )
   - [x] boot/uefi (This is not using ztest, skip)
- [ ] cmake/config_dir
- [x] crypto (@enjiamai )
- [ ] drivers [   ] (37/39)
   - [x] adc (@hakehuang )
   - [x] drivers/bbram  (@mengxianglinx)
   - [x] drivers/can  (@henrikbrixandersen )
   - [x] drivers/clock_control   (#mengxianglinx )
   - [x] drivers/counter (@enjiamai )
   - [x] drivers/dac (@enjiamai )
   - [x] dma (@hakehuang )
   - [x] drivers/disk (@enjiamai )
   - [x] eeprom (@henrikbrixandersen )
   - [x] drivers/entropy (@enjiamai ) 
   - [x] drivers/espi  (@enjiamai  )
   - [x] drivers/flash  (@enjiamai ) 
   - [x] drivers/flash_simulator (@enjiamai )
   - [x] drivers/gpio  (@enjiamai )
   - [x] drivers/hwinfo (@shaoanli )
   - [x] drivers/i2c (@enjiamai )  
   - [ ] drivers/i2s/i2s_api  (@hunterhu3000 , #48231)
   - [x] drivers/i2s/i2s_speed  (@hunterhu3000 , #48239)
   - [x] drivers/i2s/ipm  (This is not using ztest, should we apply it?)  
   - [x] drivers/kscan/kscan_api (@hunterhu3000 )
   - [x] drivers/led/led_api  (@enjiamai )
   - [x] drivers/memc/stm32_sdram/ (@pdgendt )  
   - [x] drivers/mipi_dsi/api/  (@enjiamai )
   - [x] drivers/pinctrl/api  (@yperess )
   - [x] drivers/pinctrl/gd32 (@enjiamai )
   - [x] drivers/pinctrl/nrf  (@enjiamai )
   - [ ] drivers/pwm/ (@enjiamai , #49511 )
   - [x] drivers/regulator/  (@enjiamai )
   - [x] drivers/sdhc  (@danieldegrasse )
   - [x] drivers/sensor/generic/ (@aaronemassey )
   - [x] drivers/sensor/accel (@enjiamai )
   - [x] drivers/sensor/sbs_gauge  (@aaronemassey ) 
   - [x] drivers/spi/  (@enjiamai )
   - [x] drivers/syscon (@enjiamai )
   - [x] drivers/timer/nrf_rtc_timer  (@enjiamai )
   - [x] drivers/uart (@enjiamai )
   - [x] drivers/virtualization/ivshmem (@enjiamai )   
   - [x] drivers/w1/w1_api ( @str4t0m )
   - [x] drivers/watchdog/wdt_basic_api (@aaronemassey )
- [x] kernel ( @nashif , @smrtos, @LixinGuoX  )  (38/38)
   - [x] kernel/condvar (@nashif,)
   - [x] kernel/common  (@LixinGuoX,)
   - [x] kernel/context (@LixinGuoX)
   - [x] kernel/device  (@LixinGuoX)
   - [x] kernel/early_sleep   (#LixinGuoX )
   - [x] kernel/events  (@LixinGuoX)
   - [x] kernel/fatal   (@LixinGuoX)
   - [x] kernel/fifo (@LixinGuoX)
   - [x] kernel/fpu_sharing   (@LixinGuoX)
   - [x] kernel/gen_isr_table (@LixinGuoX)
   - [x] kernel/interrupt  (@enjiamai)
   - [x] kernel/lifo (@LixinGuoX)
   - [x] kernel/mbox (@enjiamai )
   - [x] kernel/mem_heap  (@Zhaoningx ) 
   - [x] kernel/mem_protect   (@enjiamai)
   - [x] kernel/mem_slab   (@Zhaoningx )
   - [x] kernel/mp  (@enjiamai 
   - [x] kernel/msgq (@mengxianglinx )
   - [x] kernel/mutex   (@smrtos)
   - [x] kernel/obj_tracking (@LixinGuoX)
   - [x] kernel/pending (@LixinGuoX)
   - [x] kernel/pipe   (@LixinGuoX)
   - [x] kernel/poll (@Zhaoningx )
   - [x] kernel/profiling  (@LixinGuoX)
   - [x] kernel/queue   (@Zhaoningx )
   - [x] kernel/sched   (@smrtos  )
   - [x] kernel/semaphore  (@mengxianglinx)
   - [x] kernel/sleep   (@LixinGuoX)
   - [x] kernel/smp (@LixinGuoX)
   - [x] kernel/smp_boot_delay   (@LixinGuoX)
   - [x] kernel/spinlock   (@LixinGuoX)
   - [x] kernel/stack   (@LixinGuoX)
   - [x] kernel/threads (@Zhaoningx)
   - [x] kernel/tickless   (@LixinGuoX)
   - [x] kernel/timer (@enjiamai )   
   - [x] kernel/usage (@LixinGuoX)
   - [x] kernel/workq  (@Zhaoningx  )
   - [x] kernel/xip @LixinGuoX
- [x] lib [@yerabolu, @1xlibiao ]    (28/29, 97%)
   - [x] lib/cmsis_dsp/filtering[@enjiamai ]
   - [x] lib/cmsis_dsp/interpolation[@enjiamai ] 
   - [x] lib/cmsis_dsp/matrix[@enjiamai ]
   - [x] lib/cmsis_dsp/quaternionmath (@1xlibiao)
   - [x] lib/cmsis_dsp/statistics[@enjiamai ]   
   - [x] lib/cmsis_dsp/support[@enjiamai ]  
   - [x] lib/cmsis_dsp/svm (@1xlibiao )
   - [x] lib/cmsis_dsp/transform[@enjiamai ]
   - [x] lib/devicetree (@1xlibiao)
   - [x] lib/fdtable (@1xlibiao)
   - [x] lib/gui/lvgl   (@1xlibiao)
   - [x] lib/heap (@1xlibiao)
   - [x] lib/heap_align (@1xlibiao)
   - [x] lib/json    (@1xlibiao)
   - [x] lib/cmsis_nn   (@yerabolu)
   - [ ] lib/mem_alloc (#yerabolu , #50164 )
   - [x] lib/mem_blocks (@yerabolu)
   - [x] lib/mpsc_pbuf  (@yerabolu)
   - [x] lib/newlib/heap_listener   (@yerabolu )
   - [x] lib/newlib/thread_safety (@yerabolu )   
   - [x] lib/notify  (@yerabolu)
   - [x] lib/onoff   (@yerabolu)
   - [x] lib/p4workq (@yerabolu)
   - [x] lib/ringbuffer (@1xlibiao  )
   - [x] lib/smf  (@1xlibiao )
   - [x] lib/sprintf (@yerabolu)
   - [x] lib/spsc_pbu (@nordic-krch )  
   - [x] lib/sys_util   (@yerabolu ) 
   - [x] lib/time (@yerabolu)
- [x] misc [@chen-png ]  (2/2)
- [ ] net [@hunterhu3000, @xiaos2x ]  ( 66/73, 90%)
   - [x] net/6lo  (@xiaos2x)
   - [x] net/all  (@xiaos2x)
   - [x] net/arp    (@xiaos2x)
   - [x] net/bridge  (@xiaos2x)
   - [x] net/buf  (@xiaos2x)
   - [x] net/checksum_offload (@xiaos2x)
   - [x] net/context (@hunterhu3000 )
   - [x] net/dhcpv4  (@xiaos2x)
   - [x] net/ethernet_mgmt (@hunterhu3000 )
   - [x] net/hostname   (@xiaos2x)
   - [x] net/udp  (@xiaos2x)
   - [ ] net/icmpv4 (@hunterhu3000 , #49381 )
   - [x] net/icmpv6  (@xiaos2x)
   - [x] net/ieee802154/custom_l2   (@xiaos2x)
   - [x] net/ieee802154/fragment (@xiaos2x)
   - [x] net/ieee802154/l2 (@xiaos2x)
   - [x] net/iface (@hunterhu3000 )
   - [x] net/igmp (@hunterhu3000 )
   - [x] net/ip-addr (@xiaos2x)
   - [x] net/ipv6 (@hunterhu3000 )
   - [x] net/ipv6_fragment (@xiaos2x)
   - [x] net/lib/coap   (@xiaos2x)
   - [x] net/lib/dns_addremove   (@xiaos2x )
   - [x] net/lib/dns_packet   (@xiaos2x)
   - [x] net/lib/dns_resolve  (@xiaos2x)
   - [x] net/lib/dns_sd (@xiaos2x)
   - [x] net/lib/http_header_fields (@xiaos2x)
   - [x] net/lib/lwm2m/content_json (@hunterhu3000 )
   - [x] net/lib/lwm2m/content_link_format (@hunterhu3000 )
   - [x] net/lib/lwm2m/content_oma_tlv (@hunterhu3000 )
   - [x] net/lib/lwm2m/content_plain_text (@hunterhu3000 )
   - [x] net/lib/lwm2m/content_raw_cbor (@hunterhu3000 )
   - [ ] net/lib/lwm2m/content_senml_cbor  (@hunterhu3000 , #49895 )
   - [x] net/lib/mqtt_packet  (@xiaos2x)
   - [x] net/lib/mqtt_publisher (@hunterhu3000 )
   - [x] net/lib/mqtt_pubsub (@hunterhu3000 )
   - [x] net/lib/mqtt_subscriber (@hunterhu3000 )
   - [x] net/lib/tls_credentials (@hunterhu3000 )
   - [x] net/mgmt (@hunterhu3000)
   - [x] net/mld  (@hunterhu3000)
   - [x] net/neighbor   (@hunterhu3000)
   - [x] net/net_pkt (@hunterhu3000)
   - [x] net/npf  (@hunterhu3000)
   - [x] net/pm   (@hunterhu3000)
   - [x] net/ppp  (@hunterhu3000)
   - [x] net/promiscuous   (@hunterhu3000)
   - [x] net/ptp  (@hunterhu3000)
   - [x] net/route   (@hunterhu3000)
   - [x] net/route_mcast/  (@hunterhu3000)
   - [x] net/shell   (@hunterhu3000)
   - [x] net/socket/af_packet (@hunterhu3000)
   - [x] net/socket/af_packet_ipproto_raw (@hunterhu3000) suffle fail, cannot run twice
   - [x] net/socket/getaddrinfo  (@hunterhu3000) suffle fail, cannot run twice
   - [x] net/socket/getnameinfo  (@hunterhu3000)
   - [x] net/socket/misc   (@hunterhu3000)
   - [x] net/socket/net_mgmt  (@hunterhu3000) unable to suffle
   - [x] net/socket/offload_dispatcher (@hunterhu3000 )
   - [x] net/socket/poll   (@hunterhu3000) suffle fail, cannot run twice
   - [x] net/socket/register  (@hunterhu3000) unable to suffle
   - [x] net/socket/select (@hunterhu3000)
   - [x] net/socket/socketpair   (@hunterhu3000 )
   - [x] net/socket/tcp (@hunterhu3000 )
   - [x] net/socket/tls (@hunterhu3000 )
   - [ ] net/socket/tls_ext   (@hunterhu3000, #48212)
   - [x] net/socket/udp (@hunterhu3000 )
   - [ ] net/socket/websocket (@hunterhu3000, #48224)
   - [x] net/tcp  (@hunterhu3000 , #49498 )
   - [x] net/traffic_class (@hunterhu3000 )
   - [ ] net/trickle/   (@hunterhu3000, #48226)
   - [ ] net/tx_timestamp  (@hunterhu3000, #48227)
   - [ ] net/utils   (@hunterhu3000, #48228)
   - [x] net/virtual (@hunterhu3000 )
   - [x] net/vlan (@hunterhu3000) suffle fail, cannot run twice
- [x] subsys [ ] ( 38/38 , 100%)
   - [x] subsys/logging/log_msg (@1xlibiao )
   - [x] subsys/logging/log_immediate (@1xlibiao )
   - [x] subsys/logging/log_backend_init (@1xlibiao )
   - [x] subsys/logging/log_switch_format (@1xlibiao )
   - [x] subsys/logging/log_benchmark (@shaoanxli )
   - [x] subsys/logging/log_backend_fs (@shaoanxli )
   - [x] subsys/logging/log_core_additional (@shaoanxli )
   - [x] subsys/logging/log_api (@yperess )
   - [x] subsys/logging/log_output (@nordic-krch )
   - [x] subsys/logging/log_stack (@nordic-krch )
   - [x] subsys/logging/log_stress (@nordic-krch )
   - [x] subsys/logging/log_syst (@1xlibiao )
   - [x] subsys/sd/  (@Zhaoningx)
   - [x] subsys/jwt  (@shuai1x)
   - [x] subsys/mgmt (@yinfangw )
   - [x] subsys/canbus  (@henrikbrixandersen )
   - [x] subsys/usb  (@shuai1x)
   - [x] subsys/cpp  (@shuai1x)
   - [x] subsys/edac (@yinfangw )
   - [x] subsys/pm/  (@yinfangw )
   - [x] subsys/storage (@yinfangw )
   - [x] subsys/shell   (@yinfangw) 
   - [x] subsys/modbus  (@Zhaoningx )
   - [x] subsys/ipc/ (@Zhaoningx)
   - [x] subsys/settings/fcb_init (@Kunli123 )
   - [x] subsys/settings (@mengxianglinx )
   - [x] subsys/rtio/   (@teburd)
   - [x] subsys/fs/fat_fs_api  (@shuai1x)
   - [x] subsys/fs/fat_fs_dual_drive (@shuai1x )
   - [x] subsys/fs/fs_api (#mengxianglinx )
   - [x] subsys/fs/littlefs (@Kunli123 )
   - [x] subsys/fs/multi-fs (@shuai1x )
   - [x] subsys/fs/fcb  (@yinfangw )
   - [x] subsys/fs/nvs  (@simhein )
   - [x] subsys/portability/  (#shuai1x )
   - [x] subsys/dfu  (@shuai1x)
   - [x] subsys/tracing (@mengxianglinx )
   - [x] subsys/debug   (@yinfangw) 
- [x] unit
   - [x] list (@Zhaoningx )
   - [x] rbtree (@Zhaoningx )
   - [x] util (@enjiamai )
   - [x] others (@enjiamai )
- [x] ztest 

## Simple migration workflow

This does not cover all migration cases nor the entirety of the ZTEST API. This
is just a simple workflow get started on simple tests.

* Replace `ztest_test_suite()` and its containing function with a
   `ZTEST_SUITE()` [defined here with documented
   parameters](https://github.com/zephyrproject-rtos/zephyr/blob/2ddf2fa8b86810179fe8386919007dd07a3ae51c/subsys/testsuite/ztest/include/zephyr/ztest_test_new.h#L114).
* Replace prior test functions invoking `zassert` with `ZTEST` or `ZTEST_USER`.
* Add `CONFIG_ZTEST_NEW_API=y` to the test's `prj.conf`.

## Difficulty or questions

Usually, a single test's migration shouldn't require more than 10 minutes. If
you're having difficulty porting a test or understanding how to use the new
ZTEST API, then make a comment on this issue.

## Some suggestions

* Try the new CONFIG_ZTEST_SHUFFLE to check if the ported test functions are self-contained/independent.
* Keep the old CONFIG_MULTITHREADING as the old test cases.
* Do not have a “test_” prefix in the test suite name. 
* One test suite per commit. One PR to hold all related commits.

**Comment by nashif** [comment]
for all of those working on this, do not have a test_ prefix in the testsuite name. This is just confusing and redundant.

**Comment by hakehuang** [comment]
@aaronemassey , I have a problem here, there used to be some test fucntions are registerred as shall command see below code
```
extern void test_dma_m2m_chan0_burst8(void);
extern void test_dma_m2m_chan1_burst8(void);
extern void test_dma_m2m_chan0_burst16(void);
extern void test_dma_m2m_chan1_burst16(void);

#ifdef CONFIG_SHELL
TC_CMD_DEFINE(test_dma_m2m_chan0_burst8)
TC_CMD_DEFINE(test_dma_m2m_chan1_burst8)
TC_CMD_DEFINE(test_dma_m2m_chan0_burst16)
TC_CMD_DEFINE(test_dma_m2m_chan1_burst16)

SHELL_CMD_REGISTER(test_dma_m2m_chan0_burst8, NULL, NULL,
			TC_CMD_ITEM(test_dma_m2m_chan0_burst8));
SHELL_CMD_REGISTER(test_dma_m2m_chan1_burst8, NULL, NULL,
			TC_CMD_ITEM(test_dma_m2m_chan1_burst8));
SHELL_CMD_REGISTER(test_dma_m2m_chan0_burst16, NULL, NULL,
			TC_CMD_ITEM(test_dma_m2m_chan0_burst16));
SHELL_CMD_REGISTER(test_dma_m2m_chan1_burst16, NULL, NULL,
			TC_CMD_ITEM(test_dma_m2m_chan1_burst16));
#endif
```

shall we create a marco for ZTEST_SH which looks like below
```
#define Z_TEST_WITH_SH(suite, fn, t_options, use_fixture)                                                  \
	static void _##suite##_##fn##_wrapper(void *data);                                         \
	static void suite##_##fn(                                                                  \
		COND_CODE_1(use_fixture, (struct suite##_fixture *fixture), (void)));              \
	static STRUCT_SECTION_ITERABLE(ztest_unit_test, z_ztest_unit_test_##suite##_##fn) = {      \
		.test_suite_name = STRINGIFY(suite),                                               \
		.name = STRINGIFY(fn),                                                             \
		.test = (_##suite##_##fn##_wrapper),                                               \
		.thread_options = t_options,                                                       \
	};                                                                                         \
	static void _##suite##_##fn##_wrapper(void *data)                                          \
	{                                                                                          \
		COND_CODE_1(use_fixture, (suite##_##fn((struct suite##_fixture *)data);),          \
			    (ARG_UNUSED(data); suite##_##fn();))                                   \
	}                                                                                          \
       TC_CMD_DEFINE(suite##_##fn)                                                           \
       SHELL_CMD_REGISTER(suite##_##fn, NULL, NULL, TC_CMD_ITEM(suite##_##fn));  \
	static inline void suite##_##fn(                                                           \
		COND_CODE_1(use_fixture, (struct suite##_fixture *fixture), (void)))

```

**Comment by aaronemassey** [comment]
@hakehuang 

> @aaronemassey , I have a problem here, there used to be some test fucntions are registerred as shall command see below code

Looking at this still, but I'm a bit confused as to actually how the SHELL_COMMAND_REGISTER macro is actually being leveraged in this test. It looks like the test is simply running the test functions themselves without respect to the shell command macro. Maybe we can discuss this at the next working group meeting (tomorrow).

**Comment by simhein** [comment]
@aaronemassey subsys/fs is wrong checked in the issue.  See: https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/subsys/fs. I started working on it can you add my name to the "task"?

**Comment by JordanYates** [comment]
I feel like this can be closed with the deprecation of the old API in v3.4

**Comment by shuai1x** [comment]
47002

在 2023-07-07 19:48:13，"Jordan Yates" ***@***.***> 写道：


Closed #47002 as completed.
