### ISSUE TITLE
mcumgr zephyr 3.2 release checklist

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#49950]
PRs needed for upcoming zephyr 3.2 release:
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49455
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49516
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49517
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49691
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49801
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49909
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49838
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49925
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49873
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49835
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49528
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49527
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/47935

Optional/nice to have PRs for upcoming zephyr 3.2 release:
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/49865
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/47322
