### ISSUE TITLE
Zephyr 3.2 release notes overview

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#50423]
Umbrella issue for tracking release notes updates for the various drivers and subsystems, if you own one of these feel free to mark as done, link PRs, add notes, expand or just drop a comment. Adding few placeholders in https://github.com/zephyrproject-rtos/zephyr/pull/50418 for these, will clear the empty one before the final release.

- [ ] Overview (everyone)
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46746
  - [ ] mention sysbuild and blobs (@fabiobaltieri)
- [ ] Known Issues (@fabiobaltieri)
  - [ ] Mention https://github.com/zephyrproject-rtos/zephyr/issues/50665
- [ ] Kernel (@andyross)
- [ ] Architectures
  - [ ] ARC (@ruuddw)
  - [x] ARM (@microbuilder, #50504)
  - [x] ARM64 (@carlocaione, #50431)
  - [ ] Posix (@aescolar)
  - [x] RISC-V (@kgugala @pgielda @tgorochowik @fkokosinski)
  - [ ] x64 (@jhedberg)
  - [x] Xtensa (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
- [x] Bluetooth (@jhedberg @cvinayak @PavelVPV @Thalley @asbjornsabo)
- [x] Boards & SoC Support (@fabiobaltieri)
- [ ] Drivers and Sensors
  - [x] ADC (@anangl)
  - [x] CAN (@henrikbrixandersen, #50338)
  - [x] Clock Control (@nordic-krch)
  - [ ] Coredump (@mrkhldn)
  - [x] Counter (@nordic-krch)
  - [x] Crypto (@ceolin)
  - [x] DAC (@martinjaeger)
  - [x] DMA (@teburd)
  - [ ] DAI (@juimonen)
  - [x] Disk (@danieldegrasse ) #50443
  - [x] Display (@jfischer-no @gmarull)
  - [x] EEPROM (@henrikbrixandersen, #50350)
  - [x] Entropy (@ceolin)
  - [x] ESPI (@albertofloyd, #50509) 
  - [ ] Ethernet (@tbursztyka)
  - [x] Flash (@nvlsianpu) https://github.com/zephyrproject-rtos/zephyr/pull/50710
  - [ ] GPIO (@mnkp)
  - [ ] HWINFO (@alexanderwachter)
  - [x] I2C (@teburd)
  - [x] I2S (@anangl)
  - [x] I3C (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
  - [ ] IEEE 802.15.4 (@tbursztyka)
  - [x] Interrupt Controller (orphan, @fabiobaltieri)
  - [x] IPM (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
  - [x] LED (@Mani-Sadhasivam)
  - [x] LoRa (@Mani-Sadhasivam)
  - [x] MEMC (orphan, @fabiobaltieri)
  - [x] MM (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
  - [x] Modem (@rerickson1)
  - [x] PCIE (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
  - [x] PECI (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
  - [x] PWM (@anangl)
  - [x] Pin control (@gmarull)
  - [x] Pinmux (@gmarull)
  - [x] Power Domain (orphan, @fabiobaltieri)
  - [x] Reset (orphan, @fabiobaltieri)
  - [x] SDHC (orphan, @fabiobaltieri) #50445 
  - [ ] SPI (@tbursztyka)
  - [x] Sensor (@MaureenHelm, #50488)
  - [x] Serial (@dcpleung, https://github.com/zephyrproject-rtos/zephyr/pull/50444)
  - [ ] Timer (@andyross)
  - [x] USB (@jfischer-no)
  - [x] W1 (@str4t0m)
  - [x] Watchdog (@katsuster @martinjaeger)
  - [ ] WiFi (@tbursztyka)
- [x] Networking (@rlubos) (https://github.com/zephyrproject-rtos/zephyr/pull/50541)
  - [x] CoAP (@rlubos @pdgendt)
  - [x] Ethernet (@tbursztyka)
  - [x] HTTP (@rlubos)
  - [x] LwM2M (@rlubos)
  - [x] MQTT (@rlubos)
  - [x] OpenThread (@rlubos @pdgendt)
  - [x] Sockets (@pfalcon)
  - [x] TCP (@rlubos)
  - [ ] TLS (@d3zd3z @ceolin)
- [x] USB (@jfischer-no)
- [x] Build System (@tejlmand)
- [x] Devicetree (@mbolivar-nordic @galak): https://github.com/zephyrproject-rtos/zephyr/pull/50510
- [ ] Libraries / Subsystems
  - [ ] Console (@pfalcon)
  - [x] C Library (@stephanosio) https://github.com/zephyrproject-rtos/zephyr/pull/50527
  - [x] C++ Subsystem (@stephanosio) https://github.com/zephyrproject-rtos/zephyr/pull/50533
  - [x] CAN (@henrikbrixandersen, N/A)
  - [x] Emul (@yperess)
  - [x] Filesystem (@nvlsianpu) #50750
  - [x] IPC (@carlocaione @arnopo, #50431)
  - [x] LoRaWAN (@Mani-Sadhasivam)
  - [x] Logging (@nordic-krch)
  - [x] Management (@de-nordic)
  - [x] Modbus (@jfischer-no)
  - [x] Power management (@ceolin)
  - [x] RTIO (@teburd)
  - [x] SD Subsystem (@danieldegrasse ) #50447
  - [x] Settings (@nvlsianpu) #50739
  - [x] Shell (@jakub-uC)
  - [x] Storage (@nvlsianpu) #50743
  - [ ] Testsuite (@nashif)
  - [ ] Tracing (@nashif)
- [ ] HALs
  - [x] Atmel (@nandojve)
  - [x] Espressif (@sylvioalves @glaubermaroto @uLipe) https://github.com/zephyrproject-rtos/zephyr/pull/50702
  - [x] GigaDevice (@nandojve @gmarull)
  - [x] Nordic (@anangl)
  - [x] NXP (@dleach02)
  - [ ] Renesas (@andrzej-kaczmarek) (needs a MAINTAINERS.yml entry)
  - [x] RPi Pico (@yonsch)
  - [ ] Silabs (@yonsch @mnkp @chrta)
  - [ ] ST (@avisconti)
  - [x] STM32 (@erwango)
  - [ ] Telink (@andy-liu-telink)
  - [x] TI (@cfriedt @gmarull)
  - [ ] Wurth Elektronik (@yath-eiSmart @mah-eiSmart) (needs a MAINTAINERS.yml entry)
  - [x] Xtensa (@dcpleung)
  - [x] DFU (@nvlsianpu) #50751 
- [x] MCUboot (@d3zd3z @nvlsianpu) https://github.com/zephyrproject-rtos/zephyr/pull/50695
- [ ] Trusted Firmware A (@povergoing)
- [x] Trusted Firmware M (@microbuilder, #50505)
- [ ] Documentation (@carlescufi)
- [x] Tests and Samples (misc, @fabiobaltieri)

**Comment by fabiobaltieri** [comment]
Hi! This is for tracking release not updates for v3.2.0 (https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/releases/release-notes-3.2.rst). If you own one of these feel free to mark as done, link PRs, add notes, expand or just drop a comment.

Thanks!
