### ISSUE TITLE
Zephyr 3.3 release checklist

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#50898]
- [x] Make sure the release plan is kept up to date:
   - See https://github.com/orgs/zephyrproject-rtos/projects/13

- [x] Pre RC1 Steps
   - [x] Create v3.3.1 and v3.4.0 milestone so that features that don't make it to the release can be assigned a milestone
   - [x] Verify that all security-critical external components and external dependencies are up to date (previous: https://github.com/zephyrproject-rtos/zephyr/issues/49678)
        - mbedtls update WIP: https://github.com/zephyrproject-rtos/zephyr/pull/53899
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable (ask Security working group).
   - [x] Make sure there's no pending ["Release Blocker"](https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aissue+is%3Aopen+label%3A%22Release+Blocker%22) issues

See https://docs.zephyrproject.org/latest/project/release_process.html#tagging for tagging details, release specific filters under https://github.com/zephyrproject-rtos/zephyr/wiki/Filters to find pending PRs.

--------
- [x] Release Notes WIP
  - [x] Make sure to tell everybody to use the **past tense** (i.e. "X has been added" or "X is now Y")
  - [x] Create draft `doc/releases/release-notes-3.3.rst` with feature summary from the previous one (if not there already)
  - [x] Update `doc/releases/release-notes-3.3.rst` detailed sections (relative to 3.2.0 release) as important issues are addressed (subsystem owners). (https://github.com/zephyrproject-rtos/zephyr/issues/54495)
--------
- [x] Finalize Release Notes: (https://github.com/zephyrproject-rtos/zephyr/pull/54904)
  - [x] Add list of addressed issues (spell check issue list and fix in GitHub as needed) using `scripts/release/list_issues.py`
  - [x] Add list of known issues (spell check issue list and fix in GitHub as needed) by downloading the [latest bug pickle](https://github.com/zephyrproject-rtos/zephyr/actions/workflows/bug_snapshot.yaml) and using `scripts/dump_bugs_pickle.py`
  - [x] Review `doc/releases/release-notes-3.3.rst` overview summary and details sections
    - [x] Request summary details from subsystem maintainers
- [x] Update `doc/develop/api/overview.rst` https://github.com/zephyrproject-rtos/zephyr/pull/50604
- [x] Update `doc/conf.py` (add version to relevant list in `html_context`)
- [x] Update `doc/LICENSING.rst` for new components that do not have a license
--------
- [x]  Remaining Release Notes (https://github.com/zephyrproject-rtos/zephyr/issues/54495)
- [x] Check the CI [bi-weekly](https://github.com/zephyrproject-rtos/zephyr/actions/workflows/twister.yaml?query=event%3Aschedule) run for build failures that should be fixed
--------
- [x] Update version in VERSION ([EXTRAVERSION must be empty, not zero 0](https://docs.zephyrproject.org/latest/project/release_process.html#tagging)) https://github.com/zephyrproject-rtos/zephyr/pull/54950
- [x] Tag both v3.3.0 and zephyr-v3.3.0 (see https://docs.zephyrproject.org/latest/project/release_process.html#tagging)
- [x] Update and publish the [draft GitHub release](https://github.com/zephyrproject-rtos/zephyr/releases) created by the CI.
- [x] Tag v3.3.0 in [example-application](https://github.com/zephyrproject-rtos/example-application) https://github.com/zephyrproject-rtos/example-application/pull/31
--------
- [ ] After Release
  - [x] Update patchlevel in VERSION (PATCHLEVEL = 99) https://github.com/zephyrproject-rtos/zephyr/pull/54956
  - [x] Create `v3.3-branch` branch for 3.3.x releases (from v3.3.0 tag, don't include the switch to patchlevel 99)
  - [x] Create `backport v3.3-branch` label
  - [x] Move all PRs/Issues in the v3.3.0 milestone to the next milestone
  - [x] Close v3.3.0 milestone 
  - [x] Update [current release](https://www.zephyrproject.org/developer-resources/#current-release) and GitHub stats on the website (email Brett)
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release and announce the opening of the merge window
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [ ] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Store the number of currently open PRs to keep track of post-release PR overhead over time: 545 open at the time of release
  - [x] Update MAINTAINERS.yml "Release Notes" maintainers to point at the next release owners
  - [x] Update current and supported version information in the [Security Policy](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/SECURITY.md).

Previous checklist: https://github.com/zephyrproject-rtos/zephyr/issues/46287
