### ISSUE TITLE
POSIX Roadmap for LTSv3

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#51211]
## Introduction

POSIX libraries and applications should Just Work™️ in 90% of the cases when being ported to Zephyr. Why? Because we want to _enable_ our users to launch products and applications to the best of our ability, and we want to _lower the barrier to entry_ by enabling users to leverage portable APIs.

This is an umbrella issue that will outlines work to be done in the POSIX API prior to LTSv3 (Ideally complete by v3.5). 

### Problem description

As discussed at [EOSS 2023](https://eoss2023.sched.com/event/1LcPq/posix-roadmap-for-ltsv3-chris-friedt-meta) and [EOSS 2024](https://eoss24.sched.com/event/1aBF3/ltsv3-posix-roadmap-update-chris-friedt-tenstorrent), Zephyr's POSIX API layer needs some improvements. These can be broken down into the following:

1. **Maintainability**
2. Application / libc / toolchain **Interface**
3. Application / library **Portability**

### Proposed change

Implement all Option Requirements of POSIX [Subprofiling Option Groups](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_subprofiles.html) required for [PSE51](https://docs.zephyrproject.org/latest/services/portability/posix/aep/index.html#minimal-realtime-system-profile-pse51), [PSE52](https://docs.zephyrproject.org/latest/services/portability/posix/aep/index.html#minimal-realtime-system-profile-pse52), and most of [PSE53](https://docs.zephyrproject.org/latest/services/portability/posix/aep/index.html#minimal-realtime-system-profile-pse53) compatibility.

![aep](https://github.com/zephyrproject-rtos/zephyr/assets/983494/3e53f84f-4380-4567-8876-fde7d57a130c)

Update the POSIX areas at [docs.zephyrproject.org](https://docs.zephyrproject.org/latest/). For reference, the top level page of Zephyr's POSIX documentation.

https://docs.zephyrproject.org/latest/services/portability/posix/index.html

**Maintainability** addresses the needs of the maintainer, contributors, and (to some extent) the users.

**Interface** addresses the needs of
* the user (users develop POSIX code to the _interface_, not the _implementation_) (i.e. `_POSIX_C_SOURCE`, `_XOPEN_SOURCE`)
* the C Library maintainers - via [Option Requirements](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_02) (e.g. `_POSIX_TIMERS`)
* users - we do not need to re-doc the standardized POSIX API (i.e. via doxygen). However, users should rightfully expect to be able to find links to the standards that Zephyr conforms to, as well as the conformance gaps.

**Portability** addresses the needs of the users who should (rightfully) expect that the POSIX API layer behaves according to the specification.

### Proposed change (Detailed)

**Maintainability**
- Support toolchain / libc overrides for POSIX Option Groups
  - [ ] https://github.com/zephyrproject-rtos/zephyr/pull/74184
- Abstract certain POSIX structures as integers
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/51781
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52003
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52087
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52173
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52313  
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52316
- Re-use Zephyr primitives inside of the POSIX API layer rather than dogfooding POSIX types
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/58924
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/56163
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/58856
- Remove layering violations / cyclic dependencies between `subsys/net`, `subsys/fs`, and `lib/posix`
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/24966
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/73047
  - [ ] https://github.com/zephyrproject-rtos/zephyr/pull/74096
  - [ ] https://github.com/zephyrproject-rtos/zephyr/pull/73978
- Leverage a more standardized and compatible set of POSIX headers and Kconfig options
  * PicoLibC (base on Newlib) headers already exist in Zephyr SDK
  * Must copy-in for 3rd-party toolchains / libcs that do *not* support POSIX, so that Zephyr can still provide POSIX support
  * `#include_next` is required for the above
  - [ ] Insert link to PR for pulling in PicoLibc POSIX headers
* The POSIX Architecture and POSIX Subsystem are currently at odds
  * `CONFIG_ARCH_POSIX` and `CONFIG_POSIX_API` are mutually exclusive
  * this is primarily due to conflicting symbols in the C global namespace
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/13787
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/58305
  - [x] #45100
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/67181
* Remove `CONFIG_NET_SOCKETS_POSIX_NAMES`
  * introduced prior to `CONFIG_POSIX_API` in spite of the fact that the BSD Sockets API is part of POSIX
  - [ ] TODO insert PR for removing net sockets posix names

The layering issues that exist between `subsys/net` and `lib/posix` can be described as a cyclic dependency. The issue can be resolved via mutual dependency.

I.e. Currently, we have:
```
┌───────────┐       ┌───────────┐
│           ├──────►│           │
│   POSIX   │       │   NET     │
│           │◄──────┤           │
└───────────┘       └───────────┘
```

But we need
```
          ┌───────────┐
          │           │
          │   ZVFS    │
          │           │
          └▲────────▲─┘
           │        │
           │        │
┌──────────┴┐       ├───────────┐
│           │       │           │
│   POSIX   ├───────►   NET     │
│           │       │           │
└───────────┘       └───────────┘
```
Diagrams made with https://asciiflow.com/

I think we may have settled on the name "ZVFS" in the above diagram.

**Interface**

> [!TIP]
> Check the [Current status](https://docs.zephyrproject.org/latest/services/portability/posix/option_groups/index.html) of Suprofiling Option Group support from docs to verify that the items below are up to date

- [x] Include a clear reference to the [POSIX standard](https://ieeexplore.ieee.org/servlet/opac?punumber=8277151) in Zephyr's documentation
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/64540
- Plan for formally supporting Real-Time and Embedded Profiles of [IEEE Std 1003.13-2003](https://ieeexplore.ieee.org/document/1342418) (a.k.a. [PSE52](http://get.posixcertified.ieee.org/docs/pse52-2003.html))
  - https://github.com/zephyrproject-rtos/zephyr/issues/17706
  - [Conformance Test Suites](https://www.opengroup.org/testing/testsuites/vspse52-2003.html):
    - [VSX4](https://www.opengroup.org/testing/testsuites/vsx4.htm) POSIX [IEEE 1003.1](https://ieeexplore.ieee.org/servlet/opac?punumber=4694974) (Note: test is designed for [IEEE 1003.1-2001](https://ieeexplore.ieee.org/document/974398))
    - [VSTH](https://www.opengroup.org/testing/testsuites/vsth.htm) Threads
    - [VSRT](https://www.opengroup.org/testing/testsuites/vsrt.htm) Real-Time
- With `CONFIG_POSIX_API`, Ensure POSIX headers can be included as `#include <poll.h>` rather than `#include <zephyr/posix/poll.h>`
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/51771
- **`POSIX_SINGLE_PROCESS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66866
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66861
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66862
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66863
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/56670
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59924
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66864
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/66762
- **`POSIX_SIGNALS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59925
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59927
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59928
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59929
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59931
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59932
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59933
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66923
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66924
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66925
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66928
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66929
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66930
- **`POSIX_DEVICE_IO`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66932
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66938
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66946
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66947
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66948
- **`POSIX_FD_MGMT`**
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74097
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74098
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74099
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74100
- **`POSIX_SEMAPHORES`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66955
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66956
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66957
- **`_POSIX_MESSAGE_PASSING`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66958
- **`_POSIX_PRIORITY_SCHEDULING`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66959
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66960
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66961
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66962
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66963
- **`_POSIX_READER_WRITER_LOCKS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66964
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66965
- **`_POSIX_THREAD_PRIORITY_SCHEDULING`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66966
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66967
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66968
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66969
- **`_POSIX_TIMEOUTS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66970
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66971
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/66972
- **`_XOPEN_STREAMS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66973
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66974
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66975
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66976
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66977
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66978
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/66979
- **`_POSIX_SPIN_LOCKS`** (mandatory for the base specification)
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/59911
  - [x] posix: implement `pthread_spin_destroy()`
  - [x] posix: implement `pthread_spin_init()`
  - [x] posix: implement `pthread_spin_lock()`
  - [x] posix: implement `pthread_spin_trylock()`
  - [x] posix: implement `pthread_spin_unlock()`
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59910
- **`_POSIX_THREADS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59934
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59935
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59936
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59937
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59939
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59940
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59941
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59942
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59943
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59944
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59945
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59946
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/44379
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/59773
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/44727
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/25973
- **`_POSIX_CLOCK_SELECTION`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59947
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59948
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59949
- **`_POSIX_SHARED_MEMORY_OBJECTS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59950
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59951
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59952
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59953
- **`_POSIX_CPUTIME`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59954
- **`_POSIX_TIMERS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59955
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59956
  - https://github.com/zephyrproject-rtos/zephyr/issues/40099
  - https://github.com/zephyrproject-rtos/zephyr/pull/17155
- **`_POSIX_REALTIME_SIGNALS`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74993
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74994
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74995
- **`_POSIX_SYNCHRONIZED_IO`**
  - [x] implement `fsync()`
  - [x] implement `msync()`
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74455
- **`_POSIX_THREAD_PRIO_PROTECT`**
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74456
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74457
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74458
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74459
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74460
- **`_POSIX_THREAD_SAFE_FUNCTIONS`**
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74461
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74462
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74463
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74464
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74465
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74466
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/74467
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74468
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74469
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74470
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74471
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74472
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74473
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74474
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/74475

* Address regular bugs and enhancement requests
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/25407
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/51776
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52360
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52517
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52518
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52749
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/55186
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/54996
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/58911
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/54996
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/46101
  - [x] https://github.com/zephyrproject-rtos/zephyr/pull/60081

## Alternatives

There was a previous massive PR that attempted to address a number of the goals at once (#43987), but it is impossible to review in the current state and needs to be broken down and simplified in separate individual PRs.

**Comment by carlescufi** [comment]
Architecture WG:

- @cfriedt shows a presentation with a roadmap update for POSIX support
- @nashif asks about the scope of POSIX support, which profiles will be supported?

**Comment by romkell** [comment]
- @cfriedt: when ever implementing dynamic features in the scheduler / core code (not yet defined safety scope) please consider safety where dynamic memory management and using heaps is problematic to get TÜV certification.
But I remember that we had that discussion earlier already and solved that by layering the dynamic part on top of the core code which can be passed statically OR dynamically allocated objects such as stack buffers, thread contexts etc. what so ever. I feel you are aware of that.

**Comment by cfriedt** [comment]
> * @cfriedt: when ever implementing dynamic features in the scheduler / core code (not yet defined safety scope) please consider safety where dynamic memory management and using heaps is problematic to get TÜV certification.
Absolutely

>   But I remember that we had that discussion earlier already and solved that by layering the dynamic part on top of the core code which can be passed statically OR dynamically allocated objects such as stack buffers, thread contexts etc. what so ever. I feel you are aware of that.

Yeah, so the suggested approach from an earlier PR was to keep thread stack allocation separate and selectable, so that will still be the case. However, the proposed kernel-level API will also allow
* a static, pre-allocated pool of thread stacks to be used
* dynamic, heap-allocated thread stacks to be used
* both of the above (with a configurable preference)
* and of course neither

**Comment by romkell** [comment]
> Yeah, so the suggested approach from an earlier PR was to keep thread stack allocation separate and selectable, so that will still be the case. However, the proposed kernel-level API will also allow
    - a static, pre-allocated pool of thread stacks to be used
    - dynamic, heap-allocated thread stacks to be used
    - both of the above (with a configurable preference)
    - and of course neither

Like it!

**Comment by cfriedt** [comment]
Would be kind of nice to be able to use `socketpair()` without networking. I wonder if something can be borrowed from `eventfd`.. 🤔

**Comment by abrodkin** [comment]
@cfriedt speaking of POSIX PSE profile test-suites (in the original issue description above), it might be a bit more correct to refer to "embedded versions" of those, such as:
* [VSX4-PSE](https://www.opengroup.org/testing/testsuites/vsx4pse.htm) - Embedded core POSIX system interfaces tests
* [VSPH-PSE](https://www.opengroup.org/testing/testsuites/vsthpse.htm) - Embedded threads tests
* [VSRT-PSE](https://www.opengroup.org/testing/testsuites/vsrtpse.htm) - Embedded realtime tests

**Comment by cfriedt** [comment]
> ## Introduction
> 
> This is an umbrella issue that will outline planned work to be done in the POSIX subsystem prior to LTSv3 (Ideally complete by v3.4). 
> 
> Note: a full list of issues to be considered in the roadmap is [here](https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aissue+is%3Aopen+label%3A%22Area%3A+POSIX%22+-label%3A%22RFC%22).
> 
> ### Problem description
> 
> There was a lapse in maintainership of the POSIX subsystem for a period of time which slowed integration with the rest of the Zephyr codebase and addition of new POSIX features.
> 
> Currently, the most visible items on the TODO list are below.
> 
> * Plan for formally supporting Real-Time and Embedded Profiles of [IEEE Std 1003.13-2003](https://ieeexplore.ieee.org/document/1342418) (a.k.a. [PSE52](http://get.posixcertified.ieee.org/docs/pse52-2003.html))
>   * https://github.com/zephyrproject-rtos/zephyr/issues/17706
>   * [Conformance Test Suites](https://www.opengroup.org/testing/testsuites/vspse52-2003.html):
>     * [VSX4-PSE](https://www.opengroup.org/testing/testsuites/vsx4.htm) POSIX [IEEE 1003.1](https://ieeexplore.ieee.org/servlet/opac?punumber=4694974) (Note: test is designed for [IEEE 1003.1-2001](https://ieeexplore.ieee.org/document/974398))
>     * [VSTH-PSE](https://www.opengroup.org/testing/testsuites/vsth.htm) Threads
>     * [VSRT-PSE](https://www.opengroup.org/testing/testsuites/vsrt.htm) Real-Time
> * Use a more standardized and compatible set of POSIX headers
>   * https://github.com/zephyrproject-rtos/zephyr/issues/13787
>   * Touched-upon briefly [here](https://github.com/zephyrproject-rtos/zephyr/pull/51771#issuecomment-1295846694)
>   * Zephyr needs to define feature test macros. See [2.2 The Compilation Environment](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_02)
>   * We will likely be borrowing as much header detail as possible from Newlib for compatibility / maturity purposes.
>   * Potentially enable / disable POSIX feature test macros with Kconfig options
> * With `CONFIG_POSIX_API`, Ensure POSIX headers can be included as `#include <poll.h>` rather than `#include <zephyr/posix/poll.h>`
>   * #43998
> * Support automatic pthread stack and object allocation
>   * i.e. ensure that `pthread_create()` works with a `NULL` `pthread_attr_t *`
>   * #25973
> * Clean up layering issues between network and POSIX APIs
>   * Network headers currently define a number of POSIX symbols, macros, etc without proper namespacing
>   * #24966
> * The POSIX Architecture and POSIX Subsystem are currently at odds
>   * `CONFIG_ARCH_POSIX` and `CONFIG_POSIX_API` are mutually exclusive
>   * this is primarily due to conflicting symbols in the C global namespace
>   * ideally, we would also like to be able to test Zephyr POSIX subsystem functions under `native_posix`
>   * #45100
> * Remove `CONFIG_NET_SOCKETS_POSIX_NAMES`
>   * this is mainly needed for testing network library code on `native_posix`
> * Support for [`sysconf()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sysconf.html)
> * Address individual enhancment issues and bugfixes
> 
> ### Proposed change
> 
> * Replace most of the Zephyr posix headers with sanitized Newlib headers
>   * Newlib's POSIX headers are quite mature and use the prescribed feature test macros already
>   * PicoLibc's POSIX headers were derived from Newlib's so there is commonality gain
>   * 3rd party toolchains and libc's often are derived from Newlib, so it's a safe bet moving forward.
>   * Provide POSIX feature test macros in Zephyr (possibly enabled / disabled via Kconfig)
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/51781
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52003
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52087
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52173
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52313  
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/52316
> * Support for `sysconf()`
>   - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/56670
> * `CONFIG_POSIX_API` include issue fixed by
>   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/51771
> * Support automatic pthread stack allocation and object creation
>   * Add support for thread stack / object allocation to Zephyr
>   * This can be configured to allocate from a system thread pool and / or from the heap
> * Clean up layering issues between network and POSIX APIs
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/54996
>   * Properly namespace Zephyr net symbols and constants (e.g. `FD_SET()`)
>   * Make the POSIX subsystem should be a thin wrapper around net counterparts
>   * Move some implementations into POSIX or common layer (e.g. `poll()`)
>   * Restructure some system calls so that there is a proper symbol in POSIX (e.g. `read()`, `write()`, `ioctl()`) that then calls a system call.
> * The POSIX Architecture and POSIX Subsystem are currently at odds
>   * Use `dlopen()` to open / link to the native libc, thus avoiding pollution of the global C namespace
>   * Properly abstract calls to the underlying "HAL" from within `native_posix` drivers and libraries
>   * Remove `posix_cheats.h` - possibly 
>   * System include path has priority over Zephyr POSIX headers (obvious, but easily illustrated via #55760)
>     * Solution: use `-nostdinc`, `-nostdinc++`, Zephyr should use its own POSIX headers, even for `native_posix`
> * Remove `CONFIG_NET_SOCKETS_POSIX_NAMES`
>   * unnecessary once Zephyr POSIX library code can be used on `native_posix`
> 
> * Address regular bugs and enhancement requests
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/25407
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/51776
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52360
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52517
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52518
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/52749
>   - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/55186
>   - [x] https://github.com/zephyrproject-rtos/zephyr/issues/54996
> 
> ## Detailed RFC
> 
> ### Proposed change (Detailed)
> 
> The layering issues that exist between networking and POSIX can be described as a cyclic dependency. The issue can be resolved via mutual dependency.
> 
> I.e. Currently, we have:
> ```
> ┌───────────┐       ┌───────────┐
> │           ├──────►│           │
> │   POSIX   │       │   NET     │
> │           │◄──────┤           │
> └───────────┘       └───────────┘
> ```
> 
> But we need
> ```
>           ┌───────────┐
>           │           │
>           │    ??     │
>           │           │
>           └▲────────▲─┘
>            │        │
>            │        │
> ┌──────────┴┐       ├───────────┐
> │           │       │           │
> │   POSIX   ├───────►   NET     │
> │           │       │           │
> └───────────┘       └───────────┘
> ```
> 
> I'm thinking the correct name for `??` would be something like `zfdio`
> 
> Diagrams made with https://asciiflow.com/
> 
> [1] That assumes we don not want `CONFIG_POSIX_API=y` to be the default. If it were the default, that allow us to use all posix headers non-prefixed again everywhere (e.g. `<fcntl.h>`, `<unistd.h>`)
> 
> ### Dependencies
> 
> - [ ] Clean up layering issues between network and POSIX APIs
> - [ ] The POSIX Architecture and POSIX Subsystem are currently at odds
> - [ ] Remove CONFIG_NET_SOCKETS_POSIX_NAMES
> 
> ### Concerns and Unresolved Questions
> 
> ## Alternatives
> 
> There was a previous massive PR that attempted to address a number of the goals at once (#43987), but it is impossible to review in the current state and needs to be broken down and simplified in separate individual PRs.
>

**Comment by abrodkin** [comment]
@cfriedt you updated names. but references are still to non-PSE pages ;)

**Comment by cfriedt** [comment]
> @cfriedt you updated names. but references are still to non-PSE pages ;)

Actually, all three are referenced from "Conformance Test Suites" already. I was just trying to provide a reference to the higher scope specifications as well.

In any case, the information is available.

**Comment by cfriedt** [comment]
**TSC Attention Required**

Please refer to 

[POSIX System Interfaces](https://docs.zephyrproject.org/latest/services/portability/posix/conformance/index.html#posix-system-interfaces-required)
[POSIX Application Environment Profiles](https://docs.zephyrproject.org/latest/services/portability/posix/aep/index.html)

**Why should the PRs below be considered for approval?**

* A number of members of the Zephyr project (especially those in automotive, other safety-centric areas), depend on POSIX for product development for the next several years.
* Many features were part of the release plan.
* Not *all* features were finished on time, but a *huge* amount were, and some had approvals but did not get merged in time
* Better to not leave architecturally important PRs on the table

**What are the PR's we are asking to merge?**

Allow toolchains / platforms to override POSIX Option Groups via Kconfig (mainly for maintainers, libc compatibility)
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/74184

Add stubs for the `POSIX_SIGNALS` Option Group (we do not yet have processes in Zephyr, so complete to the best of our ability, mainly just adding stubs)
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/74436

Implement `POSIX_DEVICE_IO` Option Group (depended on mmap, so a bit delayed. lays groundwork for zvfs, extremely useful in terms of reducing api-layer dependency cycles)
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/73978

Implement `POSIX_FD_MGMT` Option Group (`zvfs_poll()`, `zvfs_select()`, extremely useful in terms of reducing api-layer dependency cycles)
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/73978

**What are we leaving behind?**

**System Interfaces (Base Definitions)**
* `_POSIX_REALTIME_SIGNALS` (i.e. signalling individual threads)
  * very, *very* close to being done, but didn't have quite enough cycles to finish by last week
  * requires kernel changes, which probably *should not be rushed*
  * RT signals are actually a relatively simple and clean interface, compared to full POSIX signals
  * Note: ISO C and full POSIX signals really should be implemented on top of kernel-level RT signals
  * `pthread_kill()` is the one function in `_POSIX_THREADS` that depends on RT Signals
* `_POSIX_THREAD_SAFE_FUNCTIONS`
  * also very, *very* close to being done, but has changes requested, dependencies on posix device io, etc
  * We get by without this today, and it will be fine to get it in after LTS

**PSE51 - Minimal Realtime System Profile**
* N/A this is feature complete 🎉  (with caveats above)

**PSE52 - Realtime Controller System Profile**
* `POSIX_FILE_SYSTEM`
  * `subsys/fs` requires better `fdtable` integration (i.e. using per-file-descriptor offset, rather than per-file offset)
  * depends on device io, fd mgmt, etc
* `_POSIX_TRACE*`
  * not a lot of demand, as Zephyr already has a pretty good tracing subsystem
  * had considered implementing as stubs, but not enough cycles

**PSE53 - Dedicated Realtime System Profile**
* quite a few things relating to multi-process support (pipe, signal jump, spawn, sporadic server)
* would rather just do this properly after LTSv3

**Why did these PRs not make it in for Feature Freeze?**

* Difficulty making parallel PRs (i.e. there were dependency PRs that took some time, so PRs needed to be serialized)
* Limited developer / reviewer bandwidth. The people who are kind enough to review POSIX PRs have limited bandwidth, as do we all. Of course, more help making PRs is always appreciated.
* Some Options in particular are beyond the scope of what is supported in Zephyr, so could be stubs (e.g. mutex priorities)

**Post-release Bug-fixes and Stability-fixes (backports)**

* Optional POSIX features should be guarded by feature test macros (e.g. `#if defined(_POSIX_PRIORITY_SCHEDULING)`)
* Use correct header names (e.g. `sys/features.h` instead of `posix_features.h`
* Mitigate type definition conflicts between Newlib / Picolibc / Minimal libc
* Merge `signal.h` and `time.h` into minimal libc to reduce conflicts between Newlib / Picolibc / Minimal libc
* Do NOT blanket-define `_POSIX_THREADS` (`lib/posix/options/CMakeLists.txt`)

**Comment by cfriedt** [comment]
Updated comment to reflect that the the posix device_io, signals, and fd_mgmt features were reverted.

This puts LTSv3 in a kind of dilapidated state from the POSIX & libc perspective.
