### ISSUE TITLE
1.11 Release Checklist

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5327]
Add items as required
--------
- [x] Major enhancements:
  - [x] SMP Support: Issue #1882
  - [x] MMU/MPU Support/Userspace: Issue #2937
  - [x] FOTA Updates (LWM2M/BLE): Issue #5382
  - [x] POSIX API Layer (PSE52): Issue #1291
  - [x] Native Port: Issue #1891 
  - [x] OpenThread Support: Issue #3858

Pushed out to 1.12:
- [ ] LLVM Support: Issue #3689
- [ ] AMP support: Issue #3065
--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-1.11.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-1.11.rst details sections (relative to 1.10.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checkin resulting file scripts/sanity_chk/sanity_last_release.csv
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues
  - [x] Review doc/release-notes-1.11.rst overview summary and details sections (see Sign-off below)
  - [x] Update doc/release-notes.rst (add reference to 1.11 notes)
  - [x] Update doc/index.rst (add reference to doc/1.11.0)
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v1.11.0 (with release notes)
  - [x] Update https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update https://www.zephyrproject.org/developers/#downloads
  - [x] Update doc generation (in future should be automatic based on tag)
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] Xtensa, RISCV32, NIOS-II - @nashif, @andrewboie 
--------
- [x] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create branch for 1.11.x releases, update github protections for branch
  - [x] Create checklist for next release

**Comment by pfalcon** [comment]
Release notes should include something like: "Cleanups and consistency improvements in sensor subsystem: SENSOR_CHAN_DISTANCE is changed to use meter unit, SENSOR_CHAN_HUMIDITY in percent units (backward incompatible changes)". I can prepare specific wording when release notes will be drafted.

**Comment by carlescufi** [comment]
Next release: https://github.com/zephyrproject-rtos/zephyr/issues/6533

**Comment by MaureenHelm** [comment]
@carlescufi Why did you add the v1.12.0 milestone? Can we close this issue?

**Comment by carlescufi** [comment]
@MaureenHelm my mistake. Closing now.
