### ISSUE TITLE
Zephyr 3.3 release notes overview

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#54495]
Umbrella issue for tracking release notes updates for the various drivers and subsystems, if you own one of these feel free to mark as done, link PRs, add notes, expand or just drop a comment.

**When writing release notes, please use the past tense (e.g. "Added foo and removed bar.")**

- [x] Overview (everyone)
- [x] Known Issues (@stephanosio)
- [x] Kernel (@andyross)
- [ ] Architectures
  - [x] ARC (@ruuddw)
  - [x] ARM (@microbuilder) (in #54808)
  - [x] ARM64 (@carlocaione) (in #54481)
  - [x] Posix (@aescolar)
  - [x] RISC-V (@kgugala @pgielda @tgorochowik @fkokosinski, #54546)
  - [ ] x86 (@jhedberg)
  - [x] Xtensa (@dcpleung)
- [x] Bluetooth (@jhedberg @cvinayak @PavelVPV @Thalley @asbjornsabo)
- [x] Boards & SoC Support (@stephanosio)
- [ ] Drivers and Sensors
  - [x] ADC (@anangl)
  - [x] CAN (@henrikbrixandersen, #54502)
  - [x] Clock Control (@nordic-krch)
  - [ ] Coredump (@mrkhldn)
  - [x] Counter (@nordic-krch)
  - [ ] Crypto (@ceolin)
  - [x] DAC (@martinjaeger, #54793)
  - [x] DMA (@teburd)
  - [ ] DAI (@juimonen)
  - [x] Disk (@danieldegrasse, #54624)
  - [x] Display (@jfischer-no, #54866)
  - [x] EEPROM (@henrikbrixandersen, #54503)
  - [ ] Entropy (@ceolin)
  - [ ] ESPI (@albertofloyd) 
  - [x] Ethernet (@tbursztyka)
  - [x] Flash (@nvlsianpu)
  - [x] GPIO (@mnkp)
  - [x] HWINFO (@alexanderwachter)
  - [x] I2C (@teburd)
  - [ ] I2S (@anangl)
  - [x] I3C (@dcpleung) (in #54515)
  - [ ] IEEE 802.15.4 (@tbursztyka)
  - [x] Interrupt Controller (orphan, @stephanosio)
  - [x] IPM (@dcpleung) (in #54515)
  - [ ] LED (@Mani-Sadhasivam)
  - [ ] LoRa (@Mani-Sadhasivam)
  - [ ] MEMC (orphan, @stephanosio)
  - [x] MM (@dcpleung)
  - [ ] Modem (@rerickson1)
  - [x] PCIE (@dcpleung) (in #54515)
  - [x] PECI (@dcpleung)
  - [x] PWM (@anangl)
  - [x] Pin control (@gmarull)
  - [ ] Pinmux (@gmarull)
  - [ ] Power Domain (orphan, @stephanosio)
  - [x] Reset (orphan, @stephanosio)
  - [x] SDHC (@danieldegrasse, #54625)
  - [ ] SPI (@tbursztyka)
  - [x] Sensor (@MaureenHelm, #54722)
  - [x] Serial (@dcpleung) (in #54515)
  - [x] Timer (@andyross)
  - [x] USB (@jfischer-no #54866)
  - [x] W1 (@str4t0m)
  - [x] Watchdog (@katsuster @martinjaeger)
  - [ ] WiFi (@tbursztyka)
- [x] Networking (@rlubos, #54562)
  - [x] CoAP (@rlubos @pdgendt)
  - [x] Ethernet (@tbursztyka)
  - [x] HTTP (@rlubos)
  - [x] LwM2M (@rlubos)
  - [x] MQTT (@rlubos)
  - [x] OpenThread (@rlubos @pdgendt)
  - [x] Sockets (@pfalcon)
  - [x] TCP (@rlubos)
  - [x] TLS (@d3zd3z @ceolin)
- [x] USB (@jfischer-no, #54866)
- [x] USB-C (@sambhurst)
- [x] Build System (@tejlmand)
- [x] Devicetree (@mbolivar-nordic @galak)
- [ ] Libraries / Subsystems
  - [ ] Console (@pfalcon)
  - [x] C Library (@stephanosio, https://github.com/zephyrproject-rtos/zephyr/pull/54680)
  - [x] C++ Library (@stephanosio, https://github.com/zephyrproject-rtos/zephyr/pull/54684)
  - [x] CAN (@henrikbrixandersen, included in #54502)
  - [x] DSP (@stephanosio @yperess)
  - [ ] Emul (@yperess)
  - [x] Filesystem (@nvlsianpu)
  - [x] FPGA (@cfriedt)
  - [x] IPC (@carlocaione @arnopo) (in #54481)
  - [ ] LoRaWAN (@Mani-Sadhasivam)
  - [x] Logging (@nordic-krch)
  - [x] Management (@de-nordic)
  - [ ] Modbus (@jfischer-no)
  - [x] POSIX API (@cfriedt)
  - [ ] Power management (@ceolin)
  - [ ] RTIO (@teburd)
  - [x] SD Subsystem (@danieldegrasse, #54627)
  - [x] Settings (@nvlsianpu)
  - [x] Shell (@jakub-uC)
  - [x] Storage (@nvlsianpu)
  - [ ] Testsuite (@nashif)
  - [ ] Tracing (@nashif)
- [ ] HALs
  - [x] Atmel (@nandojve, #54728)
  - [x] Espressif (@sylvioalves @glaubermaroto @uLipe)
  - [x] GigaDevice (@nandojve, @cameled, #54644)
  - [x] Nordic (@anangl)
  - [ ] NXP (@dleach02)
  - [ ] Renesas (@andrzej-kaczmarek)
  - [ ] RPi Pico (@yonsch)
  - [ ] Silabs (@yonsch @mnkp @chrta)
  - [ ] ST (@avisconti)
  - [x] STM32 (@erwango) (#54552)
  - [ ] Telink (@andy-liu-telink)
  - [ ] TI (@vaishnavachath)
  - [ ] Wurth Elektronik (@yath-eiSmart @mah-eiSmart)
  - [x] Xtensa (@dcpleung)
  - [ ] DFU (@nvlsianpu)
- [x] MCUboot (@d3zd3z @nvlsianpu)
- [x] Trusted Firmware A (@povergoing)
- [x] Trusted Firmware M (@microbuilder) (in #54808)
- [x] Documentation (@carlescufi)
- [x] Tests and Samples (misc, @stephanosio)

p.s. Thanks to @fabiobaltieri for laying the groundwork for this in https://github.com/zephyrproject-rtos/zephyr/issues/50423

**Comment by Thalley** [comment]
Bluetooth audio is added by https://github.com/zephyrproject-rtos/zephyr/pull/54496
