### ISSUE TITLE
ARC: prepare arc Zephyr infastructure  for 64bit MDB & nSIM

### ISSUE THREAD

**Issue by evgeniy-paltsev** [zephyrproject-rtos/zephyr#55468]
Prepare arc Zephyr infastructure for usage 64bit MDB & nSIM as default

This includes:
- [x] mdb-nsim west runner
- [ ] mdb-hw west runner
- [ ] nsim west runner
- [ ] cmake nsim infrastructure
- [x] cmake mdb infrastructure 
- [x] internal CI check on simulator target
- [x] internal CI check on HW target
