### ISSUE TITLE
Driver API review/cleanup/rework

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#5697]
This issue will be used to track all driver subsystem rework/cleanups:
- [x] spi:  Issue #5797, #5839, PR #5921 
- [x] adc: PR #7691 #8857
- [x] counter/rtc: Issue #5895, #8331. PR see issue. **API complete**
- [x] display PR: #7833
- [x] watchdog: Issues #10913, #10914, #10916, #10917 **DONE**: Issue #3994, PR #1260, #7007
- [ ] i2c  Issue:  #4040 PR: #5224 (merged)
- [x] gpio Issue #10339 #10741 #15611
- [x] pinctrl: PR #5799
- [x] pinmux
- [ ] Advanced sensor API #1387, #13455 #14008
- [ ] General inconsistencies and common guidelines for APIs
- [ ] serial Issue: #1682 #8243 #11535 PRs: #8306 #8307 (@jarz-nordic). PR #10820
- [ ] dma #8974 #8928
- [ ] pwm: Issues  #6958 and #9507
- [ ] battery: Issue #2542 
- [ ] led Issue: #8946
- [ ] clock_control Issues: #11107 #12039 #14008
- [ ] console (console.h? clarify with @pfalcon)
- [x] usb

- [ ] aio
- [x] bluetooth:  internal to bt subsystem
- [x] crypto
- [x] entropy
- [x] ethernet:  internal to net subsystem
- [x] flash
- [x] i2s
- [x] ieee802154: internal to net subsystem
- [x] ipm
- [x] pci
- [ ] system timer: interface to kernel, no exported header file
- [x] sensor
- [x] interrupt_controller
   - [x] shared_irq

Notes from API meeting:

https://docs.google.com/document/d/1lv-8B5QE2m4FjBcvfqAXFIgQfW5oz6306zJ7GIZIWCk/edit?usp=sharing

**Comment by b0661** [comment]
@galak can pinctrl PR #5799 also be added  here?

**Comment by carlescufi** [comment]
@b0661 done

**Comment by Mani-Sadhasivam** [comment]
@galak @carlescufi Can we add LED API to this issue?

**Comment by carlescufi** [comment]
@Mani-Sadhasivam done, is that what you meant?

**Comment by Mani-Sadhasivam** [comment]
@carlescufi No, I mean to add LED entry to the list of API's here. I will work on extending the API further.

**Comment by Mani-Sadhasivam** [comment]
@carlescufi Moreover, issue #8946 belongs to LED API and not LED Strip.

**Comment by vaussard** [comment]
Issues related to the PWM API: #6958 and #9507

**Comment by galak** [comment]
@mbolivar to move this PR into a project.

**Comment by nvlsianpu** [comment]
@galah @carlescufi  flash driver documentation issue: [flash: should write_protection be emulated?](https://github.com/zephyrproject-rtos/zephyr/issues/15729)

**Comment by mbolivar** [comment]
> @mbolivar to move this issue into a project.

Finally got around to this: https://github.com/zephyrproject-rtos/zephyr/projects/18

Is that pretty much what people are expecting? Should we close this if so?

**Comment by andrewboie** [comment]
I think we need clarity on what is going on with the new async serial API, and the old CONFIG_UART_INTERRUPT_DRIVEN API, as seen here: https://github.com/zephyrproject-rtos/zephyr/pull/14854

**Comment by henrikbrixandersen** [comment]
@galak Does this issue still provide value or can it be closed?

**Comment by galak** [comment]
> @galak Does this issue still provide value or can it be closed?

going to close it.  We can re-open if needed.
