### ISSUE TITLE
LE Audio: BAP Broadcast Source Unit test

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#57457]
**Is your enhancement proposal related to a problem? Please describe.**
This is mainly a training exercise for @Thalley to get experience with the unit test framework(s) using a fairly simply module (the BAP Broadcast Source). 

**Describe the solution you'd like**
Implement unit tests for the BAP Broadcast Source to get at least 80% test coverage using only those tests. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

```[tasklist]
### Tasks
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62162
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62257
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62259
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62338
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62344
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62348
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62361
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62402
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62437
```
