### ISSUE TITLE
MCUmgr for zephyr 3.4 meta PR list

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#58128]
MCUmgr PRs needed for zephyr 3.4:

- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57933
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57974
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57976
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57989
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57991
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57992
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58030
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58065
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58126
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58127
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/57921
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58181
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58194
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58246
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58242
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/58290

**Comment by nashif** [comment]
looks like all those PRs are merged, should this be closed?

**Comment by nordicjm** [comment]
> looks like all those PRs are merged, should this be closed?

Was away, will close.
