### ISSUE TITLE
gosc2023: net: http: project overview

### ISSUE THREAD

**Issue by Emna-Rekik** [zephyrproject-rtos/zephyr#58901]
# High Level Milestones / Deliverables

- [x] Milestone 0: Continuous Integration
- [x] Milestone 1: HTTP 2.0 Server (prototypes in Linux)
- [ ] Milestone 2: Rest API Support
- [x] Milestone 3: CRiMe Support
- [ ] Milestone 4: JSON Support
- [ ] Milestone 5: TLS Support

## Milestone 0: Continuous Integration

- [x] https://github.com/zephyrproject-rtos/zephyr/issues/59028
- [ ] Enable Test Coverage

## Milestone 1: HTTP 2.0 Server (prototypes in Linux)

RFC 9113: https://datatracker.ietf.org/doc/html/rfc9113

- [ ] Unit tests, Test Points, Features, etc
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59567
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59681
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59684
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59685
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59686
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59688
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59689
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59690
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59670
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59691
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59693
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59694
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/59695
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59696
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/59697
  - [ ] https://github.com/zephyrproject-rtos/zephyr/issues/59698
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59699
  - [x] https://github.com/zephyrproject-rtos/zephyr/issues/59700

* Reuse Zephyr's HTTP Client Library
* Reuse Zephyr's HTTP Parser Library

## Milestone 2: Rest API Support

- [ ] show multiple REST clients using the server simultaneously
- Sample apps with >= 2 REST endpoints
  - Use a REST generator to simplify things!
  - https://github.com/OAI/OpenAPI-Specification/
  - https://github.com/cfriedt/hanoi
- Documentation about how to add custom REST endpoints

## Milestone 3: CRiMe Support

Not to be confused with the HTTP 2.0 / SPDY attack 
https://en.wikipedia.org/wiki/CRIME

- [x] gzip compression, use existing cmake + any necessary wrappers

## Milestone 4: JSON Support

- [ ] Show that it's possible to exchange data with Zephyr over HTTP (JSON is often used in REST applications)
- Use Zephyr's Existing JSON Library

## Milestone 5: TLS Support

- [ ] Security Regression Testsuite (show that we are not vulnerable to old attacks)
  - Research historically what CVEs affected Zephyr's HTTP support (via CivetWeb)
  - We don't want our new HTTP server to exhibit the same security vulnerabilities
- certificate compression / storage
- user provided certificates
- Asymmetric Encryption approach
- Symmetric Encryption approach (Mutual Authentication)
- Existing reference - samples/...

## Milestone 6: Documentation (this is not an official milestone, but it is a deliverable)
- [ ] Ensure that there is adequate publishable content including
  - user-facing instructions ("How do I customize the HTTP Server?")
  - can be bundled with Sample app, but also important to document features in general (i.e. some .rst file in doc/)
  - features, performance, ...

**Comment by cfriedt** [comment]
We might be able to assign tasks to Emna once she has made a commit. I'm not sure.

**Comment by cfriedt** [comment]
@Emna-Rekik, @rlubos - I wonder if the format of this should be more like an RFC. What do you think? It can be refined and then probably presented at the Networking Forum at some point.

**Comment by rlubos** [comment]
> It can be refined and then probably presented at the Networking Forum for feedback / discussion. IIRC, it's once a month, but I'm not sure of the next meeting.

Next Networking Forum is due on 4th of July, not sure about the attendance though given this specific date. But for sure we could put this on the agenda.

**Comment by cfriedt** [comment]
@Emna-Rekik - could you possibly cut & paste the test plan portion of this issue somewhere else? Let's try to keep this issue description as more or less a checklist of subtasks

**Comment by clamattia** [comment]
Hello Zephyr Community

We are very interested in this feature and are curious, whether there is still work in progress on this.
Is the `http server` on the roadmap/planned?

**Comment by rlubos** [comment]
@clamattia Yes, we're working on wrapping the project up and integrating it with Zephyr (hopefully for 3.7 release).

**Comment by clamattia** [comment]
> @clamattia Yes, we're working on wrapping the project up and integrating it with Zephyr (hopefully for 3.7 release).

Cool, thanks.
