### ISSUE TITLE
Zephyr 3.5 Release Checklist

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#60293]
- [x] Make sure the release plan is kept up to date:
   - See https://github.com/orgs/zephyrproject-rtos/projects/13

- [x] Pre RC1 Steps
   - [x] Create v3.6.0 milestone so that features that don't make it to the release can be assigned a milestone
   - [ ] Verify that all security-critical external components and external dependencies are up to date (previous: https://github.com/zephyrproject-rtos/zephyr/issues/49678)
   - [ ] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable (ask Security working group).
   - [x] Make sure there's no pending ["Release Blocker"](https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aissue+is%3Aopen+label%3A%22Release+Blocker%22) issues
   - [ ] Ensure that the latest Zephyr SDK contains all the changes necessary to support the new features included in, or planned for this release; if not, ping the SDK maintainer (@stephanosio) to release a new SDK version.
       - [ ] Check if any toolchain-related enhancements and bug fixes are required for any of the pull requests targeting this release. If any of these enhancements and bug fixes are not part of the latest Zephyr SDK, a new SDK version must be released.
       - [ ] Check that the Picolibc version in the latest SDK matches the Picolibc module version in `west.yml`. If they do not match, a new SDK version must be released.

See https://docs.zephyrproject.org/latest/project/release_process.html#tagging for tagging details, release specific filters under https://github.com/zephyrproject-rtos/zephyr/wiki/Filters to find pending PRs.

--------
- [x] Release Notes WIP
  - [x] Make sure to tell everybody to use the **past tense** (i.e. "X has been added" or "X is now Y")
  - [x] Create draft `doc/releases/release-notes-3.5.rst` with feature summary from the previous one (if not there already)
  - [x] Update `doc/releases/release-notes-3.5.rst` detailed sections (relative to 3.3.0 release) as important issues are addressed (subsystem owners). (previous: https://github.com/zephyrproject-rtos/zephyr/issues/54495)
--------
- [x] Finalize Release Notes: (previous: https://github.com/zephyrproject-rtos/zephyr/pull/54904)
  - [x] Add list of known issues (spell check issue list and fix in GitHub as needed) by downloading the [latest bug pickle](https://github.com/zephyrproject-rtos/zephyr/actions/workflows/bug_snapshot.yaml) and using `scripts/dump_bugs_pickle.py`
  - [x] Review `doc/releases/release-notes-3.5.rst` overview summary and details sections
    - [x] Request summary details from subsystem maintainers
- [x] Update `doc/develop/api/overview.rst` (previous: https://github.com/zephyrproject-rtos/zephyr/pull/50604)
- [x] Update `doc/conf.py` (add version to relevant list in `html_context`)
- [x] Update `doc/LICENSING.rst` for new components that do not have a license
--------
- [x]  Remaining Release Notes (previous: https://github.com/zephyrproject-rtos/zephyr/issues/54495)
- [x] Check the CI [bi-weekly](https://github.com/zephyrproject-rtos/zephyr/actions/workflows/twister.yaml?query=event%3Aschedule) run for build failures that should be fixed
--------
- [x] Update version in VERSION ([EXTRAVERSION must be empty, not zero 0](https://docs.zephyrproject.org/latest/project/release_process.html#tagging)) (previous: https://github.com/zephyrproject-rtos/zephyr/pull/54950)
- [x] Tag v3.5.0 (see https://docs.zephyrproject.org/latest/project/release_process.html#tagging)
- [x] Update and publish the [draft GitHub release](https://github.com/zephyrproject-rtos/zephyr/releases) created by the CI.
- [x] Tag v3.5.0 in [example-application](https://github.com/zephyrproject-rtos/example-application) (previous: https://github.com/zephyrproject-rtos/example-application/pull/31)
--------
- [x] After Release
  - [x] Update patchlevel in VERSION (PATCHLEVEL = 99) (previous: https://github.com/zephyrproject-rtos/zephyr/pull/54956)
  - [x] Create `v3.5-branch` branch for 3.5.x releases (from v3.5.0 tag, don't include the switch to patchlevel 99)
  - [x] Create `backport v3.5-branch` label
  - [x] Move all PRs/Issues in the v3.5.0 milestone to the next milestone
  - [x] Close v3.5.0 milestone 
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release and announce the opening of the merge window
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Update MAINTAINERS.yml "Release Notes" maintainers to point at the next release owners
  - [x] Update current and supported version information in the [Security Policy](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/SECURITY.md).

Previous checklist: https://github.com/zephyrproject-rtos/zephyr/issues/54990
