### ISSUE TITLE
LE Audio: Add helper functions for bt_audio_codec_cap and metadata

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#62292]
**Is your enhancement proposal related to a problem? Please describe.**
The `bt_audio_codec_cap` contains an array of codec capabilities and codec capabilities metadata. 

For `bt_audio_codec_cfg` we have the `bt_audio_codec_cfg_get_*` functions to retrieve codec cfg data, and we should have the same for the codec capabilities, for both the capabilities and metadata. 

**Describe the solution you'd like**
Implement helper functions to get the following fields from a LTV encoded `bt_audio_codec_cap.data`:
```c
BT_AUDIO_CODEC_LC3_FREQ
BT_AUDIO_CODEC_LC3_DURATION
BT_AUDIO_CODEC_LC3_CHAN_COUNT
BT_AUDIO_CODEC_LC3_FRAME_LEN
BT_AUDIO_CODEC_LC3_FRAME_COUNT
```

As well as the `meta` for both `codec_cfg` and `codec_cap`:
```c
BT_AUDIO_METADATA_TYPE_PREF_CONTEXT
BT_AUDIO_METADATA_TYPE_STREAM_CONTEXT
BT_AUDIO_METADATA_TYPE_PROGRAM_INFO
BT_AUDIO_METADATA_TYPE_STREAM_LANG
BT_AUDIO_METADATA_TYPE_CCID_LIST
BT_AUDIO_METADATA_TYPE_PARENTAL_RATING
BT_AUDIO_METADATA_TYPE_PROGRAM_INFO_URI
BT_AUDIO_METADATA_TYPE_AUDIO_STATE
BT_AUDIO_METADATA_TYPE_BROADCAST_IMMEDIATE
BT_AUDIO_METADATA_TYPE_EXTENDED
BT_AUDIO_METADATA_TYPE_VENDOR
```

**Describe alternatives you've considered**
N/A

**Additional context**
It may also be useful to have `_set_` functions for the above.
```[tasklist]
### Tasks
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62774
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/62712
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63040
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63147
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63155
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63161
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63170
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63203
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63223
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63321
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63400
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63427
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/63429
```
