### ISSUE TITLE
1.12 Release Checklist

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#6533]
Add items as required
--------
- [x] Major enhancements:
  - [ ] ~~LLVM Support: Issue #3689~~ (pushed to 1.13)
  - [x] AMP support: Issue #3065
  - [x] VFS support: Issue #2978
  - [ ] ~~Enhanced Logging: Issue #6186~~ (pushed to 1.13)
  - [x] Runtime config system: Issue #5149
  - [x] VFS support: Issue #2978
  - [x] Command-line meta-tool: Issue #6205 
  - [ ] ~~Out-of-tree code: #5554~~

- [x] Pre RC1 Steps
   - [x] Verify that all external components and external dependencies are up to date, for example 
      - mbedTLS
      - tinycrypt
      - FatFS
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as unexploitable.

--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-1.12.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-1.12.rst details sections (relative to 1.11.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checkin resulting file scripts/sanity_chk/sanity_last_release.csv
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues (spell check issue list and fix in GitHub as needed)
  - [x] Review doc/release-notes-1.12.rst overview summary and details sections (see Sign-off below)
  - [x] Update doc/release-notes.rst (add reference to 1.12 notes)
  - [x] Update doc/index.rst (add reference to doc/1.12.0)
  - [x] Update doc/LICENSING.rst for new components that do not have a license
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v1.12.0 (with release notes)
  - [x] Update https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update https://www.zephyrproject.org/developers/#downloads (and git checkout version example)
  - [x] Update doc generation (in future should be automatic based on tag)
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [ ] Xtensa, RISCV32, NIOS-II - @nashif, @andrewboie 
--------
- [x] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create branch for 1.12.x releases, update github protections for branch
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Update https://www.zephyrproject.org with latest stats from https://zephyr.biterg.io

**Comment by carlescufi** [comment]
Additional info: https://github.com/zephyrproject-rtos/zephyr/wiki/Release-procedure

**Comment by MaureenHelm** [comment]
Next release: #8320
