### ISSUE TITLE
Zephyr 3.7 Release Checklist

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#69408]
#### As soon as possible
- [x] Ensure there is a draft `doc/releases/release-notes-3.7.rst` and `doc/releases/migration-guide-3.7.rst` with feature summary from the previous one and if not create one #69418

#### From day one but with extra focus as we approach RC1 and after:
- [x] Check the CI [bi-weekly](https://github.com/zephyrproject-rtos/zephyr/actions/workflows/twister.yaml?query=event%3Aschedule) run for build failures that should be fixed and report or fix them.
- [x] Make sure the release plan is kept up to date:
   - See https://github.com/orgs/zephyrproject-rtos/projects/13
- [x] Ensure the [release management page](https://github.com/zephyrproject-rtos/zephyr/wiki/Release-Management) has an up-to-date schedule for the release

#### One month before RC1:
- [x] Ping west project maintainers to remind them of the RC1/freeze deadline and to consider if their modules should be updated (you may want to extract all west projects' maintainers names from the MAINTAINERS files and create an issue like https://github.com/zephyrproject-rtos/zephyr/issues/73834 )
- [x] Start giving heads up on the TSC meeting about the incoming freeze.

#### Pre RC1
   - [x] Create next release (v4.0.0) milestone so that features that don't make it to the release can be assigned a milestone
   - [x] Verify that all security-critical external components and external dependencies are up to date 
     - https://github.com/zephyrproject-rtos/zephyr/issues/73703
     - https://github.com/zephyrproject-rtos/zephyr/issues/73878
     - (previous: https://github.com/zephyrproject-rtos/zephyr/issues/49678)
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable (ask Security working group).
   - [x] Make sure there's no pending ["Release Blocker"](https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aissue+is%3Aopen+label%3A%22Release+Blocker%22) issues
   - [x] Ensure that the latest Zephyr SDK contains all the changes necessary to support the new features included in, or planned for this release; if not, ping the SDK maintainer (@stephanosio) to release a new SDK version.
       - [x] Check if any toolchain-related enhancements and bug fixes are required for any of the pull requests targeting this release. If any of these enhancements and bug fixes are not part of the latest Zephyr SDK, a new SDK version must be released.
       - [x] Check that the Picolibc version in the latest SDK matches the Picolibc module version in `west.yml`. If they do not match, a new SDK version must be released. (ping @stephanosio and @keith-packard )

See https://docs.zephyrproject.org/latest/project/release_process.html#tagging for tagging details, release specific filters under https://github.com/zephyrproject-rtos/zephyr/wiki/Filters to find pending PRs.

- [x] Release Notes and Migration Guide WIP
  - [x] Make sure to tell everybody to
    * Use the **past tense** (i.e. "X has been added" or "X is now Y")
    * Update `doc/releases/release-notes-3.7.rst` detailed sections (relative to 3.6.0 release) as important issues are addressed (subsystem owners). (previous: https://github.com/zephyrproject-rtos/zephyr/issues/54495)
  - [x] Be sure to remind maintainers to update the release notes, at the very least in the rc1, rc2 and rc3 emails. But you may need to create a GH issue to follow up.

#### After RC3, before final release

- [x] Finalize Release Notes and Migration Guide: (previous: #69404) #76047
  - [x] Review `doc/releases/release-notes-3.7.rst` overview summary and details sections
    - [x] Request summary details from subsystem maintainers
- [x] Add new version in `doc/conf.py`, `doc/releases/index.rst`, and `doc/releases/eol_releases.rst` #76047
- [x] Remove EOL version(s) in `doc/conf.py`, `doc/releases/index.rst`, and `doc/releases/eol_releases.rst`  : (#76342) .
- [x] Update `doc/LICENSING.rst` for new components that do not have a license: (previous: #69392)
- [x] Remaining Release Notes (#75933)
- [x] Update version in VERSION ([EXTRAVERSION must be empty, not zero 0](https://docs.zephyrproject.org/latest/project/release_process.html#tagging)) #76047 
- [x] Tag v3.7.0 (see https://docs.zephyrproject.org/latest/project/release_process.html#tagging)
- [x] Update and publish the [draft GitHub release](https://github.com/zephyrproject-rtos/zephyr/releases) created by the CI.
- [x] Tag v3.7.0 in [example-application](https://github.com/zephyrproject-rtos/example-application) (previous: https://github.com/zephyrproject-rtos/example-application/pull/73)

### After Release
  - [x] Update patchlevel in VERSION (PATCHLEVEL = 99) (e.g. https://github.com/zephyrproject-rtos/zephyr/pull/76334) and tag `v3.7.99`
  - [x] Create `v3.7-branch` branch for 3.7.x releases (from v3.7.0 tag, don't include the switch to patchlevel 99)
  - [x] Create `backport v3.7-branch` label
  - [x] Move all PRs/Issues in the v3.7.0 milestone to the next milestone
  - [x] Close v3.7.0 milestone 
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release and announce the opening of the merge window
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog / https://www.zephyrproject.org/announcements/)
  - [x] Post an update in https://github.com/zephyrproject-rtos/zephyr/discussions under General, have one of our administrators move it to Announcements and pin it
  - [x] Post an announcement in discord in the #general & #release channels
  - [ ] Update MAINTAINERS.yml "Release Notes" maintainers to point at the next release owners
  - [x] Update current and supported version information in the [Security Policy](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/SECURITY.md). (#76339)
  - [ ] If you're a first time release manager, you may contact Tracey (or [info@zephyrproject.org](mailto:info@zephyrproject.org)) to claim your Release Manager badge.
- [x] Create draft `doc/releases/release-notes-4.0.rst` and `doc/releases/migration-guide-4.0.rst` with feature summary from the previous one (if not there already) #76344

Previous checklist: #64247
Next checklist: #76338

**Comment by aescolar** [comment]
Closing as 3.7 has been released. Owners for 4.0 are not yet allocated, but we can handle the change in the maintainers file without keeping this checklist open.
