### ISSUE TITLE
Hardware Model - Meta issue -  Enhancements / feature request

### ISSUE THREAD

**Issue by tejlmand** [zephyrproject-rtos/zephyr#69546]
Meta Issue of Hardware Model v2 enhancement

#51831 Introduce the Hardware Model v2, which provide a foundation of the new Hardware Model.

A goal of the new Hardware Model was to make it more extensible in the future as new enhancements and feature requirements arises.
The new model has been prepared in such a way which should reduce the board misuse / misnomer found in the old hardware model.

Below follows feature requests / enhancement issues for the new Hardware Model.

- [ ] Ability to extend an existing board
- [ ] Allow building for a board's basename using Sysbuild
- [ ] Allow specifying a default SoC / cpucluster when none is specified, and a board has multiple SoCs / CPU clusters
- [ ] New alias scheme
