### ISSUE TITLE
HW Model v2: Task list for merging `collab-hwm` back to `main`

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#69575]
The following steps must be completed before merging [collab_hwm](https://github.com/zephyrproject-rtos/zephyr/tree/collab-hwm) back to `main` hwmv2:

- [x] Merge all required remaining PRs targeting collab-hwm
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69517
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69568 (needs rebase)
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69505
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69285 (needs rebase)
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69269
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69260 (address review comments)
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69194 (needs @sylvioalves to push fixes)
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69578
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69597
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69642 (@danieldegrasse)
   - [x] https://github.com/zephyrproject-rtos/zephyr/pull/69354 (must be last one merged)
- [x] Address the last open issue in https://github.com/zephyrproject-rtos/zephyr/issues/51831
   - [x] Issue with base board name overlay files now being used on boards which are variants that in hwmv1 were not applied to, causing issues and failing tests https://github.com/zephyrproject-rtos/zephyr/pull/69025#discussion_r1490902683
- [x] Adapt the porting script so that it works on OoT boards (i.e. no "legacy" folder) https://github.com/zephyrproject-rtos/zephyr/pull/69674 (@gmarull) 
- [x] Modules: merge module PRs and then update `west.yml` pointers to SHAs  (@carlescufi )
- [x] Rebase (@nordicjm)
- [x] Go over the commits, gather stats/info
- [x] Analyze squashing approaches
   - Is partial squashing actually feasible?
   - If not, should we squash to a single commit?
- [x] Remove any outstanding local changes that do not apply to `main`:
   - [x] Compliance failure removal
- [x] Final rebase 
- [x] Check that there are no commits in the branch that have been already been merged to `main`
- [x] Final check over all commit(s)
```[tasklist]
### Tasks
- [x] Update v3.7 migration guide with information on switch to HWMv2
```

**Comment by carlescufi** [comment]
Merged here: https://github.com/zephyrproject-rtos/zephyr/pull/69607
