### ISSUE TITLE
Full persistent storage support for Bluetooth

### ISSUE THREAD

**Issue by jhedberg** [zephyrproject-rtos/zephyr#7073]
The Bluetooth stack should have integrated support for storing persistently (in flash) any security keys, Client Characteristic Configuration (CCC) as well as Mesh network state. Currently the stack does have the bt_storage API, but it was never used for anything else than the identity address and local IRK.

The idea is to take advantage of the recently introduced settings API, allowing either FCB or a filesystem to be used as the backend.

- [x] Pairing keys storage (`struct bt_keys`). Merged as #7226
- [ ] GATT CCC storage (coming from #7417)
- [ ] Mesh Storage (coming from #7368 and #7428 )
