### ISSUE TITLE
boards: Move existing boards to "default configuration guidelines"

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/zephyr#7151]
Following introduction of "default board configuration guidelines" (#6858), one part of the work is to move boards already ported to zephyr to conform with guidelines available here:
http://docs.zephyrproject.org/porting/board_porting.html#default-board-configuration

In order to migrate all boards to the new standards, work is split into several tickets. See below.
As part of the work to do on each board:
- pins should be configured to fit valuable HW components available on board
- pins should be configured to fit connector if featured on the board (dts file should provide connector configuration and board should select matching connector flags, cf #6837)
- propose a default network interface (when possible)
- If ever a pin conflict prevents configuration of one of the components, board documentation should be updated with conflict and arbitration.
- update board metadata yaml file vs new board configuration [(cf documentation)](https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/subsystems/test/sanitycheck.rst#board-configuration)

Work is split into following issues:

- [x] Get 96Boards boards (4) compliant with default configuration guidelines (#9233)
- [x] Get ARC boards (4) compliant with default configuration guidelines (#9234)
- [x] Get XTENSA boards (2) compliant with default configuration guidelines (#9235)
- [x] Get X86 boards (8) compliant with default configuration guidelines (#9236)
- [x] Get RISCV boards (5) compliant with default configuration guidelines (#9237)
- [x] Get POSIX board compliant with default configuration guidelines (#9238)
- [x] Get NIOS boards (2) compliant with default configuration guidelines (#9239)
- [x] Get ARM boards (2) compliant with default configuration guidelines (#9240)
- [x] Get ATMEL SoC based boards (6) compliant with default configuration guidelines (#9241)
- [x] Get NORDIC SoC based boards (15) compliant with default configuration guidelines (#9242)
- [x] Get NXP SoC based boards (8) compliant with default configuration guidelines (#9243)
- [x] Get SILABS board compliant with default configuration guidelines (#9244)
- [x] Get TI SoC based boards (4) compliant with default configuration guidelines (#9245)
- [x] Get ST Nucleo boards (14) compliant with default configuration guidelines (#9246)
- [x] Get ST Disco and Eval boards (14) compliant with default configuration guidelines (#9247)
- [x] Get Olimex boards (4) compliant with default configuration guidelines (#9248)
- [x] Get ST Based boards (3) compliant with default configuration guidelines (#9249)

In order to allow provision of dts connector aliases, dtc > v1.4.1 should be used. Hence all these tickets (at least when a connector is available on board) have a dependency on zephyr SDK v0.9.3:
https://github.com/zephyrproject-rtos/meta-zephyr-sdk/releases/tag/0.9.3-rc2

PR #7176 could be used as reference for this update.

EDIT: Following creation of #19116 that aims at instantiating a systematic test to check compliance, I'm closing the above issues.

**Comment by erwango** [comment]
@nashif , @galak : follow up of [Default board configuration guidelines](#6858).
I'll start deploying if you're ok with this.

**Comment by erwango** [comment]
> I'll start deploying if you're ok with this.

I'll provide a reference PR beforehand

**Comment by pizi-nordic** [comment]
FYI: @carlescufi, @anangl
