### ISSUE TITLE
Zephyr 3.7 module update overview

### ISSUE THREAD

**Issue by dleach02** [zephyrproject-rtos/zephyr#73878]
Umbrella issue for modules which may require an update before Zephyr 3.7.

- [x] https://github.com/zephyrproject-rtos/hostap (@krish2718, @jukkar)
- [ ] https://github.com/zephyrproject-rtos/zcbor (@de-nordic)
- [x] https://github.com/zephyrproject-rtos/thrift (@cfriedt)
- [x] https://github.com/zephyrproject-rtos/tflite-micro (@laurenmurphyx64)
- [x] https://github.com/zephyrproject-rtos/sof (@kv2019i)
- [x] https://github.com/zephyrproject-rtos/picolibc (@keith-packard, @stephanosio)
- [x] https://github.com/zephyrproject-rtos/percepio (@eriktamlin, @aronlander-pe)
- [x] https://github.com/zephyrproject-rtos/openthread (@rlubos)
- [x] https://github.com/zephyrproject-rtos/open-amp (@carlocaione)
- [x] https://github.com/zephyrproject-rtos/nanopb (@pdgendt)
- [x] https://github.com/zephyrproject-rtos/mcuboot (@d3zd3z, @de-nordic, @nordicjm)
- [ ] https://github.com/zephyrproject-rtos/lz4 (@Navin-Sankar)
- [x] https://github.com/zephyrproject-rtos/lvgl (@faxe1008, @brgl, @pdgendt)
- [x] https://github.com/zephyrproject-rtos/loramac-node (@Mani-Sadhasivam)
- [x] https://github.com/zephyrproject-rtos/liblc3 (@Casper-Bonde-Bose, @MariuszSkamra)
- [ ] https://github.com/zephyrproject-rtos/fatfs (@de-nordic)
- [x] https://github.com/zephyrproject-rtos/edtt (@aescolar, @wopu-ot, @thoh-ot)
- [x] https://github.com/zephyrproject-rtos/cmsis-nn (@XenuIsWatching, @stephanosio)
- [ ] https://github.com/zephyrproject-rtos/cmsis-dsp (@XenuIsWatching, @stephanosio)
- [ ] https://github.com/zephyrproject-rtos/cmsis (@stephanosio, @microbuilder, @povergoing)
- [ ] https://github.com/zephyrproject-rtos/chre (@yperess)
- [x] https://github.com/zephyrproject-rtos/canopennode (@henrikbrixandersen)
- [x] https://github.com/zephyrproject-rtos/babblesim-manifest (@aescolar)
- [ ] https://github.com/zephyrproject-rtos/acpica (@najumon1980)

Folks that are tagged please comment and confirm the status of your modules with respect to readiness for the 3.7 release.

- [Zephyr 3.7 Release Checklist #69408](https://github.com/zephyrproject-rtos/zephyr/issues/69408)
- [Zephyr 3.7 security related modules update overview #73703](https://github.com/zephyrproject-rtos/zephyr/issues/73703)

**Comment by JordanYates** [comment]
`loramac-node` is in maintenance mode and has no updates.
`cmsis-nn` update here: #73995

**Comment by faxe1008** [comment]
`lvgl` module is at the current viable released version 8.4.0 [https://github.com/lvgl/lvgl/releases/tag/v8.4.0](https://github.com/lvgl/lvgl/releases/tag/v8.4.0). Version 9 breaks at least the monochrome display support so it's not viable for now. PR for that is pending but not realistic for 3.7.

**Comment by krish2718** [comment]
No planned updated for `hostap` for `3.7.0`.

**Comment by carlocaione** [comment]
For `open-amp` and `libmetal` https://github.com/zephyrproject-rtos/zephyr/pull/74186

**Comment by keith-packard** [comment]
No known issues for picolibc for 3.7.0 -- current release is the same as zephyr uses.

**Comment by JordanYates** [comment]
`tflite-micro` upgrade is part of #73995, need either perms for the repo or someone to work out the desired branch structure.

**Comment by henrikbrixandersen** [comment]
There's a request (https://github.com/zephyrproject-rtos/zephyr/issues/70285) to update CANopenNode to v4.0, but it will not happen in time for v3.7.0.

**Comment by nordicjm** [comment]
No update planned for MCUboot in the zephyr 3.7 release

**Comment by MariuszSkamra** [comment]
As discussed offline with @sjanc, no plans to update liblc3 in the Zephyr 3.7.0

**Comment by cfriedt** [comment]
Thrift docs gave a minor update in https://github.com/zephyrproject-rtos/zephyr/pull/74557

There is a version upgrade, but I would rather save that until after 3.7

**Comment by XenuIsWatching** [comment]
cmsis-dsp hasn't had an update come out. I'd rather wait for the next 'taged' release

**Comment by dleach02** [comment]
> Thrift docs have a minor update in #74557
> 
> There is a version upgrade, but I would rather save that until after 3.7



> Thrift docs have a minor update in #74557
> 
> There is a version upgrade, but I would rather save that until after 3.7

@cfriedt remember that v3.7 is LTS3. Do you want this version to stick for the next 3+ years?

**Comment by dleach02** [comment]
> There's a request (#70285) to update CANopenNode to v4.0, but it will not happen in time for v3.7.0.



> There's a request (#70285) to update CANopenNode to v4.0, but it will not happen in time for v3.7.0.

@henrikbrixandersen so that means the LTS will stick with the older version for the next 3 years

**Comment by henrikbrixandersen** [comment]
> @henrikbrixandersen so that means the LTS will stick with the older version for the next 3 years

Correct.

**Comment by carlocaione** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/74186 this is waiting to be merged

**Comment by aescolar** [comment]
Closing as 3.7.0 rc3 has been tagged and no more module updates are expected.
