### ISSUE TITLE
3.7 Release notes - pending areas

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#75933]
This issue is to track and ping maintainers of areas which may lack release notes entries for 3.7 (https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/releases/release-notes-3.7.rst).
Maintainers you are very welcome to reply here if there is nothing of significance to be mentioned in the release notes and tick the entry in this list.

Edit: Note: There is no need to add a separate comment in this issue linking to new release notes PRs. If you want a link you can refer from your PR to this issue, or edit this first comment adding the link in this list.

Edit: When writing release notes please remember to use past tense. If there has been some change of great relevance in your area you are welcome to add or suggest adding it to the "Major enhancements" section.

### Architectures & platforms
- [x] arc @ruuddw @abrodkin @evgeniy-paltsev
- [x] arm @ithinuel
- [ ] NIOS-2 @nashif 
- [x] x86 @edersondisouza 
- [x] BeagleBoard @jadonk
- [x] Espressif @sylvioalves 
- [x] Ezurio @rerickson1
- [x] GD32 @cameled @nandojve 
- [x] Google: @fabiobaltieri 
- [x] Infineon @ifyall 
- [x] Intel x86 @edersondisouza 
- [x] Intel Xtensa @dcpleung 
- [ ] Intel ISH @kwd-doodling 
- [ ] Intel Agilex @gdengi 
- [x] Litex @tgorochowik @kgugala @fkokosinski 
- [ ] Microchip MEC @jvasanth1 
- [x] Microchip RISC-V @fkokosinski @kgugala 
- [x] Microchip SAM @nandojve 
- [ ] Nuvoton NPCX @MulinChao @ChiHuaL 
- [x] Nuvoton Numicro @cyliangtw
- [x] nRF @anangl @masz-nordic 
- [ ] opentitan @snematbakhsh 
- [ ] Panasonic @pideu-sj 
- [ ] Renesas SmartBond @ioannis-karachalios @andrzej-kaczmarek 
- [x] Renesas RA @soburi @KhiemNguyenT 
- [x] Renesas RZ @tgorochowik 
- [ ] Renesas R-Car @aaillet @lorc 
- [x] Synopsys @evgeniy-paltsev @ruuddw 
- [x] TI Simplelink / K3 @vaishnavachath
- [ ] Xen @povergoing 
- [ ] Xilinx @henrikbrixandersen 
- [x] Shields @kartben @erwango 

### Drivers and sensors
- [x] Auxiliary Display @thedjnK
- [ ] Audio @lyakh @lgirdwood @marc-hb @kv2019i
- [x] bbram @yperess 
- [ ] Coredump @mrkhldn 
- [x] Crypto @ceolin
- [x] DAC @martinjaeger (#76159)
- [ ] DAI @kv2019i @LaurentiuM1234
- [ ] EDAC @finikorg 
- [x] FPGA @cfriedt 
- [x] Fuel gauge @aaronemassey @teburd
- [x] GNSS @bjarki-andreasen 
- [ ] IEEE 802.15.4 @fgrandel @jukkar @rlubos 
- [x] LED @Mani-Sadhasivam @simonguinot 
- [ ] Mbox @carlocaione 
- [x] Memory management @dcpleung @carlocaione 
- [x] MSPI @swift-tk 
- [ ] PECI @albertofloyd 
- [x] PCI @dcpleung 
- [x] Retained memory @nordicjm
- [x] SMBUS @finikorg
- [ ] syscon @carlocaione 
- [x] System timer @andyross 
- [ ] Time Aware GPIO @akanisetti
- [ ] Virtualization @tbursztyka 
- [x] W1 @str4t0m

### Libraries / Subsystems
- [ ] ACPI @najumon1980
- [ ] Benchmarks @peter-mitsis
- [ ] Binary Descriptors @yonsch
- [ ] Bluetooth controller @cvinayak 
- [ ] Bluetooth mesh @PavelVPV @alxelax @jhedberg 
- [x] Bluetooth classic @lylezhu2012
- [ ] C++ @stephanosio 
- [ ] C library @stephanosio 
- [ ] Cache @carlocaione 
- [ ] CI @stephanosio 
- [ ] DAP @jfischer-no 
- [ ] Debug: @nashif 
- [x] Demand Paging @dcpleung 
- [ ] Device Driver Model @gmarull @tbursztyka 
- [x] DFU @de-nordic @nordicjm 
- [ ] DSP subsystem @stephanosio 
- [x] EC Host Commands @niedzwiecki-dawid 
- [x] Emulation @yperess 
- [x] Filesystem @de-nordic 
- [ ] Filesystems: FatFs reentrant support: @Ox11 
- [x] Formatted output: @nordic-krch 
- [x] Heap management @npitre @andyross 
- [ ] IPC @carlocaione @arnopo 
- [ ] JSON @d3zd3z 
- [x] mgmt: updatehub @nandojve 
- [ ] Modbus @jfischer-no 
- [ ] OpenAMP @carlocaione 
- [x] OSDP @sidcha (PR: #76082)
- [x] Picolibc : @keith-packard 
- [x] POSIX API @cfriedt @ycsin 
- [x] Retention @nordicjm
- [x] RTIO @teburd 
- [x] Task watchdog @martinjaeger (#76160)
- [ ] Test framework /ztest @nashif 
- [ ] Tracing @nashif 
- [ ] Twister @nashif 
- [x] USB susbystem & drivers @jfischer-no @tmon-nordic
- [ ] USB-C:  @sambhurst
- [x] Userspace @dcpleung 
- [x] VFS @de-nordic 
- [x] ZBus @rodrigopex

```[tasklist]
### Tasks
```

**Comment by aescolar** [comment]
@bjarki-andreasen,  @rlubos,  @simonguinot,  @carlocaione,  @carlocaione,  @swift-tk,  @albertofloyd,  @nordicjm, @carlocaione,  @andyross,  @akanisetti, @tbursztyka,  @str4t0m, @najumon1980, @peter-mitsis, @yonsch, @cvinayak,  @jhedberg,  @lylezhu2012, @stephanosio,  @stephanosio,  @carlocaione,  @stephanosio,  @jfischer-no,  @tbursztyka,  @nordicjm,  @stephanosio,  @niedzwiecki-dawid,  @de-nordic, @Ox11,  @nordic-krch,  @andyross,  @arnopo,  @d3zd3z,  @jfischer-no,  @carlocaione,  @sidcha,  @keith-packard,  @ycsin,  @nordicjm, @tmon-nordic, @sambhurst, @de-nordic,  @rodrigopex,

**Comment by rodrigopex** [comment]
@aescolar, Done #75938.

**Comment by jadonk** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/75949

**Comment by ithinuel** [comment]
Arm https://github.com/zephyrproject-rtos/zephyr/pull/75957

**Comment by dcpleung** [comment]
Demand paging and Intel Xtensa (audio DSP) are at https://github.com/zephyrproject-rtos/zephyr/pull/75972.

For memory management and userspace, there are mostly internal changes which should be invisible to areas outside of them.

**Comment by cyliangtw** [comment]
@aescolar, 
it's done #75980

**Comment by teburd** [comment]
rtio release notes #76013

**Comment by aaronemassey** [comment]
fuel gauge release notes https://github.com/zephyrproject-rtos/zephyr/pull/76009

**Comment by de-nordic** [comment]
DFU, FS, VFS:
https://github.com/zephyrproject-rtos/zephyr/pull/76018
https://github.com/zephyrproject-rtos/zephyr/pull/76019

**Comment by keith-packard** [comment]
picolibc unchanged since 3.6.0 (still at 1.8.6)

**Comment by rerickson1** [comment]
Ezurio release notes: https://github.com/zephyrproject-rtos/zephyr/pull/76028

**Comment by bjarki-andreasen** [comment]
GNSS release notes: #76049

**Comment by edersondisouza** [comment]
Nothing worth mention for x86.

**Comment by cfriedt** [comment]
POSIX API doc cleanup in #76114 and release notes in #76112

**Comment by cfriedt** [comment]
FPGA release notes in #76116

**Comment by simonguinot** [comment]
LED release notes: https://github.com/zephyrproject-rtos/zephyr/pull/76051 and https://github.com/zephyrproject-rtos/zephyr/pull/76091.

**Comment by fkokosinski** [comment]
Renesas RZ/T2M: https://github.com/zephyrproject-rtos/zephyr/pull/76152.

**Comment by evgeniy-paltsev** [comment]
ARC architecture and Synopsys platforms: #76183

**Comment by lylezhu2012** [comment]
Bluetooth classic release notes: #76197.

**Comment by str4t0m** [comment]
1-Wire release notes: #76288.

**Comment by aescolar** [comment]
Closing as the release is being done right now.
