### ISSUE TITLE
Zephyr 4.0 Release Checklist

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#76338]
#### As soon as possible
- [x] Ensure there is a draft `doc/releases/release-notes-4.0.rst` and `doc/releases/migration-guide-4.0.rst` with feature summary from the previous one and if not create one (previous #69418)
- [x] Ensure MAINTAINERS.yml "Release Notes"'s maintainers to point at the current release owners (#76876)
- [x] Set the current release managers as assignee's in https://github.com/zephyrproject-rtos/zephyr/issues/76943 and ensure it is linked from the [release plan](https://github.com/orgs/zephyrproject-rtos/projects/13).

#### From day one but with extra focus as we approach RC1 and after:
- [x] Check the CI [bi-weekly](https://github.com/zephyrproject-rtos/zephyr/actions/workflows/twister.yaml?query=event%3Aschedule) run for build failures that should be fixed and report or fix them.
- [x] Make sure the release plan is kept up to date:
   - See https://github.com/orgs/zephyrproject-rtos/projects/13
- [x] Ensure the [release management page](https://github.com/zephyrproject-rtos/zephyr/wiki/Release-Management) has an up-to-date schedule for the release

#### One month before RC1:
- [x] Ping west project maintainers to remind them of the RC1/freeze deadline and to consider if their modules should be updated (you may want to extract all west projects' maintainers names from the MAINTAINERS files and create an issue like) (previous https://github.com/zephyrproject-rtos/zephyr/issues/73834)
- [x] Start giving heads ups on the TSC meeting about the incoming freeze.

#### Two weeks before RC1:
- [x] Send a heads ups about the incoming freeze to dev-mailing list and Discord General channel

#### Pre RC1
   - [x] Create next release (v4.1.0) milestone so that features that don't make it to the release can be assigned a milestone
   - [x] Verify that all security-critical external components and external dependencies are up to date 
     - (3.7) https://github.com/zephyrproject-rtos/zephyr/issues/73703
     - (3.7) https://github.com/zephyrproject-rtos/zephyr/issues/73878
     - (4.0) https://github.com/zephyrproject-rtos/zephyr/issues/80489
     - (4.0) https://github.com/zephyrproject-rtos/zephyr/issues/80491
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as un-exploitable (ask Security working group).
   - [x] Make sure there's no pending ["Release Blocker"](https://github.com/zephyrproject-rtos/zephyr/issues?q=is%3Aissue+is%3Aopen+label%3A%22Release+Blocker%22) issues
   - [x] Ensure that the latest Zephyr SDK contains all the changes necessary to support the new features included in, or planned for this release; if not, ping the SDK maintainer (@stephanosio) to release a new SDK version.
       - [x] Check if any toolchain-related enhancements and bug fixes are required for any of the pull requests targeting this release. If any of these enhancements and bug fixes are not part of the latest Zephyr SDK, a new SDK version must be released.
       - [x] Check that the Picolibc version in the latest SDK matches the Picolibc module version in `west.yml`. If they do not match, a new SDK version must be released. (ping @stephanosio and @keith-packard )
   - [x] Create a "Deprecated APIs/options to be removed by x.y" issue for 4.3 (N+3), linking to it from & to the 4.2 one (https://github.com/zephyrproject-rtos/zephyr/issues/77070) . Remember to set the `deprecation_tracker` label.

See https://docs.zephyrproject.org/latest/project/release_process.html#tagging for tagging details, release specific filters under https://github.com/zephyrproject-rtos/zephyr/wiki/Filters to find pending PRs.

- [x] Release Notes and Migration Guide WIP
  - [x] Make sure to tell everybody to
    * Use the **past tense** (i.e. "X has been added" or "X is now Y")
    * Update `doc/releases/release-notes-4.0.rst` detailed sections (relative to 3.7.0 release) as important issues are addressed (subsystem owners). (previous: https://github.com/zephyrproject-rtos/zephyr/issues/54495)
  - [x] Be sure to remind maintainers to update the release notes, at the very least in the rc1, rc2 and rc3 emails. But you may need to create a GH issue to follow up.

#### After RC3, before final release

- [x] Finalize Release Notes and Migration Guide: (previous: #76113, #76295 )
  - [x] Review `doc/releases/release-notes-4.0.rst` overview summary and details sections
    - [x] Request summary details from subsystem maintainers
- [x] Add new version in `doc/conf.py`, `doc/releases/index.rst`, and `doc/releases/eol_releases.rst` (previous  #76047)
- [x] Remove EOL version(s) in `doc/conf.py`, `doc/releases/index.rst`, and `doc/releases/eol_releases.rst`  : (previous: #69404) .
- [x] Update `doc/LICENSING.rst` for new components that do not have a license: (previous: #69392)
- [x] Remaining Release Notes (previous #75933)
- [x] Update version in VERSION ([EXTRAVERSION must be empty, not zero 0](https://docs.zephyrproject.org/latest/project/release_process.html#tagging)) (previous #76047 )
- [x] Tag v4.0.0 (see https://docs.zephyrproject.org/latest/project/release_process.html#tagging)
- [x] Update and publish the [draft GitHub release](https://github.com/zephyrproject-rtos/zephyr/releases) created by the CI.
- [x] Tag v4.0.0 in [example-application](https://github.com/zephyrproject-rtos/example-application) (previous: https://github.com/zephyrproject-rtos/example-application/pull/73) and create github release from tag.

### After Release
  - [x] Update patchlevel in VERSION (PATCHLEVEL = 99) (e.g. https://github.com/zephyrproject-rtos/zephyr/pull/76334) and tag `v4.0.99` (https://github.com/zephyrproject-rtos/zephyr/pull/81474)
  - [x] Create `v4.0-branch` branch for 4.0.x releases (from v4.0.0 tag, don't include the switch to patchlevel 99)
  - [x] Create `backport v4.0-branch` label
  - [x] Move all PRs/Issues in the v4.0.0 milestone to the next milestone
  - [x] Close v4.0.0 milestone 
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release and announce the opening of the merge window
  - [x] Create checklist issue for next release (#81713)
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Marketing Blog for announcing release (https://www.zephyrproject.org/blog / https://www.zephyrproject.org/announcements/)
  - [x] Post an update in https://github.com/zephyrproject-rtos/zephyr/discussions under General, have one of our administrators move it to Announcements and pin it.
    - [x]  (3.7 https://github.com/zephyrproject-rtos/zephyr/discussions/76336) 
    - [x] (4.0: https://github.com/zephyrproject-rtos/zephyr/discussions/81499)
  - [x] Post an announcement in discord in the #general & #release channels
  - [x] Update MAINTAINERS.yml "Release Notes" maintainers to point at the next release owners (https://github.com/zephyrproject-rtos/zephyr/pull/81669)
  - [x] Update current and supported version information in the [Security Policy](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/SECURITY.md). (https://github.com/zephyrproject-rtos/zephyr/pull/81614)
  - [x] If you're a first time release manager, you may contact Tracey (or [info@zephyrproject.org](mailto:info@zephyrproject.org)) to claim your Release Manager badge.
- [x] Create draft `doc/releases/release-notes-4.1.rst` and `doc/releases/migration-guide-4.1.rst` with feature summary from the previous one (if not there already) #76344

Previous checklist: #69408

**Comment by stephanosio** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/80192 should tick off all the SDK-related items.
