### ISSUE TITLE
Deprecated APIs/options to be removed by 4.0

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#76943]
This issue tracks APIs/options which are meant to be removed by the 4.0 given release
(after they have been deprecated for 2 releases or more)

# 4.0

* [x] config BT_MESH_PROV_DEVICE @Andrewpini 25d44a828d404422099dfa4d8875438dacf1f38c #81305
* [x] config LWM2M_RD_CLIENT_SUPPORT @SeppoTakalo 321db8561dcb5761d952a6362fc87831ffeb24de #76944
* [x] __deprecated int lwm2m_set_u64 / get  @SeppoTakalo 071cad2e762b04e7ea782a1742ab35b802bbcd78 4.0 #76944
* [x] K_THREAD_STACK_MEMBER @dcpleung  04a0cf7d79f2f7fef63b6754b6da1bd85becb3fd < 4.0 #77030 
* [x] __deprecated inline bool smp_add_cmd_ret @nordicjm  5c88d4554485ea860c0202ef563d87c98161d704 4.0 #80572
* [x] static inline uint64_t net_pkt_txtime(struct net_pkt *pkt) , net_pkt_set_txtime @fgrandel 36402b6d2a79f17c27104c02aae0e1f00d411f23 < 4.0 f2d6c74875a0c24822a86aaf77cec75e3cc4d64b
* [x] static inline uint64_t sys_clock_timeout_end_calc(k_timeout_t timeout) @npitre 52e2f831851e8de8aa29e00938a0ef8f6ae8e8c7 < 4.0 cfaaf0135ad6fbd7711e5f0d2c7ae05c1d8a423e
* [x] Z_DEVICE_LEVEL_DEPRECATED_EARLY	@gmarull	beec8b05a8f11de474c88cdec15cdf89dbd3a86b < 4.0 cfe5bd922432d9c2090e9cbf149edd7172dc4e62
* [x] #define ceiling_fraction @gmarull	53da110dbfe5f73efa842c4b8560dba26f5a84a9 < 4.0 07f3ac95be4bc28e92359cc111a116aba88f5791
* [x] #define CBPRINTF_PACKAGE_CONVERT_  @kartben  779636415c182c5c61d7afbc0c9dc850bc7c4fd1 < 4.0 #77032
* [x] <zephyr/random/rand32.h> @ceolin e7bd10ae719d1773f8d6b189c18f775d9dfcc93d < 4.0 #81307
* [x] cmsis.h @gmarull	 b966865dd1de297cf75404743847b5f7bac52d09 4.0 fd4ec84fc69a4dc679b3fad8f5c5c809b52d633d

---------

#### Deprecation guidelines
https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#deprecated

#### Related
* https://github.com/zephyrproject-rtos/zephyr/issues/77069

**Comment by dkalowsk** [comment]
All marked as done.  Closing.
