### ISSUE TITLE
Deprecated APIs/options to be removed by 4.2

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#77070]
This issue tracks APIs/options which are meant to be removed by the *4.2* release
(after they have been deprecated for 2 releases or more)

# 4.2

* [ ] config SOC_DCDC_NRF52X , SOC_DCDC_NRF52X_HV @gmarull   aaacd682cc4cc6b0106b2de8fe6a963584e4ceff
* [ ] config SOC_DCDC_NRF53X_APP, SOC_DCDC_NRF53X_NET, SOC_DCDC_NRF53X_HV @gmarull 1eddb047f98d1afe1d31ca7bcaba87a3bbba3e79
* [ ] config BOARD_ENABLE_CPUNET	@gmarull 4c84a6f658b65557bb23719e23461a9785809e42
* [ ] adafruit feather nrf52840 express board alias in deprecated.cmake @jacobw 5e789c3ae0c7cac997d03ab73b778a334e5186a0
* [x] native_posix @aescolar #76898 https://github.com/zephyrproject-rtos/zephyr/pull/86305
* [x] [TinyCrypt shim driver](https://github.com/zephyrproject-rtos/zephyr/pull/79566) done in https://github.com/zephyrproject-rtos/zephyr/pull/90113
* [x] Kscan, everything @fabiobaltieri https://github.com/zephyrproject-rtos/zephyr/pull/76974 https://github.com/zephyrproject-rtos/zephyr/pull/86831
* [x] Remove `net_buf_put()` & `net_buf_get()` @henrikbrixandersen 9584008d9f14e63687148ccf07fab9591e3a2780 (https://github.com/zephyrproject-rtos/zephyr/pull/86880)
* [x] Remove header file `include/zephyr/net/buf.h` @henrikbrixandersen  159f7dbbb1d9aa752a1041a4985356edf00a9348 (https://github.com/zephyrproject-rtos/zephyr/pull/86880)

### leftovers from 4.1

* [ ] Various deprecated cmake items in https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/modules/FindDeprecated.cmake#L56 @nordicjm @tejlmand 4.0
* [x] config DISABLE_SSBD , ENABLE_EXTENDED_IBRS @dcpleung 4c031e2 #81540
* [x] config COUNTER_MCUX_KINETIS_LPTMR @decsny eae316ebc9ffad98b93291ebaca71a15e74fed1d https://github.com/zephyrproject-rtos/zephyr/pull/86934
* [x] config MCUX_KINETIS_LPTMR @decsny  90986e7e22f42a45e25da84ef3e293f4171f9886 https://github.com/zephyrproject-rtos/zephyr/pull/86934
* [x] lib/posix/options/Kconfig.deprecated @cfriedt (see #86824)
* [x] config SOC_ANDES_V5_L2C @wtlee 5db259010604e989dcbbf8b891db2a65af74a88d
* [ ] config GPIO_AS_PINRESET <= 4.1 @gmarull https://github.com/zephyrproject-rtos/zephyr/pull/92230
* [ ] config NFCT_PINS_AS_GPIOS <= 4.1 @gmarull https://github.com/zephyrproject-rtos/zephyr/pull/92230
* [x] __deprecated typedef struct arch_esf z_arch_esf_t; @ycsin e54b27b9671447f7a74d6221fc753c6bd22f8f94 4.1 #84326
* [ ] BT_LE_ADV_.. @theob-pro  909ad8170c7feaae8c03ae3bc4aeafaed37d2cfa 4.1

-----

#### Deprecation guidelines
https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#deprecated

#### Related
* https://github.com/zephyrproject-rtos/zephyr/issues/77069
* https://github.com/zephyrproject-rtos/zephyr/issues/80539

**Comment by dkalowsk** [comment]
@decsny and @gmarull your names are on a lot of these deprecation items for 4.2.  Can you give a look and update on any status changes needed?

**Comment by dkalowsk** [comment]
@valeriosetti there is an item for the deprecation of TinyCrypt.  As far as I can tell this is done now, and want to verify with you.  If we're good can you check the box here?

**Comment by valeriosetti** [comment]
> [@valeriosetti](https://github.com/valeriosetti) there is an item for the deprecation of TinyCrypt. As far as I can tell this is done now, and want to verify with you. If we're good can you check the box here?

I checked past release notes and the situation about TinyCrypt is the following:
- TC shim driver deprecated in 4.0
   - It is removed in 4.2 by @ceolin in #90113

- TC library deprecated in 4.1
    - It should be removed in 4.3 and indeed there is already a note for this in #80539.
    - I noticed that there are still users of TinyCrypt in Zephyr codebase (tests and BT) so I guess I will need to prepare some PR to remove this usage before 4.3

I think I can update TinyCrypt lines in the description of this issue and #80539 to clarify the scope in both releases

**Comment by decsny** [comment]
> [@decsny](https://github.com/decsny) and [@gmarull](https://github.com/gmarull) your names are on a lot of these deprecation items for 4.2. Can you give a look and update on any status changes needed?

looks like my name is only on the LPTMR one, which is already done, so I edited the message with the PR link.

**Comment by jacobw** [comment]
> * adafruit feather nrf52840 express board alias in deprecated.cmake [@jacobw](https://github.com/jacobw) [5e789c3](https://github.com/zephyrproject-rtos/zephyr/commit/5e789c3ae0c7cac997d03ab73b778a334e5186a0)

resolved in #92068

**Comment by nordicjm** [comment]
> * config GPIO_AS_PINRESET <= 4.1
> * config NFCT_PINS_AS_GPIOS <= 4.1

Have submitted a PR: https://github.com/zephyrproject-rtos/zephyr/pull/92230

**Comment by danieldegrasse** [comment]
Closing out, https://github.com/zephyrproject-rtos/zephyr/issues/80539 now tracks this
