### ISSUE TITLE
Remove CONFIG_PINCTRL from all defconfig files

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#78619]
**Describe the bug**
This Kconfig has wrongly been added to defconfig files, it is not the right place for it, it has never been the right place for it, drivers that need it should select the symbol in their Kconfig entries. The following boards do this wrongly and need to be fixed:

https://github.com/zephyrproject-rtos/zephyr/pull/80664
- [x] boards/96boards/meerkat96/96b_meerkat96_mcimx7d_m4_defconfig
- [x] boards/arduino/nicla_sense_me/arduino_nicla_sense_me_defconfig
- [x] boards/element14/warp7/warp7_mcimx7d_m4_defconfig
- [x] boards/madmachine/mm_feather/mm_feather_defconfig
- [x] boards/madmachine/mm_swiftio/mm_swiftio_defconfig
- [x] boards/phytec/mimx8mm_phyboard_polis/mimx8mm_phyboard_polis_mimx8mm6_m4_defconfig
- [x] boards/phytec/mimx8mp_phyboard_pollux/mimx8mp_phyboard_pollux_mimx8ml8_m7_defconfig
- [x] boards/pjrc/teensy4/teensy40_defconfig
- [x] boards/pjrc/teensy4/teensy41_defconfig
- [x] boards/segger/ip_k66f/ip_k66f_defconfig
- [x] boards/technexion/pico_pi/pico_pi_mcimx7d_m4_defconfig
- [x] boards/toradex/colibri_imx7d/colibri_imx7d_mcimx7d_m4_defconfig
- [x] boards/toradex/verdin_imx8mp/verdin_imx8mp_mimx8ml8_m7_ddr_defconfig
- [x] boards/toradex/verdin_imx8mp/verdin_imx8mp_mimx8ml8_m7_defconfig
- [x] boards/udoo/udoo_neo_full/udoo_neo_full_mcimx6x_m4_defconfig
___
@soburi https://github.com/zephyrproject-rtos/zephyr/pull/76794
- [x] boards/arduino/uno_r4/arduino_uno_r4_minima_defconfig
- [x] boards/arduino/uno_r4/arduino_uno_r4_wifi_defconfig
___
@jadonk https://github.com/zephyrproject-rtos/zephyr/pull/79407
- [x] boards/beagle/beagleconnect_freedom/beagleconnect_freedom_defconfig
___
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/78634
- [x] boards/digilent/zybo/zybo_defconfig
___
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/78634
- [x] boards/enclustra/mercury_xu/mercury_xu_defconfig
___
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/78621
- [x] boards/ezurio/rm1xx_dvk/rm1xx_dvk_defconfig 
___
@ifyall
- [x] boards/infineon/cy8ckit_062s4/cy8ckit_062s4_defconfig
- [x] boards/infineon/cy8cproto_062_4343w/cy8cproto_062_4343w_defconfig
- [x] boards/infineon/cy8cproto_063_ble/cy8cproto_063_ble_defconfig
- [x] boards/infineon/cyw920829m2evk_02/cyw920829m2evk_02_defconfig
___
@jvasanth1 https://github.com/zephyrproject-rtos/zephyr/pull/82086
- [x] boards/microchip/mec1501modular_assy6885/mec1501modular_assy6885_defconfig
- [x] boards/microchip/mec15xxevb_assy6853/mec15xxevb_assy6853_defconfig
- [x] boards/microchip/mec172xevb_assy6906/mec172xevb_assy6906_defconfig
- [x] boards/microchip/mec172xmodular_assy6930/mec172xmodular_assy6930_defconfig
___
- [x] boards/mikroe/clicker_ra4m1/mikroe_clicker_ra4m1_defconfig
___
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/78621
- [x] boards/nordic/nrf7002dk/nrf7002dk_nrf5340_cpuapp_defconfig
- [x] boards/nordic/nrf7002dk/nrf7002dk_nrf5340_cpuapp_nrf7001_defconfig
- [x] boards/nordic/nrf7002dk/nrf7002dk_nrf5340_cpuapp_nrf7001_ns_defconfig
- [x] boards/nordic/nrf7002dk/nrf7002dk_nrf5340_cpuapp_ns_defconfig
- [x] boards/nordic/nrf7002dk/nrf7002dk_nrf5340_cpunet_defconfig
- [x] boards/nordic/nrf9131ek/nrf9131ek_nrf9131_defconfig
- [x] boards/nordic/nrf9131ek/nrf9131ek_nrf9131_ns_defconfig
___
@MulinChao @ChiHuaL https://github.com/zephyrproject-rtos/zephyr/pull/80726
- [x] boards/nuvoton/npcx4m8f_evb/npcx4m8f_evb_defconfig
- [x] boards/nuvoton/npcx7m6fb_evb/npcx7m6fb_evb_defconfig
- [x] boards/nuvoton/npcx9m6f_evb/npcx9m6f_evb_defconfig
___
@cyliangtw https://github.com/zephyrproject-rtos/zephyr/pull/80903
- [x] boards/nuvoton/numaker_m2l31ki/numaker_m2l31ki_defconfig
- [x] boards/nuvoton/numaker_pfm_m467/numaker_pfm_m467_defconfig
- [x] boards/nuvoton/numaker_pfm_m487/numaker_pfm_m487_defconfig
___
@decsny @EmilioCBen https://github.com/zephyrproject-rtos/zephyr/pull/79065
- [x] boards/nxp/frdm_k22f/frdm_k22f_defconfig
- [x] boards/nxp/frdm_k64f/frdm_k64f_defconfig
- [x] boards/nxp/frdm_k82f/frdm_k82f_defconfig
- [x] boards/nxp/frdm_ke15z/frdm_ke15z_defconfig
- [x] boards/nxp/frdm_ke17z/frdm_ke17z_defconfig
- [x] boards/nxp/frdm_ke17z512/frdm_ke17z512_defconfig
- [x] boards/nxp/frdm_kl25z/frdm_kl25z_defconfig
- [x] boards/nxp/frdm_kw41z/frdm_kw41z_defconfig
- [x] boards/nxp/frdm_mcxa156/frdm_mcxa156_defconfig
- [x] boards/nxp/frdm_mcxn236/frdm_mcxn236_defconfig
- [x] boards/nxp/frdm_mcxn947/frdm_mcxn947_mcxn947_cpu0_defconfig
- [x] boards/nxp/frdm_mcxn947/frdm_mcxn947_mcxn947_cpu0_qspi_defconfig
- [x] boards/nxp/frdm_rw612/frdm_rw612_defconfig
- [x] boards/nxp/hexiwear/hexiwear_mk64f12_defconfig
- [x] boards/nxp/hexiwear/hexiwear_mkw40z4_defconfig
- [x] boards/nxp/imx8mm_evk/imx8mm_evk_mimx8mm6_a53_defconfig
- [x] boards/nxp/imx8mm_evk/imx8mm_evk_mimx8mm6_a53_smp_defconfig
- [x] boards/nxp/imx8mm_evk/imx8mm_evk_mimx8mm6_m4_defconfig
- [x] boards/nxp/imx8mn_evk/imx8mn_evk_mimx8mn6_a53_defconfig
- [x] boards/nxp/imx8mn_evk/imx8mn_evk_mimx8mn6_a53_smp_defconfig
- [x] boards/nxp/imx8mp_evk/doc/index.rst
- [x] boards/nxp/imx8mp_evk/imx8mp_evk_mimx8ml8_a53_defconfig
- [x] boards/nxp/imx8mp_evk/imx8mp_evk_mimx8ml8_a53_smp_defconfig
- [x] boards/nxp/imx8mp_evk/imx8mp_evk_mimx8ml8_adsp_defconfig
- [x] boards/nxp/imx8mp_evk/imx8mp_evk_mimx8ml8_m7_ddr_defconfig
- [x] boards/nxp/imx8mp_evk/imx8mp_evk_mimx8ml8_m7_defconfig
- [x] boards/nxp/imx8mq_evk/imx8mq_evk_mimx8mq6_m4_defconfig
- [x] boards/nxp/imx93_evk/imx93_evk_mimx9352_a55_defconfig
- [x] boards/nxp/imx93_evk/imx93_evk_mimx9352_m33_defconfig
- [x] boards/nxp/lpcxpresso54114/lpcxpresso54114_lpc54114_m0_defconfig
- [x] boards/nxp/lpcxpresso54114/lpcxpresso54114_lpc54114_m4_defconfig
- [x] boards/nxp/lpcxpresso55s06/lpcxpresso55s06_defconfig
- [x] boards/nxp/lpcxpresso55s16/lpcxpresso55s16_defconfig
- [x] boards/nxp/lpcxpresso55s28/lpcxpresso55s28_defconfig
- [x] boards/nxp/lpcxpresso55s36/lpcxpresso55s36_defconfig
- [x] boards/nxp/lpcxpresso55s69/lpcxpresso55s69_lpc55s69_cpu0_defconfig
- [x] boards/nxp/lpcxpresso55s69/lpcxpresso55s69_lpc55s69_cpu0_ns_defconfig
- [x] boards/nxp/mimxrt1010_evk/mimxrt1010_evk_defconfig
- [x] boards/nxp/mimxrt1015_evk/mimxrt1015_evk_defconfig
- [x] boards/nxp/mimxrt1020_evk/mimxrt1020_evk_defconfig
- [x] boards/nxp/mimxrt1024_evk/mimxrt1024_evk_defconfig
- [x] boards/nxp/mimxrt1040_evk/mimxrt1040_evk_defconfig
- [x] boards/nxp/mimxrt1050_evk/mimxrt1050_evk_defconfig
- [x] boards/nxp/mimxrt1060_evk/mimxrt1060_evk_defconfig
- [x] boards/nxp/mimxrt1060_evk/mimxrt1060_evkb_defconfig
- [x] boards/nxp/mimxrt1062_fmurt6/mimxrt1062_fmurt6_defconfig
- [x] boards/nxp/mimxrt1064_evk/mimxrt1064_evk_defconfig
- [x] boards/nxp/mimxrt1160_evk/mimxrt1160_evk_mimxrt1166_cm4_defconfig
- [x] boards/nxp/mimxrt1160_evk/mimxrt1160_evk_mimxrt1166_cm7_defconfig
- [x] boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm4_defconfig
- [x] boards/nxp/mimxrt1170_evk/mimxrt1170_evk_mimxrt1176_cm7_defconfig
- [x] boards/nxp/mimxrt1180_evk/mimxrt1180_evk_mimxrt1189_cm33_defconfig
- [x] boards/nxp/mimxrt1180_evk/mimxrt1180_evk_mimxrt1189_cm7_defconfig
- [x] boards/nxp/mimxrt595_evk/mimxrt595_evk_mimxrt595s_cm33_defconfig
- [x] boards/nxp/mimxrt685_evk/mimxrt685_evk_mimxrt685s_cm33_defconfig
- [x] boards/nxp/mr_canhubk3/mr_canhubk3_defconfig
- [x] boards/nxp/rd_rw612_bga/rd_rw612_bga_defconfig
- [x] boards/nxp/rd_rw612_bga/rd_rw612_bga_rw612_ethernet_defconfig
- [x] boards/nxp/rddrone_fmuk66/rddrone_fmuk66_defconfig
- [x] boards/nxp/s32z2xxdc2/s32z2xxdc2_s32z270_rtu0_defconfig
- [x] boards/nxp/s32z2xxdc2/s32z2xxdc2_s32z270_rtu1_defconfig
- [x] boards/nxp/twr_ke18f/twr_ke18f_defconfig
- [x] boards/nxp/twr_kv58f220m/twr_kv58f220m_defconfig
- [x] boards/nxp/ucans32k1sic/ucans32k1sic_defconfig
- [x] boards/nxp/usb_kw24d512/usb_kw24d512_defconfig
- [x] boards/nxp/vmu_rt1170/vmu_rt1170_mimxrt1176_cm7_defconfig
___
#81587
- [x] boards/openisa/rv32m1_vega/rv32m1_vega_openisa_rv32m1_ri5cy_defconfig
- [x] boards/openisa/rv32m1_vega/rv32m1_vega_openisa_rv32m1_zero_riscy_defconfig
___
@vaishnavachath https://github.com/zephyrproject-rtos/zephyr/pull/80664
- [x] boards/phytec/phyboard_electra/phyboard_electra_am6442_m4_defconfig
- [x] boards/phytec/phyboard_lyra/phyboard_lyra_am6234_m4_defconfig
___
@fkokosinski @kgugala @tgorochowik https://github.com/zephyrproject-rtos/zephyr/pull/78630
- [x] boards/qemu/riscv32_xip/qemu_riscv32_xip_defconfig
___
@soburi @KhiemNguyenT
- [x] boards/renesas/ek_ra2a1/ek_ra2a1_defconfig
- [x] boards/renesas/ek_ra4e2/ek_ra4e2_defconfig
- [x] boards/renesas/ek_ra4m2/ek_ra4m2_defconfig
- [x] boards/renesas/ek_ra4m3/ek_ra4m3_defconfig
- [x] boards/renesas/ek_ra4w1/ek_ra4w1_defconfig
- [x] boards/renesas/ek_ra6e2/ek_ra6e2_defconfig
- [x] boards/renesas/ek_ra6m1/ek_ra6m1_defconfig
- [x] boards/renesas/ek_ra6m2/ek_ra6m2_defconfig
- [x] boards/renesas/ek_ra6m3/ek_ra6m3_defconfig
- [x] boards/renesas/ek_ra6m4/ek_ra6m4_defconfig
- [x] boards/renesas/ek_ra6m5/ek_ra6m5_defconfig
- [x] boards/renesas/ek_ra8d1/ek_ra8d1_defconfig
- [x] boards/renesas/ek_ra8m1/ek_ra8m1_defconfig
- [x] boards/renesas/fpb_ra6e1/fpb_ra6e1_defconfig
- [x] boards/renesas/fpb_ra6e2/fpb_ra6e2_defconfig
- [x] boards/renesas/mck_ra8t1/mck_ra8t1_defconfig
___
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/78621
- [x] boards/ruuvi/ruuvitag/ruuvi_ruuvitag_defconfig
___
@fkokosinski @kgugala @tgorochowik https://github.com/zephyrproject-rtos/zephyr/pull/78630
- [x] boards/sifive/hifive1/hifive1_defconfig
___
@jhedberg https://github.com/zephyrproject-rtos/zephyr/pull/81764
- [x] boards/silabs/dev_kits/sltb010a/sltb010a_defconfig
- [x] boards/silabs/dev_kits/xg24_dk2601b/xg24_dk2601b_defconfig
- [x] boards/silabs/dev_kits/xg27_dk2602a/xg27_dk2602a_defconfig
- [x] boards/silabs/radio_boards/slwrb4180a/slwrb4180a_defconfig
- [x] boards/silabs/radio_boards/xg24_rb4187c/xg24_rb4187c_defconfig
- [x] boards/sparkfun/thing_plus_matter_mgm240p/sparkfun_thing_plus_matter_mgm240p_defconfig
___
@ruuddw @evgeniy-paltsev https://github.com/zephyrproject-rtos/zephyr/pull/82132
- [ ] boards/snps/emsdp/emsdp_emsdp_em11d_defconfig
___
@fkokosinski @kgugala @tgorochowik https://github.com/zephyrproject-rtos/zephyr/pull/78630
- [x] boards/sparkfun/red_v_things_plus/sparkfun_red_v_things_plus_defconfig
___
https://github.com/zephyrproject-rtos/zephyr/pull/79407
- [x] boards/ti/cc1352p7_launchpad/cc1352p7_lp_defconfig
___
@vaishnavachath
- [x] boards/ti/cc1352p1_launchxl/cc1352p1_launchxl_defconfig
- [x] boards/ti/cc1352r1_launchxl/cc1352r1_launchxl_defconfig
- [x] boards/ti/cc1352r_sensortag/cc1352r_sensortag_defconfig
- [x] boards/ti/cc26x2r1_launchxl/cc26x2r1_launchxl_defconfig
- [x] boards/ti/sk_am62/sk_am62_am6234_m4_defconfig
___
@nordicjm https://github.com/zephyrproject-rtos/zephyr/pull/78621
- [x] boards/vcc-gnd/yd_stm32h750vb/yd_stm32h750vb_defconfig
___
@ydamigos #79424
- [x] zephyr/soc/renesas/smartbond/Kconfig.defconfig
___
@nandojve
- [x] soc/atmel/sam/Kconfig.defconfig #80703
- [x] soc/atmel/sam0/Kconfig.defconfig #80703
___
@nandojve
- [x] soc/gd/gd32/Kconfig.defconfig #80697
___
@ifyall https://github.com/zephyrproject-rtos/zephyr/pull/81681
- [x] soc/infineon/cat3/Kconfig.defconfig
___
@Dino-Li @GTLin08 @RuibinChang
- [x] soc/ite/ec/it8xxx2/Kconfig.defconfig.series
___
@jvasanth1 @VenkatKotakonda @albertofloyd
- [x] soc/microchip/mec/mec174x/Kconfig.defconfig.mec1743qlj
- [x] soc/microchip/mec/mec174x/Kconfig.defconfig.mec1743qsz
- [x] soc/microchip/mec/mec175x/Kconfig.defconfig.mec1753qlj
- [x] soc/microchip/mec/mec175x/Kconfig.defconfig.mec1753qsz
- [x] soc/microchip/mec/mech172x/Kconfig.defconfig.mech1723nlj
- [x] soc/microchip/mec/mech172x/Kconfig.defconfig.mech1723nsz
___
@soburi
- [x] soc/raspberrypi/Kconfig.defconfig #80710
___
@soburi @KhiemNguyenT
- [x] soc/renesas/ra/ra2a1/Kconfig.defconfig
- [x] soc/renesas/ra/ra4e2/Kconfig.defconfig
- [x] soc/renesas/ra/ra4m2/Kconfig.defconfig
- [x] soc/renesas/ra/ra4m3/Kconfig.defconfig
- [x] soc/renesas/ra/ra4w1/Kconfig.defconfig
- [x] soc/renesas/ra/ra6e1/Kconfig.defconfig
- [x] soc/renesas/ra/ra6e2/Kconfig.defconfig
- [x] soc/renesas/ra/ra6m1/Kconfig.defconfig
- [x] soc/renesas/ra/ra6m2/Kconfig.defconfig
- [x] soc/renesas/ra/ra6m3/Kconfig.defconfig
- [x] soc/renesas/ra/ra6m4/Kconfig.defconfig
- [x] soc/renesas/ra/ra6m5/Kconfig.defconfig
- [x] soc/renesas/ra/ra8d1/Kconfig.defconfig
- [x] soc/renesas/ra/ra8m1/Kconfig.defconfig
- [x] soc/renesas/ra/ra8t1/Kconfig.defconfig
___
@aaillet @lorc #81666 
- [x] soc/renesas/rcar/rcar_gen3/Kconfig.defconfig
- [x] soc/renesas/rcar/rcar_gen4/Kconfig.defconfig.r8a779f0
___
@andy-liu-telink
- [x] soc/telink/tlsr/tlsr951x/Kconfig.defconfig
___
@vaishnavachath
- [x] soc/ti/k3/am6x/Kconfig.defconfig

Please submit fixes then tick once they have been merged.

**Comment by billwatersiii** [comment]
These boards are not owned by Infineon (ifyall):

boards/madmachine/mm_feather/mm_feather_defconfig
boards/madmachine/mm_swiftio/mm_swiftio_defconfig

**Comment by nordicjm** [comment]
> These boards are not owned by Infineon (ifyall):
> 
> boards/madmachine/mm_feather/mm_feather_defconfig boards/madmachine/mm_swiftio/mm_swiftio_defconfig

There is actually a gap there but for some reason github is added a gap between the infineon ones too, but if you edit the post it will show no line gaps for the infineon boards but one after before the madmachine ones

**Comment by nordicjm** [comment]
A whole lot more:

@nandojve
- [ ] soc/atmel/sam/Kconfig.defconfig
- [ ] soc/atmel/sam0/Kconfig.defconfig
___
@nandojve
- [ ] soc/gd/gd32/Kconfig.defconfig
___
@ifyall
- [ ] soc/infineon/cat3/Kconfig.defconfig
___
@Dino-Li @GTLin08 @RuibinChang
- [ ] soc/ite/ec/it8xxx2/Kconfig.defconfig.series
___
@jvasanth1 @VenkatKotakonda @albertofloyd
- [ ] soc/microchip/mec/mec174x/Kconfig.defconfig.mec1743qlj
- [ ] soc/microchip/mec/mec174x/Kconfig.defconfig.mec1743qsz
- [ ] soc/microchip/mec/mec175x/Kconfig.defconfig.mec1753qlj
- [ ] soc/microchip/mec/mec175x/Kconfig.defconfig.mec1753qsz
- [ ] soc/microchip/mec/mech172x/Kconfig.defconfig.mech1723nlj
- [ ] soc/microchip/mec/mech172x/Kconfig.defconfig.mech1723nsz
___
@yonsch
- [ ] soc/raspberrypi/Kconfig.defconfig
___
@soburi @KhiemNguyenT
- [ ] soc/renesas/ra/ra2a1/Kconfig.defconfig
- [ ] soc/renesas/ra/ra4e2/Kconfig.defconfig
- [ ] soc/renesas/ra/ra4m2/Kconfig.defconfig
- [ ] soc/renesas/ra/ra4m3/Kconfig.defconfig
- [ ] soc/renesas/ra/ra4w1/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6e1/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6e2/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6m1/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6m2/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6m3/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6m4/Kconfig.defconfig
- [ ] soc/renesas/ra/ra6m5/Kconfig.defconfig
- [ ] soc/renesas/ra/ra8d1/Kconfig.defconfig
- [ ] soc/renesas/ra/ra8m1/Kconfig.defconfig
- [ ] soc/renesas/ra/ra8t1/Kconfig.defconfig
___
@aaillet @lorc
- [ ] soc/renesas/rcar/rcar_gen3/Kconfig.defconfig
- [ ] soc/renesas/rcar/rcar_gen4/Kconfig.defconfig.r8a779f0
___
@andy-liu-telink
- [ ] soc/telink/tlsr/tlsr951x/Kconfig.defconfig
___
@vaishnavachath
- [ ] soc/ti/k3/am6x/Kconfig.defconfig

**Comment by nordicjm** [comment]
@MulinChao @ChiHuaL @cyliangtw @jhedberg @ruuddw @evgeniy-paltsev @nandojve @ifyall @jvasanth1 @VenkatKotakonda @albertofloyd @soburi @KhiemNguyenT @aaillet @lorc @andy-liu-telink @vaishnavachath you all have boards/socs here with this issue, can you submit fixes for them to select PINCTRL properly?

**Comment by soburi** [comment]
> @MulinChao @ChiHuaL @cyliangtw @jhedberg @ruuddw @evgeniy-paltsev @nandojve @ifyall @jvasanth1 @VenkatKotakonda @albertofloyd @soburi @KhiemNguyenT @aaillet @lorc @andy-liu-telink @vaishnavachath you all have boards/socs here with this issue, can you submit fixes for them to select PINCTRL properly?

My part, 

> @soburi https://github.com/zephyrproject-rtos/zephyr/pull/76794
> 
> boards/arduino/uno_r4/arduino_uno_r4_minima_defconfig
> boards/arduino/uno_r4/arduino_uno_r4_wifi_defconfig

This is now waiting to merge.

> @soburi @KhiemNguyenT
> 
> soc/renesas/ra/ra2a1/Kconfig.defconfig
> ...


@KhiemNguyenT

First, Could the Renesas team please handle it?

**Comment by ifyall** [comment]
@soburi, I have marked the Infineon boards as done. They were handled in https://github.com/zephyrproject-rtos/zephyr/pull/78734

**Comment by soburi** [comment]
@ifyall 
> @soburi, I have marked the Infineon boards as done. They were handled in #78734

Thank you for the update.

@nordicjm 
Please confirm it.

**Comment by nordicjm** [comment]
@ifyall seems `soc/infineon/cat3/Kconfig.defconfig` has not been done

**Comment by rruuaanng** [comment]
I've commit a PR about openisa. Maybe we can add me to task list ;)

**Comment by nordicjm** [comment]
Pinging on boards/socs that have had no response or fix posted:

@jvasanth1

boards/microchip/mec1501modular_assy6885/mec1501modular_assy6885_defconfig
boards/microchip/mec1501modular_assy6885/mec1501modular_assy6885_defconfig
boards/microchip/mec15xxevb_assy6853/mec15xxevb_assy6853_defconfig
boards/microchip/mec15xxevb_assy6853/mec15xxevb_assy6853_defconfig
boards/microchip/mec172xevb_assy6906/mec172xevb_assy6906_defconfig
boards/microchip/mec172xmodular_assy6930/mec172xmodular_assy6930_defconfig

@jhedberg

boards/silabs/dev_kits/sltb010a/sltb010a_defconfig
boards/silabs/dev_kits/xg24_dk2601b/xg24_dk2601b_defconfig
boards/silabs/dev_kits/xg27_dk2602a/xg27_dk2602a_defconfig
boards/silabs/radio_boards/slwrb4180a/slwrb4180a_defconfig
boards/silabs/radio_boards/xg24_rb4187c/xg24_rb4187c_defconfig

@ruuddw @evgeniy-paltsev

boards/snps/emsdp/emsdp_emsdp_em11d_defconfig

@vaishnavachath

boards/ti/cc1352p1_launchxl/cc1352p1_launchxl_defconfig
boards/ti/cc1352r1_launchxl/cc1352r1_launchxl_defconfig
boards/ti/cc1352r_sensortag/cc1352r_sensortag_defconfig
boards/ti/cc26x2r1_launchxl/cc26x2r1_launchxl_defconfig
boards/ti/sk_am62/sk_am62_am6234_m4_defconfig
soc/ti/k3/am6x/Kconfig.defconfig

@ifyall

soc/infineon/cat3/Kconfig.defconfig

@jvasanth1 @VenkatKotakonda @albertofloyd

soc/microchip/mec/mec174x/Kconfig.defconfig.mec1743qlj
soc/microchip/mec/mec174x/Kconfig.defconfig.mec1743qsz
soc/microchip/mec/mec175x/Kconfig.defconfig.mec1753qlj
soc/microchip/mec/mec175x/Kconfig.defconfig.mec1753qsz
soc/microchip/mec/mech172x/Kconfig.defconfig.mech1723nlj
soc/microchip/mec/mech172x/Kconfig.defconfig.mech1723nsz

@aaillet @lorc

soc/renesas/rcar/rcar_gen3/Kconfig.defconfig
soc/renesas/rcar/rcar_gen4/Kconfig.defconfig.r8a779f0

@andy-liu-telink

soc/telink/tlsr/tlsr951x/Kconfig.defconfig

The target for this is zephyr 4.1, please submit fixes in the short term future for this.

**Comment by fabiobaltieri** [comment]
Arch WG:
- summarized the issue, asking for response from the board maintainers
- @erwango asked if this is going to have to done for CONFIG_GPIO as well
  - the pinctrl driver for stm32 depends on gpio, so every board needs to enable gpio to use pinctrl

**Comment by tagunil** [comment]
> > > boards/snps/emsdp/emsdp_emsdp_em11d_defconfig
> > 
> > 
> > Hi @nordicjm, What should we do if our SoCs use generic drivers like spi_dw or uart_ns16550, which might require PINCTRL depending on specific hardware configuration of these IPs? We'd really like to avoid making PINCTRL a hard requirement for the drivers, keeping the dependency somewhere between the SoC level and the board level.
> 
> `select PINCTRL if ...`

Do you mean listing the SoCs in the Kconfig of the driver? Wouldn't such a list grow uncontrollably for drivers used by many different SoCs from different vendors, like ns16550?

**Comment by gmarull** [comment]
> > > > boards/snps/emsdp/emsdp_emsdp_em11d_defconfig
> > > 
> > > 
> > > Hi @nordicjm, What should we do if our SoCs use generic drivers like spi_dw or uart_ns16550, which might require PINCTRL depending on specific hardware configuration of these IPs? We'd really like to avoid making PINCTRL a hard requirement for the drivers, keeping the dependency somewhere between the SoC level and the board level.
> > 
> > 
> > `select PINCTRL if ...`
> 
> Do you mean listing the SoCs in the Kconfig of the driver? Wouldn't such a list grow uncontrollably for drivers used by many different SoCs from different vendors, like ns16550?

you can always do `select PINCTRL if !...` I guess they'll be the exception and not the rule. After all, these generic APIs (like pinctrl) exist to facilitate generic IP drivers.

**Comment by jhedberg** [comment]
Considering that we have a bunch of Kconfig macros for DT, I wonder if it'd be possible to use those to detect if a DT node with the ns16550 compat has a `pinctrl-N` property, and if so `select PINCTRL`?

**Comment by jhedberg** [comment]
> Considering that we have a bunch of Kconfig macros for DT, I wonder if it'd be possible to use those to detect if a DT node with the ns16550 compat has a `pinctrl-N` property, and if so `select PINCTRL`?

What I mean is, something like this:
```
select PINCTRL if $(dt_compat_any_has_prop,$(DT_COMPAT_NS16550),pinctrl-0)
```
