### ISSUE TITLE
Zephyr 4.0  security related modules update overview

### ISSUE THREAD

**Issue by dkalowsk** [zephyrproject-rtos/zephyr#80489]
Umbrella issue for tracking security related modules which may require an update before Zephyr 4.0.

- [x] https://github.com/zephyrproject-rtos/mbedtls (@ceolin , @d3zd3z , @tomi-font)
  - Looks to be on upstream latest 3.6.2 LTS https://github.com/Mbed-TLS/mbedtls
- [x] https://github.com/zephyrproject-rtos/tinycrypt (@ceolin )
  - Is marked as deprecated.  Should the MAINTAINERS.yml also be updated?
  - https://github.com/zephyrproject-rtos/zephyr/pull/79653  Part 1
  - ~~https://github.com/zephyrproject-rtos/zephyr/pull/79931  Part 2~~ (not for 4.0)
- [x] https://github.com/zephyrproject-rtos/trusted-firmware-m (@d3zd3z , @ithinuel , @tomi-font  )
  - TF-M 2.1.1 update PR: https://github.com/zephyrproject-rtos/zephyr/pull/80667
- [x] https://github.com/zephyrproject-rtos/trusted-firmware-a (@povergoing, @sgrrzhf, @ithinuel )
  - Seems to be behind (2.7) and not on the LTS (2.10).
  -  I thought we updated to 2.10 with https://github.com/zephyrproject-rtos/zephyr/pull/74111 but I don't see those tags in our repo.
- [x] https://github.com/zephyrproject-rtos/uoscore-uedhoc (@rlubos , @StefanHri )

**Comment by tomi-font** [comment]
I'll take care of updating TF-M to 2.1.1 once it is officially released.

**Comment by rlubos** [comment]
`uoscore-uedhoc` is up to date with upstream.

**Comment by dkalowsk** [comment]
tinycrypt deprecation is moved to 4.1

**Comment by mmahadevan108** [comment]
All items addressed.
