### ISSUE TITLE
Stepper API: Rename motion control related functions

### ISSUE THREAD

**Issue by jilaypandya** [zephyrproject-rtos/zephyr#81789]
### Problem description

Stepper API in current state comprises of following functions for motion control:

1.  [stepper_move](https://docs.zephyrproject.org/latest/doxygen/html/group__stepper__interface.html#ga7622a8e1e95b2bbb2dc1273bd84e88a5) for triggering relative motion.
2. [stepper_set_target_position](https://docs.zephyrproject.org/latest/doxygen/html/group__stepper__interface.html#ga2417b3ca2f77553bcd6a8b909e5f4d27) for triggering absolute position from **reference position**.
3. [stepper_set_actual_position](https://docs.zephyrproject.org/latest/doxygen/html/group__stepper__interface.html#gaf312a93167aabb39d814c6548991d6c6) for setting reference position.
4. [stepper_enable_constant_velocity_mode](https://docs.zephyrproject.org/latest/doxygen/html/group__stepper__interface.html#ga430250f6e3544e5bba49d5b6ceba1bf9) for triggering continuous motion in a given direction with a given velocity.

### Proposed change

These function names could become more intuitive if renamed as following:

1. `stepper_move` -> `stepper_move_by` for the  number of **relative** steps to move.
2. `stepper_set_target_position` -> `stepper_move_to` for the **absolute** position to be reached.
3. `stepper_set_actual_position` -> `stepper_set_reference_position` for the the **reference** position from which the steps are to be counted.
4. `stepper_enable_constant_velocity_mode` -> `stepper_run` for the brevity of the actual function. 

### Proposed change (Detailed)

Following files will have to be refactored:

API:
- [x] [stepper_api](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/drivers/stepper.h)
- [x] `move_to`, `move_by` and `run` shall be non-blocking operations

Drivers:
- [x] [tmc5041_stepper](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/stepper/adi_tmc/adi_tmc5041_stepper_controller.c)
- [x] [fake_stepper](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/stepper/fake_stepper_controller.c)
- [x] [gpio_stepper](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/stepper/gpio_stepper_controller.c)
- [x] [stepper_shell](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/stepper/stepper_shell.c)

Docs:
-  [x] [stepper.rst](https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/hardware/peripherals/stepper.rst) 

Tests:
- [x] [stepper_api](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/stepper/stepper_api/src/main.c)
- [x] [stepper_shell](https://github.com/zephyrproject-rtos/zephyr/blob/main/tests/drivers/stepper/shell/src/main.c)

Entry in migration guide:

- [x] [migration_guide_4_1](https://github.com/zephyrproject-rtos/zephyr/blob/main/doc/releases/migration-guide-4.1.rst)

### Dependencies

None
## Alternatives

```[tasklist]
### Tasks
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/81835
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/82162
- [ ] https://github.com/zephyrproject-rtos/zephyr/pull/82573
```

**Comment by rruuaanng** [comment]
I think it's great and I like the new names, but I don't know what other people think of it.
