### ISSUE TITLE
meta: Track progress on moving device drivers APIs to iterable structs

### ISSUE THREAD

**Issue by pdgendt** [zephyrproject-rtos/zephyr#82102]
Now that #71773 has been merged, device driver API declarations need to call the `DEVICE_API` macro.

Tracking all APIs:

- [x] `adc_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/72292
- [x] `auxdisplay_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82121
- [x] `bbram_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82123
- [x] `bc12_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82125
- [x] `bt_hci_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82126
- [x] `can_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82128
- [x] `can_transceiver_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82146
- [x] `cellular_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82147
- [x] `charger_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82148
- [x] `clock_control_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82150
- [x] `comparator_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82186
- [x] `coredump_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82164
- [x] `counter_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82166
- [x] `crypto_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82167
- [x] `dac_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82168
- [x] `dai_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82170
- [x] `display_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82171
- [x] `dma_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82292
- [x] `edac_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82172
- [x] `eeprom_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82173
- [x] `entropy_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82174
- [x] `espi_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82296
- [x] `espi_saf_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82296
- [x] `ethphy_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82175
- [x] `flash_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82291
- [x] `fpga_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82176
- [x] `fuel_gauge_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82178
- [x] `gnss_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82179
- [x] `gpio_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82180
- [x] `haptics_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82181
- [x] `hwspinlock_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82182
- [x] `i2c_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82207
- [x] `i2s_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82233
- [x] `i3c_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82207
- [x] `ipm_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82234
- [x] `its_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82241
- [x] `ivshmem_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82242
- [x] `kscan_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82246
- [x] `led_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82249
- [x] `led_strip_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82250
- [x] `lora_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82264
- [x] `mbox_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82266
- [x] `mdio_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82267
- [x] `mipi_dbi_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82270
- [x] `mipi_dsi_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82271
- [x] `mspi_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82296
- [x] `nrf_clock_control_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82277
- [x] `pcie_ctrl_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82278
- [x] `pcie_ep_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82279
- [x] `peci_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `ps2_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `ptp_clock_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82301
- [x] `pwm_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82253
- [x] `regulator_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82290
- [x] `regulator_parent_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82290
- [x] `reset_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `retained_mem_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82301
- [x] `rtc_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82337
- [x] `sdhc_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82301
- [x] `sensor_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/72293
- [x] `shared_irq_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `smbus_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `spi_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82261
- [x] `stepper_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `svc_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `syscon_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `tcpc_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82285
- [x] `tee_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `tgpio_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `uart_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82293
- [x] `usbc_ppc_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82285
- [x] `usbc_vbus_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82285
- [x] `video_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82301
- [x] `vtd_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82283
- [x] `w1_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82297
- [x] `wdt_driver_api` https://github.com/zephyrproject-rtos/zephyr/pull/82300
- [x] Leftover APIs https://github.com/zephyrproject-rtos/zephyr/pull/83065
- [x] Leftover APIs before 4.1 https://github.com/zephyrproject-rtos/zephyr/pull/84437
- [x] Feature freeze for 4.1 https://github.com/zephyrproject-rtos/zephyr/pull/85645
- [ ] More feature freeze for 4.1 https://github.com/zephyrproject-rtos/zephyr/pull/86138

**Comment by yishai1999** [comment]
`led_driver_api` - https://github.com/zephyrproject-rtos/zephyr/pull/82249

**Comment by kartben** [comment]
@pdgendt success? :)

**Comment by pdgendt** [comment]
There's still some left from other merged PRs, will do another run, and maybe keep it for the 4.1 release?
