### ISSUE TITLE
1.13 Release Checklist

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#8320]
Add items as required
--------
- [x] Major enhancements:
  - [x] QM (Quality Managed) level qualification: #6906
  - [x] Support Precision Time Protocol (PTP): #3067
  - [x] Ecosystem and Tool Support: #2934 
  - [x] Logging Subsystem Enhancements: #6186
  - [x] Advanced Power Management: #3295 
  - [x] Add generation of SPDX TagValue documents: #7314
  - [x] TLS/DTLS socket support (experimental) #9007

- [x] Pre RC1 Steps
   - [x] Verify that all external components and external dependencies are up to date, for example 
      - mbedTLS
      - tinycrypt
      - FatFS
   - [x] Check known vulnerabilities, and fix exploitable vulnerabilities or verify them as unexploitable.

See https://github.com/zephyrproject-rtos/zephyr/wiki/Release-procedure for tagging details

--------
- [x] Release Notes WIP
  - [x] Create draft doc/release-notes-1.13.rst with feature summary from https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update doc/release-notes-1.13.rst details sections (relative to 1.12.0 release) as important issues are addressed (subsystem owners)
--------
- [x] Release data
  - [x] Update version in VERSION
  - [x] Run sanitycheck with --all --release and checkin resulting file scripts/sanity_chk/sanity_last_release.csv
--------
- [x] Finalize Release Notes
  - [x] Add list of GitHub issues (spell check issue list and fix in GitHub as needed)
  - [x] Review doc/release-notes-1.13.rst overview summary and details sections (see Sign-off below)
  - [x] Update doc/release-notes.rst (add reference to 1.13 notes)
  - [x] Update doc/index.rst (add reference to doc/1.13.0)
  - [x] Update doc/conf.py (add version to pick list)
  - [x] Update doc/LICENSING.rst for new components that do not have a license
  - [x] Create release and add notes on https://github.com/zephyrproject-rtos/zephyr/releases
  - [x] Final tagged release as zephyr-v1.13.0 (with release notes)
  - [x] Update https://www.zephyrproject.org/developers/#releases-overview
  - [x] Update https://www.zephyrproject.org/developers/#downloads (and git checkout version example)
  - [x] Update doc generation (in future should be automatic based on tag) ping @nashif
  - [x] Email devel@lists.zephyrproject.org & announce@lists.zephyrproject.org lists about release
--------
- [x]  Final Release Notes Sign-off
  - Subsystems
    - [x] Networking - @jukkar 
    - [x] Bluetooth - @jhedberg , @carlescufi 
  - Architectures
    - [x] ARC - @ruuddw 
    - [x] ARM - @galak, @MaureenHelm 
    - [x] X86 - @nashif, @andrewboie 
    - [x] Xtensa, RISCV32, NIOS-II - @nashif, @andrewboie 
  - [x] Security - @agross-linaro 
--------
- [ ] After Release
  - [x] Update patchlevel in Makefile (PATCHLEVEL = 99)
  - [ ] Marketing Blog for announcing release (https://www.zephyrproject.org/blog)
  - [x] Create branch for 1.13.x releases, update github protections for branch
  - [x] Create checklist issue for next release
  - [x] Add a comment to this issue linking to the next release checklist issue
  - [x] Update https://www.zephyrproject.org with latest stats from Github

**Comment by pfalcon** [comment]
Added TLS/DTLS sockets https://github.com/zephyrproject-rtos/zephyr/pull/9007 to major enhancements. @rlubos FYI.

**Comment by pfalcon** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/9391 should be documented as non backward-compatible change.

**Comment by nashif** [comment]
> #9391 should be documented as non backward-compatible change.

please add a line about this in the release notes draft.

**Comment by nashif** [comment]
@ruuddw, @vonhust  can you check the release notes please and see if ARC/synopsys changes are covered? 

@galak, @MaureenHelm ditto

**Comment by MaureenHelm** [comment]
@nashif Arm is done.

**Comment by ruuddw** [comment]
@nashif Synopsys/ARC changes are covered, just few suggestions to improve:
Designware -> Synopsys DesignWare 
arch: Support Synopsys nSIM device simulator -> please move (or repear) to Boards/SoC section, and rephrase to "arc: Support Synopsys ARC nSIM instruction set simulator"

**Comment by nashif** [comment]
Check list for 1.14 created: #9898
