### ISSUE TITLE
Migrate sensor drivers to device tree

### ISSUE THREAD

**Issue by MaureenHelm** [zephyrproject-rtos/zephyr#9962]
- [x] ak8975 [@galak] #22962
- [x] bma280 [@pabigot] #22103
- [x] dht (gpio) [@pabigot] #21424
- [x] grove-light [@pabigot] #21602
- [x] grove-temp [@pabigot] #21602
- [x] mpu6050 [@pabigot] #21565
- [x] pms7003 (uart device) [@galak] #22963

**Comment by MaureenHelm** [comment]
> I can take the ST sensors (lis*, lsm*) work.

Thanks!

> (Please note that in the above list the lis2mdl is missing as it has been recently added)

I added it to the list.

**Comment by avisconti** [comment]
@MaureenHelm 
Ticked lis2dh in the list above and moved on lis3dh.

**Comment by avisconti** [comment]
@MaureenHelm 
lis2mdl is ready but requires your review. (PR #11832)

**Comment by avisconti** [comment]
@MaureenHelm 
For completeness I added in the list above also lsm303dlhc accel/magn driver because they wer missing.
The good news is that they already use info from DT!

**Comment by galak** [comment]
@Mani-Sadhasivam can you look at converting the ccs811 to DTS?

**Comment by Mani-Sadhasivam** [comment]
@galak Okay. Will do it this weekend.

**Comment by galak** [comment]
> @galak Okay. Will do it this weekend.

thanks

**Comment by pabigot** [comment]
A more complete list of sensors that need to be converted is in #20017; could we close this and use that one?  @galak

**Comment by pabigot** [comment]
I've transferred the entries added here to #20017 so we don't have to look in two places to see what's being worked on.  The original list there only focused on uses that included interrupts, so I'll be adding a few more to that issue.

**Comment by galak** [comment]
> I've transferred the entries added here to #20017 so we don't have to look in two places to see what's being worked on. The original list there only focused on uses that included interrupts, so I'll be adding a few more to that issue.

My changes are purely DT changes, I didn't make any conversions to new GPIO API.  So not sure about moving this list into #20017, unless we want that PR to handle both changes (DT & updated GPIO API support).

**Comment by microbuilder** [comment]
@MaureenHelm I'm digging around to see what sensors I have from this list, but found a `hmc5883l` so I can take that one, and I'll see if I can find any other parts that don't have owners yet.

**Comment by galak** [comment]
> @Mani-Sadhasivam can you look at converting the ccs811 to DTS?

Looks like it was pretty easy so I did it #20347

**Comment by galak** [comment]
#22963 and #22962 should close this out.

**Comment by MaureenHelm** [comment]
> #22963 and #22962 should close this out.

Merged
